// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: map_msgs/OccupancyGridUpdate.proto

package map_msgs

import (
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OccupancyGridUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *std_msgs.Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	X      int32            `protobuf:"varint,2,opt,name=X,proto3" json:"X,omitempty"`
	Y      int32            `protobuf:"varint,3,opt,name=Y,proto3" json:"Y,omitempty"`
	Width  uint32           `protobuf:"varint,4,opt,name=Width,proto3" json:"Width,omitempty"`
	Height uint32           `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	Data   []int32          `protobuf:"varint,6,rep,packed,name=Data,proto3" json:"Data,omitempty"`
}

func (x *OccupancyGridUpdate) Reset() {
	*x = OccupancyGridUpdate{}
	mi := &file_map_msgs_OccupancyGridUpdate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupancyGridUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupancyGridUpdate) ProtoMessage() {}

func (x *OccupancyGridUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_map_msgs_OccupancyGridUpdate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupancyGridUpdate.ProtoReflect.Descriptor instead.
func (*OccupancyGridUpdate) Descriptor() ([]byte, []int) {
	return file_map_msgs_OccupancyGridUpdate_proto_rawDescGZIP(), []int{0}
}

func (x *OccupancyGridUpdate) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *OccupancyGridUpdate) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *OccupancyGridUpdate) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *OccupancyGridUpdate) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *OccupancyGridUpdate) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *OccupancyGridUpdate) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_map_msgs_OccupancyGridUpdate_proto protoreflect.FileDescriptor

var file_map_msgs_OccupancyGridUpdate_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x61, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4f, 0x63, 0x63, 0x75, 0x70,
	0x61, 0x6e, 0x63, 0x79, 0x47, 0x72, 0x69, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x15,
	0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x13, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x61,
	0x6e, 0x63, 0x79, 0x47, 0x72, 0x69, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a,
	0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x59, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x6d, 0x61, 0x70, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_map_msgs_OccupancyGridUpdate_proto_rawDescOnce sync.Once
	file_map_msgs_OccupancyGridUpdate_proto_rawDescData = file_map_msgs_OccupancyGridUpdate_proto_rawDesc
)

func file_map_msgs_OccupancyGridUpdate_proto_rawDescGZIP() []byte {
	file_map_msgs_OccupancyGridUpdate_proto_rawDescOnce.Do(func() {
		file_map_msgs_OccupancyGridUpdate_proto_rawDescData = protoimpl.X.CompressGZIP(file_map_msgs_OccupancyGridUpdate_proto_rawDescData)
	})
	return file_map_msgs_OccupancyGridUpdate_proto_rawDescData
}

var file_map_msgs_OccupancyGridUpdate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_map_msgs_OccupancyGridUpdate_proto_goTypes = []any{
	(*OccupancyGridUpdate)(nil), // 0: map_msgs.OccupancyGridUpdate
	(*std_msgs.Header)(nil),     // 1: std_msgs.Header
}
var file_map_msgs_OccupancyGridUpdate_proto_depIdxs = []int32{
	1, // 0: map_msgs.OccupancyGridUpdate.Header:type_name -> std_msgs.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_map_msgs_OccupancyGridUpdate_proto_init() }
func file_map_msgs_OccupancyGridUpdate_proto_init() {
	if File_map_msgs_OccupancyGridUpdate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_map_msgs_OccupancyGridUpdate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_map_msgs_OccupancyGridUpdate_proto_goTypes,
		DependencyIndexes: file_map_msgs_OccupancyGridUpdate_proto_depIdxs,
		MessageInfos:      file_map_msgs_OccupancyGridUpdate_proto_msgTypes,
	}.Build()
	File_map_msgs_OccupancyGridUpdate_proto = out.File
	file_map_msgs_OccupancyGridUpdate_proto_rawDesc = nil
	file_map_msgs_OccupancyGridUpdate_proto_goTypes = nil
	file_map_msgs_OccupancyGridUpdate_proto_depIdxs = nil
}
