// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: map_msgs/ProjectedMapInfo.proto

package map_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectedMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FrameId string  `protobuf:"bytes,1,opt,name=FrameId,proto3" json:"FrameId,omitempty"`
	X       float64 `protobuf:"fixed64,2,opt,name=X,proto3" json:"X,omitempty"`
	Y       float64 `protobuf:"fixed64,3,opt,name=Y,proto3" json:"Y,omitempty"`
	Width   float64 `protobuf:"fixed64,4,opt,name=Width,proto3" json:"Width,omitempty"`
	Height  float64 `protobuf:"fixed64,5,opt,name=Height,proto3" json:"Height,omitempty"`
	MinZ    float64 `protobuf:"fixed64,6,opt,name=MinZ,proto3" json:"MinZ,omitempty"`
	MaxZ    float64 `protobuf:"fixed64,7,opt,name=MaxZ,proto3" json:"MaxZ,omitempty"`
}

func (x *ProjectedMapInfo) Reset() {
	*x = ProjectedMapInfo{}
	mi := &file_map_msgs_ProjectedMapInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectedMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectedMapInfo) ProtoMessage() {}

func (x *ProjectedMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_map_msgs_ProjectedMapInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectedMapInfo.ProtoReflect.Descriptor instead.
func (*ProjectedMapInfo) Descriptor() ([]byte, []int) {
	return file_map_msgs_ProjectedMapInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectedMapInfo) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *ProjectedMapInfo) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ProjectedMapInfo) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ProjectedMapInfo) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ProjectedMapInfo) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProjectedMapInfo) GetMinZ() float64 {
	if x != nil {
		return x.MinZ
	}
	return 0
}

func (x *ProjectedMapInfo) GetMaxZ() float64 {
	if x != nil {
		return x.MaxZ
	}
	return 0
}

var File_map_msgs_ProjectedMapInfo_proto protoreflect.FileDescriptor

var file_map_msgs_ProjectedMapInfo_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x61, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x10,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x59, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x69, 0x6e, 0x5a, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x4d, 0x69, 0x6e, 0x5a, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x61, 0x78, 0x5a,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x4d, 0x61, 0x78, 0x5a, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f,
	0x6d, 0x61, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_map_msgs_ProjectedMapInfo_proto_rawDescOnce sync.Once
	file_map_msgs_ProjectedMapInfo_proto_rawDescData = file_map_msgs_ProjectedMapInfo_proto_rawDesc
)

func file_map_msgs_ProjectedMapInfo_proto_rawDescGZIP() []byte {
	file_map_msgs_ProjectedMapInfo_proto_rawDescOnce.Do(func() {
		file_map_msgs_ProjectedMapInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_map_msgs_ProjectedMapInfo_proto_rawDescData)
	})
	return file_map_msgs_ProjectedMapInfo_proto_rawDescData
}

var file_map_msgs_ProjectedMapInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_map_msgs_ProjectedMapInfo_proto_goTypes = []any{
	(*ProjectedMapInfo)(nil), // 0: map_msgs.ProjectedMapInfo
}
var file_map_msgs_ProjectedMapInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_map_msgs_ProjectedMapInfo_proto_init() }
func file_map_msgs_ProjectedMapInfo_proto_init() {
	if File_map_msgs_ProjectedMapInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_map_msgs_ProjectedMapInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_map_msgs_ProjectedMapInfo_proto_goTypes,
		DependencyIndexes: file_map_msgs_ProjectedMapInfo_proto_depIdxs,
		MessageInfos:      file_map_msgs_ProjectedMapInfo_proto_msgTypes,
	}.Build()
	File_map_msgs_ProjectedMapInfo_proto = out.File
	file_map_msgs_ProjectedMapInfo_proto_rawDesc = nil
	file_map_msgs_ProjectedMapInfo_proto_goTypes = nil
	file_map_msgs_ProjectedMapInfo_proto_depIdxs = nil
}
