// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: geometry_msgs/Polygon.proto

package geometry_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Polygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*Point32 `protobuf:"bytes,1,rep,name=Points,proto3" json:"Points,omitempty"`
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_geometry_msgs_Polygon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_msgs_Polygon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_geometry_msgs_Polygon_proto_rawDescGZIP(), []int{0}
}

func (x *Polygon) GetPoints() []*Point32 {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_geometry_msgs_Polygon_proto protoreflect.FileDescriptor

var file_geometry_msgs_Polygon_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67,
	0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x1b, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x33, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x07, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x06, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geometry_msgs_Polygon_proto_rawDescOnce sync.Once
	file_geometry_msgs_Polygon_proto_rawDescData = file_geometry_msgs_Polygon_proto_rawDesc
)

func file_geometry_msgs_Polygon_proto_rawDescGZIP() []byte {
	file_geometry_msgs_Polygon_proto_rawDescOnce.Do(func() {
		file_geometry_msgs_Polygon_proto_rawDescData = protoimpl.X.CompressGZIP(file_geometry_msgs_Polygon_proto_rawDescData)
	})
	return file_geometry_msgs_Polygon_proto_rawDescData
}

var file_geometry_msgs_Polygon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_geometry_msgs_Polygon_proto_goTypes = []any{
	(*Polygon)(nil), // 0: geometry_msgs.Polygon
	(*Point32)(nil), // 1: geometry_msgs.Point32
}
var file_geometry_msgs_Polygon_proto_depIdxs = []int32{
	1, // 0: geometry_msgs.Polygon.Points:type_name -> geometry_msgs.Point32
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_geometry_msgs_Polygon_proto_init() }
func file_geometry_msgs_Polygon_proto_init() {
	if File_geometry_msgs_Polygon_proto != nil {
		return
	}
	file_geometry_msgs_Point32_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geometry_msgs_Polygon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geometry_msgs_Polygon_proto_goTypes,
		DependencyIndexes: file_geometry_msgs_Polygon_proto_depIdxs,
		MessageInfos:      file_geometry_msgs_Polygon_proto_msgTypes,
	}.Build()
	File_geometry_msgs_Polygon_proto = out.File
	file_geometry_msgs_Polygon_proto_rawDesc = nil
	file_geometry_msgs_Polygon_proto_goTypes = nil
	file_geometry_msgs_Polygon_proto_depIdxs = nil
}
