//autogenerated:yes
//nolint:revive,lll
package obstacle_detector

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type CircleObstacle struct {
    msg.Package `ros:"obstacle_detector"`
    Center geometry_msgs.Point
    Velocity geometry_msgs.Vector3
    Radius float64
    TrueRadius float64
}

