//autogenerated:yes
//nolint:revive,lll
package stereo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type DisparityImage struct {
    msg.Package `ros:"stereo_msgs"`
    Header std_msgs.Header
    Image sensor_msgs.Image
    F float32
    T float32`rosname:"T"`
    ValidWindow sensor_msgs.RegionOfInterest
    MinDisparity float32
    MaxDisparity float32
    DeltaD float32
}

