// This file is auto-generated by rostoproto, do not edit Manually!!


package objectrecognitionactiongoal_sub


import (
    "github.com/bluenviron/goroslib/v2"
    "go_agent/telemetry/gengo/ros"
    )
    
    var msgStream chan object_recognition_msgs.ObjectRecognitionActionGoal
    var initialized bool = false
    var msgC object_recognition_msgs.ObjectRecognitionActionGoal

    func msgCallback(msg *object_recognition_msgs.ObjectRecognitionActionGoal) {
      if !initialized {
        return 
      }

      if msg != nil {
        msgC = *msg 
        msgStream <- msgC 
      }
    }

    func Init(topicName string, n *goroslib.Node, msgS chan object_recognition_msgs.ObjectRecognitionActionGoal, done chan int) error {
      msgStream = msgS 
      sub, err := goroslib.NewSubscriber(goroslib.SubscriberConf{
        Node: n,
        Topic: topicName,
        Callback: msgCallback, 
      })

      if err != nil {
        return fmt.Errorf("Failed to create subscriber for topic %q: %v",topicName,err)
      }
      initialized = true
      // wait for done 
      <-done
    }
    