//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type RGBDImage struct {
    msg.Package `ros:"rtabmap_ros"`
    Header std_msgs.Header
    RgbCameraInfo sensor_msgs.CameraInfo
    DepthCameraInfo sensor_msgs.CameraInfo
    Rgb sensor_msgs.Image
    Depth sensor_msgs.Image
    RgbCompressed sensor_msgs.CompressedImage
    DepthCompressed sensor_msgs.CompressedImage
    KeyPoints []KeyPoint
    Points []Point3f
    Descriptors []uint8
    GlobalDescriptor GlobalDescriptor
}

