//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type GlobalDescriptor struct {
    msg.Package `ros:"rtabmap_ros"`
    Header std_msgs.Header
    Type int32
    Info []uint8
    Data []uint8
}

