//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type OdomInfo struct {
    msg.Package `ros:"rtabmap_ros"`
    Header std_msgs.Header
    Lost bool
    Matches int32
    Inliers int32
    IcpInliersRatio float32`rosname:"icpInliersRatio"`
    IcpRotation float32`rosname:"icpRotation"`
    IcpTranslation float32`rosname:"icpTranslation"`
    IcpStructuralComplexity float32`rosname:"icpStructuralComplexity"`
    IcpStructuralDistribution float32`rosname:"icpStructuralDistribution"`
    IcpCorrespondences int32`rosname:"icpCorrespondences"`
    Covariance [36]float64
    Features int32
    LocalMapSize int32`rosname:"localMapSize"`
    LocalScanMapSize int32`rosname:"localScanMapSize"`
    LocalKeyFrames int32`rosname:"localKeyFrames"`
    LocalBundleOutliers int32`rosname:"localBundleOutliers"`
    LocalBundleConstraints int32`rosname:"localBundleConstraints"`
    LocalBundleTime float32`rosname:"localBundleTime"`
    KeyFrameAdded bool`rosname:"keyFrameAdded"`
    TimeEstimation float32`rosname:"timeEstimation"`
    TimeParticleFiltering float32`rosname:"timeParticleFiltering"`
    Stamp float32
    Interval float32
    DistanceTravelled float32`rosname:"distanceTravelled"`
    MemoryUsage int32`rosname:"memoryUsage"`
    GravityRollError float32`rosname:"gravityRollError"`
    GravityPitchError float32`rosname:"gravityPitchError"`
    LocalBundleIds []int32`rosname:"localBundleIds"`
    LocalBundleModels []CameraModels`rosname:"localBundleModels"`
    LocalBundlePoses []geometry_msgs.Pose`rosname:"localBundlePoses"`
    Transform geometry_msgs.Transform
    TransformFiltered geometry_msgs.Transform`rosname:"transformFiltered"`
    TransformGroundTruth geometry_msgs.Transform`rosname:"transformGroundTruth"`
    Guess geometry_msgs.Transform
    Type int32
    WordsKeys []int32`rosname:"wordsKeys"`
    WordsValues []KeyPoint`rosname:"wordsValues"`
    WordMatches []int32`rosname:"wordMatches"`
    WordInliers []int32`rosname:"wordInliers"`
    LocalMapKeys []int32`rosname:"localMapKeys"`
    LocalMapValues []Point3f`rosname:"localMapValues"`
    LocalScanMap sensor_msgs.PointCloud2`rosname:"localScanMap"`
    RefCorners []Point2f`rosname:"refCorners"`
    NewCorners []Point2f`rosname:"newCorners"`
    CornerInliers []int32`rosname:"cornerInliers"`
}

