//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type ScanDescriptor struct {
    msg.Package `ros:"rtabmap_ros"`
    Header std_msgs.Header
    Scan sensor_msgs.LaserScan
    ScanCloud sensor_msgs.PointCloud2
    GlobalDescriptor GlobalDescriptor
}

