//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Goal struct {
    msg.Package `ros:"rtabmap_ros"`
    Header std_msgs.Header
    NodeId int32
    NodeLabel string
    FrameId string
}

