//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type PublishMapReq struct {
    msg.Package `ros:"rtabmap_ros"`
    Global bool
    Optimized bool
    GraphOnly bool`rosname:"graphOnly"`
}



type PublishMapRes struct {
    msg.Package `ros:"rtabmap_ros"`
}

type PublishMap struct {
    msg.Package `ros:"rtabmap_ros"`
    PublishMapReq
    PublishMapRes
}
