//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type GetMap2Req struct {
    msg.Package `ros:"rtabmap_ros"`
    Global bool
    Optimized bool
    WithImages bool
    WithScans bool
    WithUserData bool
    WithGrids bool
    WithWords bool
    WithGlobalDescriptors bool
}



type GetMap2Res struct {
    msg.Package `ros:"rtabmap_ros"`
    Data MapData
}

type GetMap2 struct {
    msg.Package `ros:"rtabmap_ros"`
    GetMap2Req
    GetMap2Res
}
