//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ResetPoseReq struct {
    msg.Package `ros:"rtabmap_ros"`
    X float32
    Y float32
    Z float32
    Roll float32
    Pitch float32
    Yaw float32
}



type ResetPoseRes struct {
    msg.Package `ros:"rtabmap_ros"`
}

type ResetPose struct {
    msg.Package `ros:"rtabmap_ros"`
    ResetPoseReq
    ResetPoseRes
}
