//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SetLabelReq struct {
    msg.Package `ros:"rtabmap_ros"`
    NodeId int32
    NodeLabel string
}



type SetLabelRes struct {
    msg.Package `ros:"rtabmap_ros"`
}

type SetLabel struct {
    msg.Package `ros:"rtabmap_ros"`
    SetLabelReq
    SetLabelRes
}
