//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type GetMapReq struct {
    msg.Package `ros:"rtabmap_ros"`
    Global bool
    Optimized bool
    GraphOnly bool`rosname:"graphOnly"`
}



type GetMapRes struct {
    msg.Package `ros:"rtabmap_ros"`
    Data MapData
}

type GetMap struct {
    msg.Package `ros:"rtabmap_ros"`
    GetMapReq
    GetMapRes
}
