//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type CleanupLocalGridsReq struct {
    msg.Package `ros:"rtabmap_ros"`
    Radius int32
    FilterScans bool
}



type CleanupLocalGridsRes struct {
    msg.Package `ros:"rtabmap_ros"`
    Modified int32
}

type CleanupLocalGrids struct {
    msg.Package `ros:"rtabmap_ros"`
    CleanupLocalGridsReq
    CleanupLocalGridsRes
}
