//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type GetNodesInRadiusReq struct {
    msg.Package `ros:"rtabmap_ros"`
    NodeId int32
    X float32
    Y float32
    Z float32
    Radius float32
    K int32
}



type GetNodesInRadiusRes struct {
    msg.Package `ros:"rtabmap_ros"`
    Ids []int32
    Poses []geometry_msgs.Pose
    DistsSqr []float32`rosname:"distsSqr"`
}

type GetNodesInRadius struct {
    msg.Package `ros:"rtabmap_ros"`
    GetNodesInRadiusReq
    GetNodesInRadiusRes
}
