//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type AddLinkReq struct {
    msg.Package `ros:"rtabmap_ros"`
    Link Link
}



type AddLinkRes struct {
    msg.Package `ros:"rtabmap_ros"`
}

type AddLink struct {
    msg.Package `ros:"rtabmap_ros"`
    AddLinkReq
    AddLinkRes
}
