//autogenerated:yes
//nolint:revive,lll
package rtabmap_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ListLabelsReq struct {
    msg.Package `ros:"rtabmap_ros"`
}



type ListLabelsRes struct {
    msg.Package `ros:"rtabmap_ros"`
    Ids []int32
    Labels []string
}

type ListLabels struct {
    msg.Package `ros:"rtabmap_ros"`
    ListLabelsReq
    ListLabelsRes
}
