//autogenerated:yes
//nolint:revive,lll
package costmap_2d

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type VoxelGrid struct {
    msg.Package `ros:"costmap_2d"`
    Header std_msgs.Header
    Data []uint32
    Origin geometry_msgs.Point32
    Resolutions geometry_msgs.Vector3
    SizeX uint32
    SizeY uint32
    SizeZ uint32
}

