// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: rtabmap_ros/CameraModel.proto

package rtabmap_ros

import (
	geometry_msgs "go_agent/telemetry/genproto/ros/geometry_msgs"
	sensor_msgs "go_agent/telemetry/genproto/ros/sensor_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraInfo     *sensor_msgs.CameraInfo  `protobuf:"bytes,1,opt,name=CameraInfo,proto3" json:"CameraInfo,omitempty"`
	LocalTransform *geometry_msgs.Transform `protobuf:"bytes,2,opt,name=LocalTransform,proto3" json:"LocalTransform,omitempty"`
}

func (x *CameraModel) Reset() {
	*x = CameraModel{}
	mi := &file_rtabmap_ros_CameraModel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraModel) ProtoMessage() {}

func (x *CameraModel) ProtoReflect() protoreflect.Message {
	mi := &file_rtabmap_ros_CameraModel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraModel.ProtoReflect.Descriptor instead.
func (*CameraModel) Descriptor() ([]byte, []int) {
	return file_rtabmap_ros_CameraModel_proto_rawDescGZIP(), []int{0}
}

func (x *CameraModel) GetCameraInfo() *sensor_msgs.CameraInfo {
	if x != nil {
		return x.CameraInfo
	}
	return nil
}

func (x *CameraModel) GetLocalTransform() *geometry_msgs.Transform {
	if x != nil {
		return x.LocalTransform
	}
	return nil
}

var File_rtabmap_ros_CameraModel_proto protoreflect.FileDescriptor

var file_rtabmap_ros_CameraModel_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x74, 0x61, 0x62, 0x6d, 0x61, 0x70, 0x5f, 0x72, 0x6f, 0x73, 0x2f, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x72, 0x74, 0x61, 0x62, 0x6d, 0x61, 0x70, 0x5f, 0x72, 0x6f, 0x73, 0x1a, 0x1d, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x73, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x0b, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x43, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x40, 0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x65, 0x6f,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x52, 0x0e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x72, 0x74, 0x61, 0x62, 0x6d, 0x61, 0x70, 0x5f,
	0x72, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rtabmap_ros_CameraModel_proto_rawDescOnce sync.Once
	file_rtabmap_ros_CameraModel_proto_rawDescData = file_rtabmap_ros_CameraModel_proto_rawDesc
)

func file_rtabmap_ros_CameraModel_proto_rawDescGZIP() []byte {
	file_rtabmap_ros_CameraModel_proto_rawDescOnce.Do(func() {
		file_rtabmap_ros_CameraModel_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtabmap_ros_CameraModel_proto_rawDescData)
	})
	return file_rtabmap_ros_CameraModel_proto_rawDescData
}

var file_rtabmap_ros_CameraModel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rtabmap_ros_CameraModel_proto_goTypes = []any{
	(*CameraModel)(nil),             // 0: rtabmap_ros.CameraModel
	(*sensor_msgs.CameraInfo)(nil),  // 1: sensor_msgs.CameraInfo
	(*geometry_msgs.Transform)(nil), // 2: geometry_msgs.Transform
}
var file_rtabmap_ros_CameraModel_proto_depIdxs = []int32{
	1, // 0: rtabmap_ros.CameraModel.CameraInfo:type_name -> sensor_msgs.CameraInfo
	2, // 1: rtabmap_ros.CameraModel.LocalTransform:type_name -> geometry_msgs.Transform
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rtabmap_ros_CameraModel_proto_init() }
func file_rtabmap_ros_CameraModel_proto_init() {
	if File_rtabmap_ros_CameraModel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtabmap_ros_CameraModel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rtabmap_ros_CameraModel_proto_goTypes,
		DependencyIndexes: file_rtabmap_ros_CameraModel_proto_depIdxs,
		MessageInfos:      file_rtabmap_ros_CameraModel_proto_msgTypes,
	}.Build()
	File_rtabmap_ros_CameraModel_proto = out.File
	file_rtabmap_ros_CameraModel_proto_rawDesc = nil
	file_rtabmap_ros_CameraModel_proto_goTypes = nil
	file_rtabmap_ros_CameraModel_proto_depIdxs = nil
}
