// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: rtabmap_ros/GPS.proto

package rtabmap_ros

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stamp     float64 `protobuf:"fixed64,1,opt,name=Stamp,proto3" json:"Stamp,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,3,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Altitude  float64 `protobuf:"fixed64,4,opt,name=Altitude,proto3" json:"Altitude,omitempty"`
	Error     float64 `protobuf:"fixed64,5,opt,name=Error,proto3" json:"Error,omitempty"`
	Bearing   float64 `protobuf:"fixed64,6,opt,name=Bearing,proto3" json:"Bearing,omitempty"`
}

func (x *GPS) Reset() {
	*x = GPS{}
	mi := &file_rtabmap_ros_GPS_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPS) ProtoMessage() {}

func (x *GPS) ProtoReflect() protoreflect.Message {
	mi := &file_rtabmap_ros_GPS_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPS.ProtoReflect.Descriptor instead.
func (*GPS) Descriptor() ([]byte, []int) {
	return file_rtabmap_ros_GPS_proto_rawDescGZIP(), []int{0}
}

func (x *GPS) GetStamp() float64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

func (x *GPS) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GPS) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GPS) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *GPS) GetError() float64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *GPS) GetBearing() float64 {
	if x != nil {
		return x.Bearing
	}
	return 0
}

var File_rtabmap_ros_GPS_proto protoreflect.FileDescriptor

var file_rtabmap_ros_GPS_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x74, 0x61, 0x62, 0x6d, 0x61, 0x70, 0x5f, 0x72, 0x6f, 0x73, 0x2f, 0x47, 0x50,
	0x53, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x74, 0x61, 0x62, 0x6d, 0x61, 0x70,
	0x5f, 0x72, 0x6f, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x03, 0x47, 0x50, 0x53, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x42, 0x65, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x07, 0x42, 0x65, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x6f, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x72, 0x74, 0x61, 0x62,
	0x6d, 0x61, 0x70, 0x5f, 0x72, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rtabmap_ros_GPS_proto_rawDescOnce sync.Once
	file_rtabmap_ros_GPS_proto_rawDescData = file_rtabmap_ros_GPS_proto_rawDesc
)

func file_rtabmap_ros_GPS_proto_rawDescGZIP() []byte {
	file_rtabmap_ros_GPS_proto_rawDescOnce.Do(func() {
		file_rtabmap_ros_GPS_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtabmap_ros_GPS_proto_rawDescData)
	})
	return file_rtabmap_ros_GPS_proto_rawDescData
}

var file_rtabmap_ros_GPS_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rtabmap_ros_GPS_proto_goTypes = []any{
	(*GPS)(nil), // 0: rtabmap_ros.GPS
}
var file_rtabmap_ros_GPS_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rtabmap_ros_GPS_proto_init() }
func file_rtabmap_ros_GPS_proto_init() {
	if File_rtabmap_ros_GPS_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtabmap_ros_GPS_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rtabmap_ros_GPS_proto_goTypes,
		DependencyIndexes: file_rtabmap_ros_GPS_proto_depIdxs,
		MessageInfos:      file_rtabmap_ros_GPS_proto_msgTypes,
	}.Build()
	File_rtabmap_ros_GPS_proto = out.File
	file_rtabmap_ros_GPS_proto_rawDesc = nil
	file_rtabmap_ros_GPS_proto_goTypes = nil
	file_rtabmap_ros_GPS_proto_depIdxs = nil
}
