//autogenerated:yes
//nolint:revive,lll
package bond

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Status struct {
    msg.Package `ros:"bond"`
    Header std_msgs.Header
    Id string
    InstanceId string
    Active bool
    HeartbeatTimeout float32
    HeartbeatPeriod float32
}

