//autogenerated:yes
//nolint:revive,lll
package turtlebot3_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


const (
    SensorState_BUMPER_FORWARD uint8 = 1
    SensorState_BUMPER_BACKWARD uint8 = 2
    SensorState_CLIFF uint8 = 1
    SensorState_SONAR uint8 = 1
    SensorState_ILLUMINATION uint8 = 1
    SensorState_BUTTON0 uint8 = 1
    SensorState_BUTTON1 uint8 = 2
    SensorState_ERROR_LEFT_MOTOR uint8 = 1
    SensorState_ERROR_RIGHT_MOTOR uint8 = 2
    SensorState_TORQUE_ON uint8 = 1
    SensorState_TORQUE_OFF uint8 = 2
)

type SensorState struct {
    msg.Package `ros:"turtlebot3_msgs"`
    msg.Definitions `ros:"uint8 BUMPER_FORWARD=1,uint8 BUMPER_BACKWARD=2,uint8 CLIFF=1,uint8 SONAR=1,uint8 ILLUMINATION=1,uint8 BUTTON0=1,uint8 BUTTON1=2,uint8 ERROR_LEFT_MOTOR=1,uint8 ERROR_RIGHT_MOTOR=2,uint8 TORQUE_ON=1,uint8 TORQUE_OFF=2"`
    Header std_msgs.Header
    Bumper uint8
    Cliff float32
    Sonar float32
    Illumination float32
    Led uint8
    Button uint8
    Torque bool
    LeftEncoder int32
    RightEncoder int32
    Battery float32
}

