// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: foxglove_msgs/CameraCalibration.proto

package foxglove_msgs

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraCalibration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp       *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	FrameId         string               `protobuf:"bytes,2,opt,name=FrameId,proto3" json:"FrameId,omitempty"`
	Width           uint32               `protobuf:"varint,3,opt,name=Width,proto3" json:"Width,omitempty"`
	Height          uint32               `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	DistortionModel string               `protobuf:"bytes,5,opt,name=DistortionModel,proto3" json:"DistortionModel,omitempty"`
	D               []float64            `protobuf:"fixed64,6,rep,packed,name=D,proto3" json:"D,omitempty"`
	K               []float64            `protobuf:"fixed64,7,rep,packed,name=K,proto3" json:"K,omitempty"`
	R               []float64            `protobuf:"fixed64,8,rep,packed,name=R,proto3" json:"R,omitempty"`
	P               []float64            `protobuf:"fixed64,9,rep,packed,name=P,proto3" json:"P,omitempty"`
}

func (x *CameraCalibration) Reset() {
	*x = CameraCalibration{}
	mi := &file_foxglove_msgs_CameraCalibration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraCalibration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraCalibration) ProtoMessage() {}

func (x *CameraCalibration) ProtoReflect() protoreflect.Message {
	mi := &file_foxglove_msgs_CameraCalibration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraCalibration.ProtoReflect.Descriptor instead.
func (*CameraCalibration) Descriptor() ([]byte, []int) {
	return file_foxglove_msgs_CameraCalibration_proto_rawDescGZIP(), []int{0}
}

func (x *CameraCalibration) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CameraCalibration) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *CameraCalibration) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CameraCalibration) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CameraCalibration) GetDistortionModel() string {
	if x != nil {
		return x.DistortionModel
	}
	return ""
}

func (x *CameraCalibration) GetD() []float64 {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *CameraCalibration) GetK() []float64 {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *CameraCalibration) GetR() []float64 {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *CameraCalibration) GetP() []float64 {
	if x != nil {
		return x.P
	}
	return nil
}

var File_foxglove_msgs_CameraCalibration_proto protoreflect.FileDescriptor

var file_foxglove_msgs_CameraCalibration_proto_rawDesc = []byte{
	0x0a, 0x25, 0x66, 0x6f, 0x78, 0x67, 0x6c, 0x6f, 0x76, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x66, 0x6f, 0x78, 0x67, 0x6c, 0x6f, 0x76,
	0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x01, 0x0a, 0x11, 0x43, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x28, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x44, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x44, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x01, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x4b, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x01, 0x52, 0x01, 0x4b, 0x12, 0x0c, 0x0a, 0x01, 0x52, 0x18, 0x08, 0x20, 0x03, 0x28, 0x01,
	0x52, 0x01, 0x52, 0x12, 0x0c, 0x0a, 0x01, 0x50, 0x18, 0x09, 0x20, 0x03, 0x28, 0x01, 0x52, 0x01,
	0x50, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6f, 0x78, 0x67, 0x6c, 0x6f, 0x76, 0x65, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foxglove_msgs_CameraCalibration_proto_rawDescOnce sync.Once
	file_foxglove_msgs_CameraCalibration_proto_rawDescData = file_foxglove_msgs_CameraCalibration_proto_rawDesc
)

func file_foxglove_msgs_CameraCalibration_proto_rawDescGZIP() []byte {
	file_foxglove_msgs_CameraCalibration_proto_rawDescOnce.Do(func() {
		file_foxglove_msgs_CameraCalibration_proto_rawDescData = protoimpl.X.CompressGZIP(file_foxglove_msgs_CameraCalibration_proto_rawDescData)
	})
	return file_foxglove_msgs_CameraCalibration_proto_rawDescData
}

var file_foxglove_msgs_CameraCalibration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_foxglove_msgs_CameraCalibration_proto_goTypes = []any{
	(*CameraCalibration)(nil),   // 0: foxglove_msgs.CameraCalibration
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_foxglove_msgs_CameraCalibration_proto_depIdxs = []int32{
	1, // 0: foxglove_msgs.CameraCalibration.Timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_foxglove_msgs_CameraCalibration_proto_init() }
func file_foxglove_msgs_CameraCalibration_proto_init() {
	if File_foxglove_msgs_CameraCalibration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foxglove_msgs_CameraCalibration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foxglove_msgs_CameraCalibration_proto_goTypes,
		DependencyIndexes: file_foxglove_msgs_CameraCalibration_proto_depIdxs,
		MessageInfos:      file_foxglove_msgs_CameraCalibration_proto_msgTypes,
	}.Build()
	File_foxglove_msgs_CameraCalibration_proto = out.File
	file_foxglove_msgs_CameraCalibration_proto_rawDesc = nil
	file_foxglove_msgs_CameraCalibration_proto_goTypes = nil
	file_foxglove_msgs_CameraCalibration_proto_depIdxs = nil
}
