// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: foxglove_msgs/KeyValuePair.proto

package foxglove_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyValuePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_foxglove_msgs_KeyValuePair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_foxglove_msgs_KeyValuePair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_foxglove_msgs_KeyValuePair_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_foxglove_msgs_KeyValuePair_proto protoreflect.FileDescriptor

var file_foxglove_msgs_KeyValuePair_proto_rawDesc = []byte{
	0x0a, 0x20, 0x66, 0x6f, 0x78, 0x67, 0x6c, 0x6f, 0x76, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x66, 0x6f, 0x78, 0x67, 0x6c, 0x6f, 0x76, 0x65, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x22, 0x36, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6f, 0x78,
	0x67, 0x6c, 0x6f, 0x76, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_foxglove_msgs_KeyValuePair_proto_rawDescOnce sync.Once
	file_foxglove_msgs_KeyValuePair_proto_rawDescData = file_foxglove_msgs_KeyValuePair_proto_rawDesc
)

func file_foxglove_msgs_KeyValuePair_proto_rawDescGZIP() []byte {
	file_foxglove_msgs_KeyValuePair_proto_rawDescOnce.Do(func() {
		file_foxglove_msgs_KeyValuePair_proto_rawDescData = protoimpl.X.CompressGZIP(file_foxglove_msgs_KeyValuePair_proto_rawDescData)
	})
	return file_foxglove_msgs_KeyValuePair_proto_rawDescData
}

var file_foxglove_msgs_KeyValuePair_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_foxglove_msgs_KeyValuePair_proto_goTypes = []any{
	(*KeyValuePair)(nil), // 0: foxglove_msgs.KeyValuePair
}
var file_foxglove_msgs_KeyValuePair_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foxglove_msgs_KeyValuePair_proto_init() }
func file_foxglove_msgs_KeyValuePair_proto_init() {
	if File_foxglove_msgs_KeyValuePair_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foxglove_msgs_KeyValuePair_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foxglove_msgs_KeyValuePair_proto_goTypes,
		DependencyIndexes: file_foxglove_msgs_KeyValuePair_proto_depIdxs,
		MessageInfos:      file_foxglove_msgs_KeyValuePair_proto_msgTypes,
	}.Build()
	File_foxglove_msgs_KeyValuePair_proto = out.File
	file_foxglove_msgs_KeyValuePair_proto_rawDesc = nil
	file_foxglove_msgs_KeyValuePair_proto_goTypes = nil
	file_foxglove_msgs_KeyValuePair_proto_depIdxs = nil
}
