// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: foxglove_msgs/Point2.proto

package foxglove_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=X,proto3" json:"X,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (x *Point2) Reset() {
	*x = Point2{}
	mi := &file_foxglove_msgs_Point2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point2) ProtoMessage() {}

func (x *Point2) ProtoReflect() protoreflect.Message {
	mi := &file_foxglove_msgs_Point2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point2.ProtoReflect.Descriptor instead.
func (*Point2) Descriptor() ([]byte, []int) {
	return file_foxglove_msgs_Point2_proto_rawDescGZIP(), []int{0}
}

func (x *Point2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_foxglove_msgs_Point2_proto protoreflect.FileDescriptor

var file_foxglove_msgs_Point2_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x66, 0x6f, 0x78, 0x67, 0x6c, 0x6f, 0x76, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x66, 0x6f,
	0x78, 0x67, 0x6c, 0x6f, 0x76, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x24, 0x0a, 0x06, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x59, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6f, 0x78, 0x67, 0x6c, 0x6f, 0x76, 0x65, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foxglove_msgs_Point2_proto_rawDescOnce sync.Once
	file_foxglove_msgs_Point2_proto_rawDescData = file_foxglove_msgs_Point2_proto_rawDesc
)

func file_foxglove_msgs_Point2_proto_rawDescGZIP() []byte {
	file_foxglove_msgs_Point2_proto_rawDescOnce.Do(func() {
		file_foxglove_msgs_Point2_proto_rawDescData = protoimpl.X.CompressGZIP(file_foxglove_msgs_Point2_proto_rawDescData)
	})
	return file_foxglove_msgs_Point2_proto_rawDescData
}

var file_foxglove_msgs_Point2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_foxglove_msgs_Point2_proto_goTypes = []any{
	(*Point2)(nil), // 0: foxglove_msgs.Point2
}
var file_foxglove_msgs_Point2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foxglove_msgs_Point2_proto_init() }
func file_foxglove_msgs_Point2_proto_init() {
	if File_foxglove_msgs_Point2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foxglove_msgs_Point2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foxglove_msgs_Point2_proto_goTypes,
		DependencyIndexes: file_foxglove_msgs_Point2_proto_depIdxs,
		MessageInfos:      file_foxglove_msgs_Point2_proto_msgTypes,
	}.Build()
	File_foxglove_msgs_Point2_proto = out.File
	file_foxglove_msgs_Point2_proto_rawDesc = nil
	file_foxglove_msgs_Point2_proto_goTypes = nil
	file_foxglove_msgs_Point2_proto_depIdxs = nil
}
