// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: people_msgs/Person.proto

package people_msgs

import (
	geometry_msgs "go_agent/telemetry/genproto/ros/geometry_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Position    *geometry_msgs.Point `protobuf:"bytes,2,opt,name=Position,proto3" json:"Position,omitempty"`
	Velocity    *geometry_msgs.Point `protobuf:"bytes,3,opt,name=Velocity,proto3" json:"Velocity,omitempty"`
	Reliability float64              `protobuf:"fixed64,4,opt,name=Reliability,proto3" json:"Reliability,omitempty"`
	Tagnames    []string             `protobuf:"bytes,5,rep,name=Tagnames,proto3" json:"Tagnames,omitempty"`
	Tags        []string             `protobuf:"bytes,6,rep,name=Tags,proto3" json:"Tags,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_people_msgs_Person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_people_msgs_Person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_people_msgs_Person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetPosition() *geometry_msgs.Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Person) GetVelocity() *geometry_msgs.Point {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Person) GetReliability() float64 {
	if x != nil {
		return x.Reliability
	}
	return 0
}

func (x *Person) GetTagnames() []string {
	if x != nil {
		return x.Tagnames
	}
	return nil
}

func (x *Person) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_people_msgs_Person_proto protoreflect.FileDescriptor

var file_people_msgs_Person_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x19, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x30, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x08, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x56, 0x65, 0x6c,
	0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x52, 0x65, 0x6c, 0x69,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x67, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x67, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x6f, 0x5f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x70, 0x65, 0x6f, 0x70, 0x6c,
	0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_people_msgs_Person_proto_rawDescOnce sync.Once
	file_people_msgs_Person_proto_rawDescData = file_people_msgs_Person_proto_rawDesc
)

func file_people_msgs_Person_proto_rawDescGZIP() []byte {
	file_people_msgs_Person_proto_rawDescOnce.Do(func() {
		file_people_msgs_Person_proto_rawDescData = protoimpl.X.CompressGZIP(file_people_msgs_Person_proto_rawDescData)
	})
	return file_people_msgs_Person_proto_rawDescData
}

var file_people_msgs_Person_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_people_msgs_Person_proto_goTypes = []any{
	(*Person)(nil),              // 0: people_msgs.Person
	(*geometry_msgs.Point)(nil), // 1: geometry_msgs.Point
}
var file_people_msgs_Person_proto_depIdxs = []int32{
	1, // 0: people_msgs.Person.Position:type_name -> geometry_msgs.Point
	1, // 1: people_msgs.Person.Velocity:type_name -> geometry_msgs.Point
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_people_msgs_Person_proto_init() }
func file_people_msgs_Person_proto_init() {
	if File_people_msgs_Person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_people_msgs_Person_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_people_msgs_Person_proto_goTypes,
		DependencyIndexes: file_people_msgs_Person_proto_depIdxs,
		MessageInfos:      file_people_msgs_Person_proto_msgTypes,
	}.Build()
	File_people_msgs_Person_proto = out.File
	file_people_msgs_Person_proto_rawDesc = nil
	file_people_msgs_Person_proto_goTypes = nil
	file_people_msgs_Person_proto_depIdxs = nil
}
