// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: people_msgs/PositionMeasurementArray.proto

package people_msgs

import (
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionMeasurementArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header       *std_msgs.Header       `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	People       []*PositionMeasurement `protobuf:"bytes,2,rep,name=People,proto3" json:"People,omitempty"`
	Cooccurrence []float32              `protobuf:"fixed32,3,rep,packed,name=Cooccurrence,proto3" json:"Cooccurrence,omitempty"`
}

func (x *PositionMeasurementArray) Reset() {
	*x = PositionMeasurementArray{}
	mi := &file_people_msgs_PositionMeasurementArray_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionMeasurementArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionMeasurementArray) ProtoMessage() {}

func (x *PositionMeasurementArray) ProtoReflect() protoreflect.Message {
	mi := &file_people_msgs_PositionMeasurementArray_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionMeasurementArray.ProtoReflect.Descriptor instead.
func (*PositionMeasurementArray) Descriptor() ([]byte, []int) {
	return file_people_msgs_PositionMeasurementArray_proto_rawDescGZIP(), []int{0}
}

func (x *PositionMeasurementArray) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PositionMeasurementArray) GetPeople() []*PositionMeasurement {
	if x != nil {
		return x.People
	}
	return nil
}

func (x *PositionMeasurementArray) GetCooccurrence() []float32 {
	if x != nil {
		return x.Cooccurrence
	}
	return nil
}

var File_people_msgs_PositionMeasurementArray_proto protoreflect.FileDescriptor

var file_people_msgs_PositionMeasurementArray_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x65,
	0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x25, 0x70, 0x65, 0x6f, 0x70, 0x6c,
	0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x18, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x38,
	0x0a, 0x06, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x06, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6f, 0x63,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0c,
	0x43, 0x6f, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f,
	0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_people_msgs_PositionMeasurementArray_proto_rawDescOnce sync.Once
	file_people_msgs_PositionMeasurementArray_proto_rawDescData = file_people_msgs_PositionMeasurementArray_proto_rawDesc
)

func file_people_msgs_PositionMeasurementArray_proto_rawDescGZIP() []byte {
	file_people_msgs_PositionMeasurementArray_proto_rawDescOnce.Do(func() {
		file_people_msgs_PositionMeasurementArray_proto_rawDescData = protoimpl.X.CompressGZIP(file_people_msgs_PositionMeasurementArray_proto_rawDescData)
	})
	return file_people_msgs_PositionMeasurementArray_proto_rawDescData
}

var file_people_msgs_PositionMeasurementArray_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_people_msgs_PositionMeasurementArray_proto_goTypes = []any{
	(*PositionMeasurementArray)(nil), // 0: people_msgs.PositionMeasurementArray
	(*std_msgs.Header)(nil),          // 1: std_msgs.Header
	(*PositionMeasurement)(nil),      // 2: people_msgs.PositionMeasurement
}
var file_people_msgs_PositionMeasurementArray_proto_depIdxs = []int32{
	1, // 0: people_msgs.PositionMeasurementArray.Header:type_name -> std_msgs.Header
	2, // 1: people_msgs.PositionMeasurementArray.People:type_name -> people_msgs.PositionMeasurement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_people_msgs_PositionMeasurementArray_proto_init() }
func file_people_msgs_PositionMeasurementArray_proto_init() {
	if File_people_msgs_PositionMeasurementArray_proto != nil {
		return
	}
	file_people_msgs_PositionMeasurement_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_people_msgs_PositionMeasurementArray_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_people_msgs_PositionMeasurementArray_proto_goTypes,
		DependencyIndexes: file_people_msgs_PositionMeasurementArray_proto_depIdxs,
		MessageInfos:      file_people_msgs_PositionMeasurementArray_proto_msgTypes,
	}.Build()
	File_people_msgs_PositionMeasurementArray_proto = out.File
	file_people_msgs_PositionMeasurementArray_proto_rawDesc = nil
	file_people_msgs_PositionMeasurementArray_proto_goTypes = nil
	file_people_msgs_PositionMeasurementArray_proto_depIdxs = nil
}
