//autogenerated:yes
//nolint:revive,lll
package actionlib_tutorials

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type AveragingResult struct {
    msg.Package `ros:"actionlib_tutorials"`
    Mean float32
    StdDev float32
}

