//autogenerated:yes
//nolint:revive,lll
package actionlib_tutorials

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type FibonacciAction struct {
    msg.Package `ros:"actionlib_tutorials"`
    ActionGoal FibonacciActionGoal
    ActionResult FibonacciActionResult
    ActionFeedback FibonacciActionFeedback
}

