//autogenerated:yes
//nolint:revive,lll
package actionlib_tutorials

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type AveragingAction struct {
    msg.Package `ros:"actionlib_tutorials"`
    ActionGoal AveragingActionGoal
    ActionResult AveragingActionResult
    ActionFeedback AveragingActionFeedback
}

