// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: geographic_msgs/RouteSegment.proto

package geographic_msgs

import (
	uuid_msgs "go_agent/telemetry/genproto/ros/uuid_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteSegment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *uuid_msgs.UniqueID `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Start *uuid_msgs.UniqueID `protobuf:"bytes,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End   *uuid_msgs.UniqueID `protobuf:"bytes,3,opt,name=End,proto3" json:"End,omitempty"`
	Props []*KeyValue         `protobuf:"bytes,4,rep,name=Props,proto3" json:"Props,omitempty"`
}

func (x *RouteSegment) Reset() {
	*x = RouteSegment{}
	mi := &file_geographic_msgs_RouteSegment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSegment) ProtoMessage() {}

func (x *RouteSegment) ProtoReflect() protoreflect.Message {
	mi := &file_geographic_msgs_RouteSegment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSegment.ProtoReflect.Descriptor instead.
func (*RouteSegment) Descriptor() ([]byte, []int) {
	return file_geographic_msgs_RouteSegment_proto_rawDescGZIP(), []int{0}
}

func (x *RouteSegment) GetId() *uuid_msgs.UniqueID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RouteSegment) GetStart() *uuid_msgs.UniqueID {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RouteSegment) GetEnd() *uuid_msgs.UniqueID {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *RouteSegment) GetProps() []*KeyValue {
	if x != nil {
		return x.Props
	}
	return nil
}

var File_geographic_msgs_RouteSegment_proto protoreflect.FileDescriptor

var file_geographic_msgs_RouteSegment_proto_rawDesc = []byte{
	0x0a, 0x22, 0x67, 0x65, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x2f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x65, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x63,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x1e, 0x67, 0x65, 0x6f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69,
	0x63, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x75, 0x75, 0x69, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73,
	0x2f, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb6, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x23, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75,
	0x75, 0x69, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49,
	0x44, 0x52, 0x02, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73,
	0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x44, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x25, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x75, 0x75, 0x69, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x49, 0x44, 0x52, 0x03, 0x45, 0x6e, 0x64, 0x12, 0x2f, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x70, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x65, 0x6f, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x69, 0x63, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x6f, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x67, 0x65, 0x6f, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x69, 0x63, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_geographic_msgs_RouteSegment_proto_rawDescOnce sync.Once
	file_geographic_msgs_RouteSegment_proto_rawDescData = file_geographic_msgs_RouteSegment_proto_rawDesc
)

func file_geographic_msgs_RouteSegment_proto_rawDescGZIP() []byte {
	file_geographic_msgs_RouteSegment_proto_rawDescOnce.Do(func() {
		file_geographic_msgs_RouteSegment_proto_rawDescData = protoimpl.X.CompressGZIP(file_geographic_msgs_RouteSegment_proto_rawDescData)
	})
	return file_geographic_msgs_RouteSegment_proto_rawDescData
}

var file_geographic_msgs_RouteSegment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_geographic_msgs_RouteSegment_proto_goTypes = []any{
	(*RouteSegment)(nil),       // 0: geographic_msgs.RouteSegment
	(*uuid_msgs.UniqueID)(nil), // 1: uuid_msgs.UniqueID
	(*KeyValue)(nil),           // 2: geographic_msgs.KeyValue
}
var file_geographic_msgs_RouteSegment_proto_depIdxs = []int32{
	1, // 0: geographic_msgs.RouteSegment.Id:type_name -> uuid_msgs.UniqueID
	1, // 1: geographic_msgs.RouteSegment.Start:type_name -> uuid_msgs.UniqueID
	1, // 2: geographic_msgs.RouteSegment.End:type_name -> uuid_msgs.UniqueID
	2, // 3: geographic_msgs.RouteSegment.Props:type_name -> geographic_msgs.KeyValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_geographic_msgs_RouteSegment_proto_init() }
func file_geographic_msgs_RouteSegment_proto_init() {
	if File_geographic_msgs_RouteSegment_proto != nil {
		return
	}
	file_geographic_msgs_KeyValue_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geographic_msgs_RouteSegment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geographic_msgs_RouteSegment_proto_goTypes,
		DependencyIndexes: file_geographic_msgs_RouteSegment_proto_depIdxs,
		MessageInfos:      file_geographic_msgs_RouteSegment_proto_msgTypes,
	}.Build()
	File_geographic_msgs_RouteSegment_proto = out.File
	file_geographic_msgs_RouteSegment_proto_rawDesc = nil
	file_geographic_msgs_RouteSegment_proto_goTypes = nil
	file_geographic_msgs_RouteSegment_proto_depIdxs = nil
}
