//autogenerated:yes
//nolint:revive,lll
package rospy_tutorials

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Floats struct {
    msg.Package `ros:"rospy_tutorials"`
    Data []float32
}

