//autogenerated:yes
//nolint:revive,lll
package rospy_tutorials

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type HeaderString struct {
    msg.Package `ros:"rospy_tutorials"`
    Header std_msgs.Header
    Data string
}

