// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: theora_image_transport/Packet.proto

package theora_image_transport

import (
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     *std_msgs.Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Data       []uint32         `protobuf:"varint,2,rep,packed,name=Data,proto3" json:"Data,omitempty"`
	BOS        int32            `protobuf:"varint,3,opt,name=BOS,proto3" json:"BOS,omitempty"`
	EOS        int32            `protobuf:"varint,4,opt,name=EOS,proto3" json:"EOS,omitempty"`
	Granulepos int64            `protobuf:"varint,5,opt,name=Granulepos,proto3" json:"Granulepos,omitempty"`
	Packetno   int64            `protobuf:"varint,6,opt,name=Packetno,proto3" json:"Packetno,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_theora_image_transport_Packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_theora_image_transport_Packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_theora_image_transport_Packet_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Packet) GetData() []uint32 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Packet) GetBOS() int32 {
	if x != nil {
		return x.BOS
	}
	return 0
}

func (x *Packet) GetEOS() int32 {
	if x != nil {
		return x.EOS
	}
	return 0
}

func (x *Packet) GetGranulepos() int64 {
	if x != nil {
		return x.Granulepos
	}
	return 0
}

func (x *Packet) GetPacketno() int64 {
	if x != nil {
		return x.Packetno
	}
	return 0
}

var File_theora_image_transport_Packet_proto protoreflect.FileDescriptor

var file_theora_image_transport_Packet_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x68, 0x65, 0x6f, 0x72, 0x61, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x74, 0x68, 0x65, 0x6f, 0x72, 0x61, 0x5f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x15, 0x73,
	0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a,
	0x03, 0x42, 0x4f, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x42, 0x4f, 0x53, 0x12,
	0x10, 0x0a, 0x03, 0x45, 0x4f, 0x53, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x45, 0x4f,
	0x53, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x65, 0x70, 0x6f, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x65, 0x70, 0x6f,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x6e, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x6e, 0x6f, 0x42, 0x38, 0x5a,
	0x36, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73,
	0x2f, 0x74, 0x68, 0x65, 0x6f, 0x72, 0x61, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_theora_image_transport_Packet_proto_rawDescOnce sync.Once
	file_theora_image_transport_Packet_proto_rawDescData = file_theora_image_transport_Packet_proto_rawDesc
)

func file_theora_image_transport_Packet_proto_rawDescGZIP() []byte {
	file_theora_image_transport_Packet_proto_rawDescOnce.Do(func() {
		file_theora_image_transport_Packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_theora_image_transport_Packet_proto_rawDescData)
	})
	return file_theora_image_transport_Packet_proto_rawDescData
}

var file_theora_image_transport_Packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_theora_image_transport_Packet_proto_goTypes = []any{
	(*Packet)(nil),          // 0: theora_image_transport.Packet
	(*std_msgs.Header)(nil), // 1: std_msgs.Header
}
var file_theora_image_transport_Packet_proto_depIdxs = []int32{
	1, // 0: theora_image_transport.Packet.Header:type_name -> std_msgs.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_theora_image_transport_Packet_proto_init() }
func file_theora_image_transport_Packet_proto_init() {
	if File_theora_image_transport_Packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_theora_image_transport_Packet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_theora_image_transport_Packet_proto_goTypes,
		DependencyIndexes: file_theora_image_transport_Packet_proto_depIdxs,
		MessageInfos:      file_theora_image_transport_Packet_proto_msgTypes,
	}.Build()
	File_theora_image_transport_Packet_proto = out.File
	file_theora_image_transport_Packet_proto_rawDesc = nil
	file_theora_image_transport_Packet_proto_goTypes = nil
	file_theora_image_transport_Packet_proto_depIdxs = nil
}
