//autogenerated:yes
//nolint:revive,lll
package theora_image_transport

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Packet struct {
    msg.Package `ros:"theora_image_transport"`
    Header std_msgs.Header
    Data []uint8
    BOS int32
    EOS int32
    Granulepos int64
    Packetno int64
}

