//autogenerated:yes
//nolint:revive,lll
package actionlib_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type GoalID struct {
    msg.Package `ros:"actionlib_msgs"`
    Stamp time.Time
    Id string
}

