//autogenerated:yes
//nolint:revive,lll
package turtle_actionlib

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ShapeResult struct {
    msg.Package `ros:"turtle_actionlib"`
    InteriorAngle float32
    Apothem float32
}

