//autogenerated:yes
//nolint:revive,lll
package turtle_actionlib

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ShapeAction struct {
    msg.Package `ros:"turtle_actionlib"`
    ActionGoal ShapeActionGoal
    ActionResult ShapeActionResult
    ActionFeedback ShapeActionFeedback
}

