// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: ar_track_alvar_msgs/AlvarMarker.proto

package ar_track_alvar_msgs

import (
	geometry_msgs "go_agent/telemetry/genproto/ros/geometry_msgs"
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlvarMarker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     *std_msgs.Header           `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Id         uint32                     `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Confidence uint32                     `protobuf:"varint,3,opt,name=Confidence,proto3" json:"Confidence,omitempty"`
	Pose       *geometry_msgs.PoseStamped `protobuf:"bytes,4,opt,name=Pose,proto3" json:"Pose,omitempty"`
}

func (x *AlvarMarker) Reset() {
	*x = AlvarMarker{}
	mi := &file_ar_track_alvar_msgs_AlvarMarker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlvarMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlvarMarker) ProtoMessage() {}

func (x *AlvarMarker) ProtoReflect() protoreflect.Message {
	mi := &file_ar_track_alvar_msgs_AlvarMarker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlvarMarker.ProtoReflect.Descriptor instead.
func (*AlvarMarker) Descriptor() ([]byte, []int) {
	return file_ar_track_alvar_msgs_AlvarMarker_proto_rawDescGZIP(), []int{0}
}

func (x *AlvarMarker) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AlvarMarker) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AlvarMarker) GetConfidence() uint32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AlvarMarker) GetPose() *geometry_msgs.PoseStamped {
	if x != nil {
		return x.Pose
	}
	return nil
}

var File_ar_track_alvar_msgs_AlvarMarker_proto protoreflect.FileDescriptor

var file_ar_track_alvar_msgs_AlvarMarker_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x6c, 0x76, 0x61, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x41, 0x6c, 0x76, 0x61, 0x72, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x5f, 0x61, 0x6c, 0x76, 0x61, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x1f, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x50, 0x6f, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73,
	0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x41, 0x6c, 0x76, 0x61, 0x72, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2e,
	0x0a, 0x04, 0x50, 0x6f, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x65, 0x64, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x65, 0x42, 0x35,
	0x5a, 0x33, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f,
	0x73, 0x2f, 0x61, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x61, 0x6c, 0x76, 0x61, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ar_track_alvar_msgs_AlvarMarker_proto_rawDescOnce sync.Once
	file_ar_track_alvar_msgs_AlvarMarker_proto_rawDescData = file_ar_track_alvar_msgs_AlvarMarker_proto_rawDesc
)

func file_ar_track_alvar_msgs_AlvarMarker_proto_rawDescGZIP() []byte {
	file_ar_track_alvar_msgs_AlvarMarker_proto_rawDescOnce.Do(func() {
		file_ar_track_alvar_msgs_AlvarMarker_proto_rawDescData = protoimpl.X.CompressGZIP(file_ar_track_alvar_msgs_AlvarMarker_proto_rawDescData)
	})
	return file_ar_track_alvar_msgs_AlvarMarker_proto_rawDescData
}

var file_ar_track_alvar_msgs_AlvarMarker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ar_track_alvar_msgs_AlvarMarker_proto_goTypes = []any{
	(*AlvarMarker)(nil),               // 0: ar_track_alvar_msgs.AlvarMarker
	(*std_msgs.Header)(nil),           // 1: std_msgs.Header
	(*geometry_msgs.PoseStamped)(nil), // 2: geometry_msgs.PoseStamped
}
var file_ar_track_alvar_msgs_AlvarMarker_proto_depIdxs = []int32{
	1, // 0: ar_track_alvar_msgs.AlvarMarker.Header:type_name -> std_msgs.Header
	2, // 1: ar_track_alvar_msgs.AlvarMarker.Pose:type_name -> geometry_msgs.PoseStamped
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ar_track_alvar_msgs_AlvarMarker_proto_init() }
func file_ar_track_alvar_msgs_AlvarMarker_proto_init() {
	if File_ar_track_alvar_msgs_AlvarMarker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ar_track_alvar_msgs_AlvarMarker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ar_track_alvar_msgs_AlvarMarker_proto_goTypes,
		DependencyIndexes: file_ar_track_alvar_msgs_AlvarMarker_proto_depIdxs,
		MessageInfos:      file_ar_track_alvar_msgs_AlvarMarker_proto_msgTypes,
	}.Build()
	File_ar_track_alvar_msgs_AlvarMarker_proto = out.File
	file_ar_track_alvar_msgs_AlvarMarker_proto_rawDesc = nil
	file_ar_track_alvar_msgs_AlvarMarker_proto_goTypes = nil
	file_ar_track_alvar_msgs_AlvarMarker_proto_depIdxs = nil
}
