// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: turtle_actionlib/ShapeFeedback.proto

package turtle_actionlib

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShapeFeedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShapeFeedback) Reset() {
	*x = ShapeFeedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_turtle_actionlib_ShapeFeedback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShapeFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeFeedback) ProtoMessage() {}

func (x *ShapeFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_turtle_actionlib_ShapeFeedback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeFeedback.ProtoReflect.Descriptor instead.
func (*ShapeFeedback) Descriptor() ([]byte, []int) {
	return file_turtle_actionlib_ShapeFeedback_proto_rawDescGZIP(), []int{0}
}

var File_turtle_actionlib_ShapeFeedback_proto protoreflect.FileDescriptor

var file_turtle_actionlib_ShapeFeedback_proto_rawDesc = []byte{
	0x0a, 0x24, 0x74, 0x75, 0x72, 0x74, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x6c,
	0x69, 0x62, 0x2f, 0x53, 0x68, 0x61, 0x70, 0x65, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x75, 0x72, 0x74, 0x6c, 0x65, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x6c, 0x69, 0x62, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x70,
	0x65, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x6f, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x74, 0x75, 0x72,
	0x74, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x6c, 0x69, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_turtle_actionlib_ShapeFeedback_proto_rawDescOnce sync.Once
	file_turtle_actionlib_ShapeFeedback_proto_rawDescData = file_turtle_actionlib_ShapeFeedback_proto_rawDesc
)

func file_turtle_actionlib_ShapeFeedback_proto_rawDescGZIP() []byte {
	file_turtle_actionlib_ShapeFeedback_proto_rawDescOnce.Do(func() {
		file_turtle_actionlib_ShapeFeedback_proto_rawDescData = protoimpl.X.CompressGZIP(file_turtle_actionlib_ShapeFeedback_proto_rawDescData)
	})
	return file_turtle_actionlib_ShapeFeedback_proto_rawDescData
}

var file_turtle_actionlib_ShapeFeedback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turtle_actionlib_ShapeFeedback_proto_goTypes = []any{
	(*ShapeFeedback)(nil), // 0: turtle_actionlib.ShapeFeedback
}
var file_turtle_actionlib_ShapeFeedback_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turtle_actionlib_ShapeFeedback_proto_init() }
func file_turtle_actionlib_ShapeFeedback_proto_init() {
	if File_turtle_actionlib_ShapeFeedback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_turtle_actionlib_ShapeFeedback_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ShapeFeedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_turtle_actionlib_ShapeFeedback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turtle_actionlib_ShapeFeedback_proto_goTypes,
		DependencyIndexes: file_turtle_actionlib_ShapeFeedback_proto_depIdxs,
		MessageInfos:      file_turtle_actionlib_ShapeFeedback_proto_msgTypes,
	}.Build()
	File_turtle_actionlib_ShapeFeedback_proto = out.File
	file_turtle_actionlib_ShapeFeedback_proto_rawDesc = nil
	file_turtle_actionlib_ShapeFeedback_proto_goTypes = nil
	file_turtle_actionlib_ShapeFeedback_proto_depIdxs = nil
}
