//autogenerated:yes
//nolint:revive,lll
package object_recognition_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
    "go_agent/telemetry/gengo/ros/shape_msgs"
)


type ObjectInformation struct {
    msg.Package `ros:"object_recognition_msgs"`
    Name string
    GroundTruthMesh shape_msgs.Mesh
    GroundTruthPointCloud sensor_msgs.PointCloud2
}

