//autogenerated:yes
//nolint:revive,lll
package object_recognition_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ObjectRecognitionAction struct {
    msg.Package `ros:"object_recognition_msgs"`
    ActionGoal ObjectRecognitionActionGoal
    ActionResult ObjectRecognitionActionResult
    ActionFeedback ObjectRecognitionActionFeedback
}

