//autogenerated:yes
//nolint:revive,lll
package object_recognition_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ObjectRecognitionResult struct {
    msg.Package `ros:"object_recognition_msgs"`
    RecognizedObjects RecognizedObjectArray
}

