//autogenerated:yes
//nolint:revive,lll
package object_recognition_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Table struct {
    msg.Package `ros:"object_recognition_msgs"`
    Header std_msgs.Header
    Pose geometry_msgs.Pose
    ConvexHull []geometry_msgs.Point
}

