//autogenerated:yes
//nolint:revive,lll
package object_recognition_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ObjectRecognitionGoal struct {
    msg.Package `ros:"object_recognition_msgs"`
    UseRoi bool
    FilterLimits []float32
}

