//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocResultPortHeaderMsg struct {
    msg.Package `ros:"sick_scan"`
    Magicword uint32
    Length uint32
    Payloadtype uint16
    Payloadversion uint16
    Ordernumber uint32
    Serialnumber uint32
    FwVersion []uint8
    Telegramcounter uint32
    Systemtime uint64
}

