//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type SickLocResultPortTestcaseMsg struct {
    msg.Package `ros:"sick_scan"`
    Header std_msgs.Header
    BinaryData []uint8
    TelegramMsg SickLocResultPortTelegramMsg
}

