//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type ImuExtended struct {
    msg.Package `ros:"sick_scan"`
    Header std_msgs.Header
    Imu sensor_msgs.Imu`rosname:"Imu"`
    Ticks uint32
    QuaternionAccuracy float32
    AngularVelocityReliability uint8
    LinearAccelerationReliability uint8
}

