//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type RadarPreHeaderMeasurementParam1Block struct {
    msg.Package `ros:"sick_scan"`
    UiCycleDuration uint32`rosname:"uiCycleDuration"`
    UiNoiseLevel uint32`rosname:"uiNoiseLevel"`
}

