//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocResultPortPayloadMsg struct {
    msg.Package `ros:"sick_scan"`
    Errorcode uint16
    Scancounter uint32
    Timestamp uint32
    Posex int32
    Posey int32
    Poseyaw int32
    Reserved1 uint32
    Reserved2 int32
    Quality uint8
    Outliersratio uint8
    Covariancex int32
    Covariancey int32
    Covarianceyaw int32
    Reserved3 uint64
}

