//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type LFErecFieldMsg struct {
    msg.Package `ros:"sick_scan"`
    VersionNumber uint16
    FieldIndex uint8
    SysCount uint32
    DistScaleFactor float32
    DistScaleOffset float32
    AngleScaleFactor uint32
    AngleScaleOffset int32
    FieldResultMrs uint8
    TimeState uint16
    Year uint16
    Month uint8
    Day uint8
    Hour uint8
    Minute uint8
    Second uint8
    Microsecond uint32
}

