//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type RadarScan struct {
    msg.Package `ros:"sick_scan"`
    Header std_msgs.Header
    RadarPreHeader RadarPreHeader`rosname:"radarPreHeader"`
    Targets sensor_msgs.PointCloud2
    Objects []RadarObject
}

