//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "time"
)


type RadarObject struct {
    msg.Package `ros:"sick_scan"`
    Id int32
    TrackingTime time.Time
    LastSeen time.Time
    Velocity geometry_msgs.TwistWithCovariance
    BoundingBoxCenter geometry_msgs.Pose
    BoundingBoxSize geometry_msgs.Vector3
    ObjectBoxCenter geometry_msgs.PoseWithCovariance
    ObjectBoxSize geometry_msgs.Vector3
    ContourPoints []geometry_msgs.Point
}

