//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type RadarPreHeader struct {
    msg.Package `ros:"sick_scan"`
    UiVersionNo uint16`rosname:"uiVersionNo"`
    RadarPreHeaderDeviceBlock RadarPreHeaderDeviceBlock`rosname:"radarPreHeaderDeviceBlock"`
    RadarPreHeaderStatusBlock RadarPreHeaderStatusBlock`rosname:"radarPreHeaderStatusBlock"`
    RadarPreHeaderMeasurementParam1Block RadarPreHeaderMeasurementParam1Block`rosname:"radarPreHeaderMeasurementParam1Block"`
    RadarPreHeaderArrayEncoderBlock []RadarPreHeaderEncoderBlock`rosname:"radarPreHeaderArrayEncoderBlock"`
}

