//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocResultPortCrcMsg struct {
    msg.Package `ros:"sick_scan"`
    Checksum uint16
}

