//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocSetResultPoseIntervalSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Interval int32
}



type SickLocSetResultPoseIntervalSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocSetResultPoseIntervalSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocSetResultPoseIntervalSrvReq
    SickLocSetResultPoseIntervalSrvRes
}
