//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocMapStateSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocMapStateSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Mapstate bool
    Success bool
}

type SickLocMapStateSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocMapStateSrvReq
    SickLocMapStateSrvRes
}
