//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocSetResultModeSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Mode int32
}



type SickLocSetResultModeSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocSetResultModeSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocSetResultModeSrvReq
    SickLocSetResultModeSrvRes
}
