//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocStartDemoMappingSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocStartDemoMappingSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocStartDemoMappingSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocStartDemoMappingSrvReq
    SickLocStartDemoMappingSrvRes
}
