//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocResultEndiannessSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocResultEndiannessSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Endianness int32
    Success bool
}

type SickLocResultEndiannessSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocResultEndiannessSrvReq
    SickLocResultEndiannessSrvRes
}
