//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocSetOdometryRestrictYMotionSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Active bool
}



type SickLocSetOdometryRestrictYMotionSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocSetOdometryRestrictYMotionSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocSetOdometryRestrictYMotionSrvReq
    SickLocSetOdometryRestrictYMotionSrvRes
}
