//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ColaMsgSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Request string
}



type ColaMsgSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Response string
}

type ColaMsgSrv struct {
    msg.Package `ros:"sick_scan"`
    ColaMsgSrvReq
    ColaMsgSrvRes
}
