//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickReportUserMessageSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Usermessage string
}



type SickReportUserMessageSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickReportUserMessageSrv struct {
    msg.Package `ros:"sick_scan"`
    SickReportUserMessageSrvReq
    SickReportUserMessageSrvRes
}
