//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocReflectorsForSupportActiveSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocReflectorsForSupportActiveSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Active bool
    Success bool
}

type SickLocReflectorsForSupportActiveSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocReflectorsForSupportActiveSrvReq
    SickLocReflectorsForSupportActiveSrvRes
}
