//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocSetResultPoseEnabledSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Enabled int32
}



type SickLocSetResultPoseEnabledSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocSetResultPoseEnabledSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocSetResultPoseEnabledSrvReq
    SickLocSetResultPoseEnabledSrvRes
}
