//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocAutoStartSavePoseSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocAutoStartSavePoseSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocAutoStartSavePoseSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocAutoStartSavePoseSrvReq
    SickLocAutoStartSavePoseSrvRes
}
