//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocSetOdometryActiveSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Active bool
}



type SickLocSetOdometryActiveSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Set bool
    Executed bool
}

type SickLocSetOdometryActiveSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocSetOdometryActiveSrvReq
    SickLocSetOdometryActiveSrvRes
}
