//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocResultPortSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocResultPortSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Port int32
    Success bool
}

type SickLocResultPortSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocResultPortSrvReq
    SickLocResultPortSrvRes
}
