//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickDevSetIMUActiveSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Active bool
}



type SickDevSetIMUActiveSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickDevSetIMUActiveSrv struct {
    msg.Package `ros:"sick_scan"`
    SickDevSetIMUActiveSrvReq
    SickDevSetIMUActiveSrvRes
}
