//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocTimeSyncSrvReq struct {
    msg.Package `ros:"sick_scan"`
    TimestampLidarMs uint32
}



type SickLocTimeSyncSrvRes struct {
    msg.Package `ros:"sick_scan"`
    VehicleTimeValid bool
    VehicleTimeSec uint32
    VehicleTimeNsec uint32
}

type SickLocTimeSyncSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocTimeSyncSrvReq
    SickLocTimeSyncSrvRes
}
