//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickDevIMUActiveSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickDevIMUActiveSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Active bool
    Success bool
}

type SickDevIMUActiveSrv struct {
    msg.Package `ros:"sick_scan"`
    SickDevIMUActiveSrvReq
    SickDevIMUActiveSrvRes
}
