//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocStateSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocStateSrvRes struct {
    msg.Package `ros:"sick_scan"`
    State int32
    Success bool
}

type SickLocStateSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocStateSrvReq
    SickLocStateSrvRes
}
