//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocInitializePoseSrvReq struct {
    msg.Package `ros:"sick_scan"`
    X int32
    Y int32
    Yaw int32
    Sigmatranslation uint32
}



type SickLocInitializePoseSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocInitializePoseSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocInitializePoseSrvReq
    SickLocInitializePoseSrvRes
}
