//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickDevGetLidarIdentSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Index uint32
}



type SickDevGetLidarIdentSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Scannerident string
    Success bool
}

type SickDevGetLidarIdentSrv struct {
    msg.Package `ros:"sick_scan"`
    SickDevGetLidarIdentSrvReq
    SickDevGetLidarIdentSrvRes
}
