//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickDevSetLidarConfigSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Index uint32
    Minrange uint32
    Maxrange uint32
    Minangle int32
    Maxangle int32
    X int32
    Y int32
    Yaw int32
    Upsidedown bool
    Ip string
    Port uint32
    Interfacetype int32
    Maplayer uint32
    Active bool
}



type SickDevSetLidarConfigSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Set bool
    Executed bool
}

type SickDevSetLidarConfigSrv struct {
    msg.Package `ros:"sick_scan"`
    SickDevSetLidarConfigSrvReq
    SickDevSetLidarConfigSrvRes
}
