//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocRequestResultDataSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocRequestResultDataSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocRequestResultDataSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocRequestResultDataSrvReq
    SickLocRequestResultDataSrvRes
}
