//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocOdometryPortSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocOdometryPortSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Port uint32
    Success bool
}

type SickLocOdometryPortSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocOdometryPortSrvReq
    SickLocOdometryPortSrvRes
}
