//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocSetAutoStartSavePoseIntervalSrvReq struct {
    msg.Package `ros:"sick_scan"`
    Interval uint32
}



type SickLocSetAutoStartSavePoseIntervalSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Success bool
}

type SickLocSetAutoStartSavePoseIntervalSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocSetAutoStartSavePoseIntervalSrvReq
    SickLocSetAutoStartSavePoseIntervalSrvRes
}
