//autogenerated:yes
//nolint:revive,lll
package sick_scan

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SickLocOdometryRestrictYMotionSrvReq struct {
    msg.Package `ros:"sick_scan"`
}



type SickLocOdometryRestrictYMotionSrvRes struct {
    msg.Package `ros:"sick_scan"`
    Active bool
    Success bool
}

type SickLocOdometryRestrictYMotionSrv struct {
    msg.Package `ros:"sick_scan"`
    SickLocOdometryRestrictYMotionSrvReq
    SickLocOdometryRestrictYMotionSrvRes
}
