//autogenerated:yes
//nolint:revive,lll
package actionlib

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type TwoIntsGoal struct {
    msg.Package `ros:"actionlib"`
    A int64
    B int64
}

