//autogenerated:yes
//nolint:revive,lll
package actionlib

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type TestRequestResult struct {
    msg.Package `ros:"actionlib"`
    TheResult int32
    IsSimpleServer bool
}

