//autogenerated:yes
//nolint:revive,lll
package actionlib

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/actionlib_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type TestRequestActionFeedback struct {
    msg.Package `ros:"actionlib"`
    Header std_msgs.Header
    Status actionlib_msgs.GoalStatus
    Feedback TestRequestFeedback
}

