//autogenerated:yes
//nolint:revive,lll
package actionlib

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type TwoIntsAction struct {
    msg.Package `ros:"actionlib"`
    ActionGoal TwoIntsActionGoal
    ActionResult TwoIntsActionResult
    ActionFeedback TwoIntsActionFeedback
}

