//autogenerated:yes
//nolint:revive,lll
package rosserial_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


const (
    TopicInfo_ID_PUBLISHER uint16 = 0
    TopicInfo_ID_SUBSCRIBER uint16 = 1
    TopicInfo_ID_SERVICE_SERVER uint16 = 2
    TopicInfo_ID_SERVICE_CLIENT uint16 = 4
    TopicInfo_ID_PARAMETER_REQUEST uint16 = 6
    TopicInfo_ID_LOG uint16 = 7
    TopicInfo_ID_TIME uint16 = 10
    TopicInfo_ID_TX_STOP uint16 = 11
)

type TopicInfo struct {
    msg.Package `ros:"rosserial_msgs"`
    msg.Definitions `ros:"uint16 ID_PUBLISHER=0,uint16 ID_SUBSCRIBER=1,uint16 ID_SERVICE_SERVER=2,uint16 ID_SERVICE_CLIENT=4,uint16 ID_PARAMETER_REQUEST=6,uint16 ID_LOG=7,uint16 ID_TIME=10,uint16 ID_TX_STOP=11"`
    TopicId uint16
    TopicName string
    MessageType string
    Md5sum string
    BufferSize int32
}

