//autogenerated:yes
//nolint:revive,lll
package rosserial_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type RequestParamReq struct {
    msg.Package `ros:"rosserial_msgs"`
    Name string
}



type RequestParamRes struct {
    msg.Package `ros:"rosserial_msgs"`
    Ints []int32
    Floats []float32
    Strings []string
}

type RequestParam struct {
    msg.Package `ros:"rosserial_msgs"`
    RequestParamReq
    RequestParamRes
}
