// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: tf2_msgs/TFMessage.proto

package tf2_msgs

import (
	geometry_msgs "go_agent/telemetry/genproto/ros/geometry_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TFMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transforms []*geometry_msgs.TransformStamped `protobuf:"bytes,1,rep,name=Transforms,proto3" json:"Transforms,omitempty"`
}

func (x *TFMessage) Reset() {
	*x = TFMessage{}
	mi := &file_tf2_msgs_TFMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFMessage) ProtoMessage() {}

func (x *TFMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tf2_msgs_TFMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFMessage.ProtoReflect.Descriptor instead.
func (*TFMessage) Descriptor() ([]byte, []int) {
	return file_tf2_msgs_TFMessage_proto_rawDescGZIP(), []int{0}
}

func (x *TFMessage) GetTransforms() []*geometry_msgs.TransformStamped {
	if x != nil {
		return x.Transforms
	}
	return nil
}

var File_tf2_msgs_TFMessage_proto protoreflect.FileDescriptor

var file_tf2_msgs_TFMessage_proto_rawDesc = []byte{
	0x0a, 0x18, 0x74, 0x66, 0x32, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x54, 0x46, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x66, 0x32, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x1a, 0x24, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x2f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x09, 0x54, 0x46,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x65, 0x64, 0x52, 0x0a, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x6f, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x74, 0x66, 0x32, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tf2_msgs_TFMessage_proto_rawDescOnce sync.Once
	file_tf2_msgs_TFMessage_proto_rawDescData = file_tf2_msgs_TFMessage_proto_rawDesc
)

func file_tf2_msgs_TFMessage_proto_rawDescGZIP() []byte {
	file_tf2_msgs_TFMessage_proto_rawDescOnce.Do(func() {
		file_tf2_msgs_TFMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_tf2_msgs_TFMessage_proto_rawDescData)
	})
	return file_tf2_msgs_TFMessage_proto_rawDescData
}

var file_tf2_msgs_TFMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tf2_msgs_TFMessage_proto_goTypes = []any{
	(*TFMessage)(nil),                      // 0: tf2_msgs.TFMessage
	(*geometry_msgs.TransformStamped)(nil), // 1: geometry_msgs.TransformStamped
}
var file_tf2_msgs_TFMessage_proto_depIdxs = []int32{
	1, // 0: tf2_msgs.TFMessage.Transforms:type_name -> geometry_msgs.TransformStamped
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tf2_msgs_TFMessage_proto_init() }
func file_tf2_msgs_TFMessage_proto_init() {
	if File_tf2_msgs_TFMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tf2_msgs_TFMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tf2_msgs_TFMessage_proto_goTypes,
		DependencyIndexes: file_tf2_msgs_TFMessage_proto_depIdxs,
		MessageInfos:      file_tf2_msgs_TFMessage_proto_msgTypes,
	}.Build()
	File_tf2_msgs_TFMessage_proto = out.File
	file_tf2_msgs_TFMessage_proto_rawDesc = nil
	file_tf2_msgs_TFMessage_proto_goTypes = nil
	file_tf2_msgs_TFMessage_proto_depIdxs = nil
}
