// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: opencv_apps/FlowArray.proto

package opencv_apps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flow []*Flow `protobuf:"bytes,1,rep,name=Flow,proto3" json:"Flow,omitempty"`
}

func (x *FlowArray) Reset() {
	*x = FlowArray{}
	mi := &file_opencv_apps_FlowArray_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowArray) ProtoMessage() {}

func (x *FlowArray) ProtoReflect() protoreflect.Message {
	mi := &file_opencv_apps_FlowArray_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowArray.ProtoReflect.Descriptor instead.
func (*FlowArray) Descriptor() ([]byte, []int) {
	return file_opencv_apps_FlowArray_proto_rawDescGZIP(), []int{0}
}

func (x *FlowArray) GetFlow() []*Flow {
	if x != nil {
		return x.Flow
	}
	return nil
}

var File_opencv_apps_FlowArray_proto protoreflect.FileDescriptor

var file_opencv_apps_FlowArray_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x76, 0x5f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x46, 0x6c,
	0x6f, 0x77, 0x41, 0x72, 0x72, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f,
	0x70, 0x65, 0x6e, 0x63, 0x76, 0x5f, 0x61, 0x70, 0x70, 0x73, 0x1a, 0x16, 0x6f, 0x70, 0x65, 0x6e,
	0x63, 0x76, 0x5f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x32, 0x0a, 0x09, 0x46, 0x6c, 0x6f, 0x77, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x25, 0x0a, 0x04, 0x46, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x63, 0x76, 0x5f, 0x61, 0x70, 0x70, 0x73, 0x2e, 0x46, 0x6c, 0x6f, 0x77,
	0x52, 0x04, 0x46, 0x6c, 0x6f, 0x77, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x76,
	0x5f, 0x61, 0x70, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_opencv_apps_FlowArray_proto_rawDescOnce sync.Once
	file_opencv_apps_FlowArray_proto_rawDescData = file_opencv_apps_FlowArray_proto_rawDesc
)

func file_opencv_apps_FlowArray_proto_rawDescGZIP() []byte {
	file_opencv_apps_FlowArray_proto_rawDescOnce.Do(func() {
		file_opencv_apps_FlowArray_proto_rawDescData = protoimpl.X.CompressGZIP(file_opencv_apps_FlowArray_proto_rawDescData)
	})
	return file_opencv_apps_FlowArray_proto_rawDescData
}

var file_opencv_apps_FlowArray_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_opencv_apps_FlowArray_proto_goTypes = []any{
	(*FlowArray)(nil), // 0: opencv_apps.FlowArray
	(*Flow)(nil),      // 1: opencv_apps.Flow
}
var file_opencv_apps_FlowArray_proto_depIdxs = []int32{
	1, // 0: opencv_apps.FlowArray.Flow:type_name -> opencv_apps.Flow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_opencv_apps_FlowArray_proto_init() }
func file_opencv_apps_FlowArray_proto_init() {
	if File_opencv_apps_FlowArray_proto != nil {
		return
	}
	file_opencv_apps_Flow_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opencv_apps_FlowArray_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opencv_apps_FlowArray_proto_goTypes,
		DependencyIndexes: file_opencv_apps_FlowArray_proto_depIdxs,
		MessageInfos:      file_opencv_apps_FlowArray_proto_msgTypes,
	}.Build()
	File_opencv_apps_FlowArray_proto = out.File
	file_opencv_apps_FlowArray_proto_rawDesc = nil
	file_opencv_apps_FlowArray_proto_goTypes = nil
	file_opencv_apps_FlowArray_proto_depIdxs = nil
}
