//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type SlidingWindowPoses struct {
    msg.Package `ros:"seven_robotics_msgs"`
    TargetPoses []geometry_msgs.PoseStamped
}

