//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type BLDCMotorState struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Timestamp time.Time
    Va float32
    Vb float32
    Vc float32
    Ia float32
    Ib float32
    Ic float32
    IdTarget float32`rosname:"idTarget"`
    IqTarget float32`rosname:"iqTarget"`
    IqErDt float32`rosname:"iqErDt"`
    Phase float32
    RpmMeasured float32
    RpmCommanded float32
    IAlpha float32`rosname:"iAlpha"`
    IBeta float32`rosname:"iBeta"`
    IAbs float32`rosname:"iAbs"`
    VAlpha float32`rosname:"vAlpha"`
    VBeta float32`rosname:"vBeta"`
    Id float32
    Iq float32
    Vd float32
    Vq float32
    Duty float32
    EncoderOffset float32
    SpeedRads float32`rosname:"speedRads"`
    MechanicalPhase float32`rosname:"mechanicalPhase"`
    MotorID uint8`rosname:"motorID"`
}

