//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type RebootSM struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Header std_msgs.Header
    RebootMotor bool`rosname:"rebootMotor"`
    RebootPC bool`rosname:"rebootPC"`
    RebootIMX6 bool`rosname:"rebootIMX6"`
    RebootUC bool`rosname:"rebootUC"`
    RebootLAN bool`rosname:"rebootLAN"`
    Rebootv24 bool
    RebootSICK bool`rosname:"rebootSICK"`
    RebootPowerExtension bool`rosname:"rebootPowerExtension"`
}

