//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type PIDStats struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Timestamp time.Time
    RightError float32`rosname:"rightError"`
    LeftError float32`rosname:"leftError"`
    RightIntegralError float32`rosname:"rightIntegralError"`
    LeftIntegralError float32`rosname:"leftIntegralError"`
    RightOutput float32`rosname:"rightOutput"`
    LeftOutput float32`rosname:"leftOutput"`
}

