//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type PowerManagement struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Header std_msgs.Header
    LaserEnable bool`rosname:"laserEnable"`
    LaserTime uint32`rosname:"laserTime"`
    LaserCycle uint8`rosname:"laserCycle"`
    KinectEnabled bool`rosname:"kinectEnabled"`
    KinectTime uint32`rosname:"kinectTime"`
    KinectCycle uint8`rosname:"kinectCycle"`
    MotorEnable bool`rosname:"motorEnable"`
    MotorTime uint32`rosname:"motorTime"`
    MotorCycle uint8`rosname:"motorCycle"`
    Stm32Enable bool`rosname:"stm32Enable"`
    Stm32Time uint32`rosname:"stm32Time"`
    Stm32Cycle uint8`rosname:"stm32Cycle"`
    Imx6Enable bool`rosname:"imx6Enable"`
    Imx6Time uint32`rosname:"imx6Time"`
    Imx6Cycle uint8`rosname:"imx6Cycle"`
    LanEnable bool`rosname:"lanEnable"`
    LanTime uint32`rosname:"lanTime"`
    LanCycle uint8`rosname:"lanCycle"`
    PcEnable bool`rosname:"pcEnable"`
    PcTime uint32`rosname:"pcTime"`
    PcCycle uint8`rosname:"pcCycle"`
}

