//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


const (
    MotorControlState_INIT uint8 = 0
    MotorControlState_CONTROL uint8 = 1
    MotorControlState_DRIVE uint8 = 2
    MotorControlState_FOC uint8 = 3
    MotorControlState_ALIGNMENT uint8 = 4
    MotorControlState_RPM uint8 = 5
    MotorControlState_FLASH_CHECK uint8 = 6
    MotorControlState_HALT uint8 = 7
    MotorControlState_ERROR uint8 = 8
    MotorControlState_CALIBRATE uint8 = 9
    MotorControlState_BRAKE uint8 = 10
)

type MotorControlState struct {
    msg.Package `ros:"seven_robotics_msgs"`
    msg.Definitions `ros:"uint8 INIT=0,uint8 CONTROL=1,uint8 DRIVE=2,uint8 FOC=3,uint8 ALIGNMENT=4,uint8 RPM=5,uint8 FLASH_CHECK=6,uint8 HALT=7,uint8 ERROR=8,uint8 CALIBRATE=9,uint8 BRAKE=10"`
    StateId uint8`rosname:"stateId"`
    StateName string`rosname:"stateName"`
}

