//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


const (
    BLDCState_INIT uint8 = 0
    BLDCState_BLDC_CONTROL uint8 = 1
    BLDCState_DRIVE uint8 = 2
    BLDCState_FOC uint8 = 3
    BLDCState_FLASH_CHECK uint8 = 4
    BLDCState_BLDC_HALT uint8 = 5
    BLDCState_ERROR uint8 = 6
    BLDCState_CALIBRATE uint8 = 7
)

type BLDCState struct {
    msg.Package `ros:"seven_robotics_msgs"`
    msg.Definitions `ros:"uint8 INIT=0,uint8 BLDC_CONTROL=1,uint8 DRIVE=2,uint8 FOC=3,uint8 FLASH_CHECK=4,uint8 BLDC_HALT=5,uint8 ERROR=6,uint8 CALIBRATE=7"`
    State uint8
    HaltState uint8`rosname:"haltState"`
}

