//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


const (
    Led_LED_SOLID_EFFECT uint8 = 0
    Led_LED_BREATHE_EFFECT uint8 = 1
    Led_LED_WAVE_EFFECT uint8 = 2
    Led_LED_RAINBOW_EFFECT uint8 = 3
    Led_LED_BLINK_EFFECT uint8 = 4
)

type Led struct {
    msg.Package `ros:"seven_robotics_msgs"`
    msg.Definitions `ros:"uint8 LED_SOLID_EFFECT=0,uint8 LED_BREATHE_EFFECT=1,uint8 LED_WAVE_EFFECT=2,uint8 LED_RAINBOW_EFFECT=3,uint8 LED_BLINK_EFFECT=4"`
    Header std_msgs.Header
    Colors std_msgs.ColorRGBA
    Effect uint8
}

