//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type PowerStatus struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Header std_msgs.Header
    MotorON bool`rosname:"motorON"`
    PcON bool`rosname:"pcON"`
    Imx6ON bool`rosname:"imx6ON"`
    UcON bool`rosname:"ucON"`
    LanON bool`rosname:"lanON"`
    KinectON bool`rosname:"kinectON"`
    SickON bool`rosname:"sickON"`
    AuxON bool`rosname:"auxON"`
}

