//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type LineSegment struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Radius float32
    Angle float32
    Covariance [4]float32
    Start [2]float32
    End [2]float32
}

