//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Battery struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Header std_msgs.Header
    Charging bool`rosname:"Charging"`
    CapacityDesigned uint32`rosname:"CapacityDesigned"`
    CapacityFull uint32`rosname:"CapacityFull"`
    NCells uint8`rosname:"nCells"`
    Volts float32`rosname:"Volts"`
    Amps float32`rosname:"Amps"`
    TempC float32`rosname:"TempC"`
    RemainingTime float32`rosname:"remainingTime"`
    RemainingCapacity float32`rosname:"remainingCapacity"`
    SOC float32`rosname:"SOC"`
    SOH float32`rosname:"SOH"`
}

