//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Brake struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Header std_msgs.Header
    Brake bool
}

