//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type MotorPlantFeedback struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Timestamp time.Time
    SetPointRight float32`rosname:"setPointRight"`
    SetPointLeft float32`rosname:"setPointLeft"`
    MeasuredSetPointRight float32`rosname:"measuredSetPointRight"`
    MeasuredSetPointLeft float32`rosname:"measuredSetPointLeft"`
    SetPointRPMRight int16`rosname:"setPointRPMRight"`
    SetPointRPMLeft int16`rosname:"setPointRPMLeft"`
    MeasuredRPMRight int16`rosname:"measuredRPMRight"`
    MeasuredRPMLeft int16`rosname:"measuredRPMLeft"`
}

