//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type MotorCurrent struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Timestamp time.Time
    RightMotorCurrent float32`rosname:"rightMotorCurrent"`
    LeftMotorCurrent float32`rosname:"leftMotorCurrent"`
}

