//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type Distance struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Timestamp time.Time
    ObjectId uint8
    Distance float64
}

