//autogenerated:yes
//nolint:revive,lll
package seven_robotics_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type ObstaclePose struct {
    msg.Package `ros:"seven_robotics_msgs"`
    Header std_msgs.Header
    ObjectId uint8
    Position geometry_msgs.Pose
}

