//autogenerated:yes
//nolint:revive,lll
package sensor_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Imu struct {
    msg.Package `ros:"sensor_msgs"`
    Header std_msgs.Header
    Orientation geometry_msgs.Quaternion
    OrientationCovariance [9]float64
    AngularVelocity geometry_msgs.Vector3
    AngularVelocityCovariance [9]float64
    LinearAcceleration geometry_msgs.Vector3
    LinearAccelerationCovariance [9]float64
}

