//autogenerated:yes
//nolint:revive,lll
package opencv_apps

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Rect struct {
    msg.Package `ros:"opencv_apps"`
    X float64
    Y float64
    Width float64
    Height float64
}

