//autogenerated:yes
//nolint:revive,lll
package opencv_apps

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type FlowStamped struct {
    msg.Package `ros:"opencv_apps"`
    Header std_msgs.Header
    Flow Flow
}

