//autogenerated:yes
//nolint:revive,lll
package opencv_apps

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ContourArray struct {
    msg.Package `ros:"opencv_apps"`
    Contours []Contour
}

