//autogenerated:yes
//nolint:revive,lll
package opencv_apps

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Moment struct {
    msg.Package `ros:"opencv_apps"`
    M00 float64
    M10 float64
    M01 float64
    M20 float64
    M11 float64
    M02 float64
    M30 float64
    M21 float64
    M12 float64
    M03 float64
    Mu20 float64
    Mu11 float64
    Mu02 float64
    Mu30 float64
    Mu21 float64
    Mu12 float64
    Mu03 float64
    Nu20 float64
    Nu11 float64
    Nu02 float64
    Nu30 float64
    Nu21 float64
    Nu12 float64
    Nu03 float64
    Center Point2D
    Length float64
    Area float64
}

