//autogenerated:yes
//nolint:revive,lll
package opencv_apps

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Flow struct {
    msg.Package `ros:"opencv_apps"`
    Point Point2D
    Velocity Point2D
}

