//autogenerated:yes
//nolint:revive,lll
package opencv_apps

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Circle struct {
    msg.Package `ros:"opencv_apps"`
    Center Point2D
    Radius float64
}

