//autogenerated:yes
//nolint:revive,lll
package plotjuggler_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type DataPoint struct {
    msg.Package `ros:"plotjuggler_msgs"`
    NameIndex uint16
    Stamp float64
    Value float64
}

