// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: nav_msgs/GridCells.proto

package nav_msgs

import (
	geometry_msgs "go_agent/telemetry/genproto/ros/geometry_msgs"
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GridCells struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     *std_msgs.Header       `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	CellWidth  float32                `protobuf:"fixed32,2,opt,name=CellWidth,proto3" json:"CellWidth,omitempty"`
	CellHeight float32                `protobuf:"fixed32,3,opt,name=CellHeight,proto3" json:"CellHeight,omitempty"`
	Cells      []*geometry_msgs.Point `protobuf:"bytes,4,rep,name=Cells,proto3" json:"Cells,omitempty"`
}

func (x *GridCells) Reset() {
	*x = GridCells{}
	mi := &file_nav_msgs_GridCells_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridCells) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridCells) ProtoMessage() {}

func (x *GridCells) ProtoReflect() protoreflect.Message {
	mi := &file_nav_msgs_GridCells_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridCells.ProtoReflect.Descriptor instead.
func (*GridCells) Descriptor() ([]byte, []int) {
	return file_nav_msgs_GridCells_proto_rawDescGZIP(), []int{0}
}

func (x *GridCells) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GridCells) GetCellWidth() float32 {
	if x != nil {
		return x.CellWidth
	}
	return 0
}

func (x *GridCells) GetCellHeight() float32 {
	if x != nil {
		return x.CellHeight
	}
	return 0
}

func (x *GridCells) GetCells() []*geometry_msgs.Point {
	if x != nil {
		return x.Cells
	}
	return nil
}

var File_nav_msgs_GridCells_proto protoreflect.FileDescriptor

var file_nav_msgs_GridCells_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x47, 0x72, 0x69, 0x64, 0x43,
	0x65, 0x6c, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x61, 0x76, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x1a, 0x19, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x2f, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x15, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x01, 0x0a, 0x09, 0x47, 0x72, 0x69, 0x64, 0x43,
	0x65, 0x6c, 0x6c, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x43, 0x65, 0x6c, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x43, 0x65, 0x6c, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x65, 0x6c, 0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x43, 0x65, 0x6c, 0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2a, 0x0a, 0x05,
	0x43, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x05, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x6f, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x6e, 0x61, 0x76, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nav_msgs_GridCells_proto_rawDescOnce sync.Once
	file_nav_msgs_GridCells_proto_rawDescData = file_nav_msgs_GridCells_proto_rawDesc
)

func file_nav_msgs_GridCells_proto_rawDescGZIP() []byte {
	file_nav_msgs_GridCells_proto_rawDescOnce.Do(func() {
		file_nav_msgs_GridCells_proto_rawDescData = protoimpl.X.CompressGZIP(file_nav_msgs_GridCells_proto_rawDescData)
	})
	return file_nav_msgs_GridCells_proto_rawDescData
}

var file_nav_msgs_GridCells_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nav_msgs_GridCells_proto_goTypes = []any{
	(*GridCells)(nil),           // 0: nav_msgs.GridCells
	(*std_msgs.Header)(nil),     // 1: std_msgs.Header
	(*geometry_msgs.Point)(nil), // 2: geometry_msgs.Point
}
var file_nav_msgs_GridCells_proto_depIdxs = []int32{
	1, // 0: nav_msgs.GridCells.Header:type_name -> std_msgs.Header
	2, // 1: nav_msgs.GridCells.Cells:type_name -> geometry_msgs.Point
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nav_msgs_GridCells_proto_init() }
func file_nav_msgs_GridCells_proto_init() {
	if File_nav_msgs_GridCells_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nav_msgs_GridCells_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nav_msgs_GridCells_proto_goTypes,
		DependencyIndexes: file_nav_msgs_GridCells_proto_depIdxs,
		MessageInfos:      file_nav_msgs_GridCells_proto_msgTypes,
	}.Build()
	File_nav_msgs_GridCells_proto = out.File
	file_nav_msgs_GridCells_proto_rawDesc = nil
	file_nav_msgs_GridCells_proto_goTypes = nil
	file_nav_msgs_GridCells_proto_depIdxs = nil
}
