// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: nav_msgs/OccupancyGrid.proto

package nav_msgs

import (
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OccupancyGrid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *std_msgs.Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Info   *MapMetaData     `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	Data   []int32          `protobuf:"varint,3,rep,packed,name=Data,proto3" json:"Data,omitempty"`
}

func (x *OccupancyGrid) Reset() {
	*x = OccupancyGrid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nav_msgs_OccupancyGrid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OccupancyGrid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupancyGrid) ProtoMessage() {}

func (x *OccupancyGrid) ProtoReflect() protoreflect.Message {
	mi := &file_nav_msgs_OccupancyGrid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupancyGrid.ProtoReflect.Descriptor instead.
func (*OccupancyGrid) Descriptor() ([]byte, []int) {
	return file_nav_msgs_OccupancyGrid_proto_rawDescGZIP(), []int{0}
}

func (x *OccupancyGrid) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *OccupancyGrid) GetInfo() *MapMetaData {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *OccupancyGrid) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_nav_msgs_OccupancyGrid_proto protoreflect.FileDescriptor

var file_nav_msgs_OccupancyGrid_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4f, 0x63, 0x63, 0x75, 0x70,
	0x61, 0x6e, 0x63, 0x79, 0x47, 0x72, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x1a, 0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2f, 0x4d, 0x61, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78, 0x0a, 0x0d, 0x4f,
	0x63, 0x63, 0x75, 0x70, 0x61, 0x6e, 0x63, 0x79, 0x47, 0x72, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73,
	0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e,
	0x4d, 0x61, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x6e, 0x61, 0x76, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nav_msgs_OccupancyGrid_proto_rawDescOnce sync.Once
	file_nav_msgs_OccupancyGrid_proto_rawDescData = file_nav_msgs_OccupancyGrid_proto_rawDesc
)

func file_nav_msgs_OccupancyGrid_proto_rawDescGZIP() []byte {
	file_nav_msgs_OccupancyGrid_proto_rawDescOnce.Do(func() {
		file_nav_msgs_OccupancyGrid_proto_rawDescData = protoimpl.X.CompressGZIP(file_nav_msgs_OccupancyGrid_proto_rawDescData)
	})
	return file_nav_msgs_OccupancyGrid_proto_rawDescData
}

var file_nav_msgs_OccupancyGrid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nav_msgs_OccupancyGrid_proto_goTypes = []any{
	(*OccupancyGrid)(nil),   // 0: nav_msgs.OccupancyGrid
	(*std_msgs.Header)(nil), // 1: std_msgs.Header
	(*MapMetaData)(nil),     // 2: nav_msgs.MapMetaData
}
var file_nav_msgs_OccupancyGrid_proto_depIdxs = []int32{
	1, // 0: nav_msgs.OccupancyGrid.Header:type_name -> std_msgs.Header
	2, // 1: nav_msgs.OccupancyGrid.Info:type_name -> nav_msgs.MapMetaData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nav_msgs_OccupancyGrid_proto_init() }
func file_nav_msgs_OccupancyGrid_proto_init() {
	if File_nav_msgs_OccupancyGrid_proto != nil {
		return
	}
	file_nav_msgs_MapMetaData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_nav_msgs_OccupancyGrid_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OccupancyGrid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nav_msgs_OccupancyGrid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nav_msgs_OccupancyGrid_proto_goTypes,
		DependencyIndexes: file_nav_msgs_OccupancyGrid_proto_depIdxs,
		MessageInfos:      file_nav_msgs_OccupancyGrid_proto_msgTypes,
	}.Build()
	File_nav_msgs_OccupancyGrid_proto = out.File
	file_nav_msgs_OccupancyGrid_proto_rawDesc = nil
	file_nav_msgs_OccupancyGrid_proto_goTypes = nil
	file_nav_msgs_OccupancyGrid_proto_depIdxs = nil
}
