//autogenerated:yes
//nolint:revive,lll
package turtlebot3_example

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/actionlib_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Turtlebot3ActionResult struct {
    msg.Package `ros:"turtlebot3_example"`
    Header std_msgs.Header
    Status actionlib_msgs.GoalStatus
    Result Turtlebot3Result
}

