// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: visualization_msgs/InteractiveMarkerPose.proto

package visualization_msgs

import (
	geometry_msgs "go_agent/telemetry/genproto/ros/geometry_msgs"
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractiveMarkerPose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *std_msgs.Header    `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Pose   *geometry_msgs.Pose `protobuf:"bytes,2,opt,name=Pose,proto3" json:"Pose,omitempty"`
	Name   string              `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *InteractiveMarkerPose) Reset() {
	*x = InteractiveMarkerPose{}
	mi := &file_visualization_msgs_InteractiveMarkerPose_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractiveMarkerPose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractiveMarkerPose) ProtoMessage() {}

func (x *InteractiveMarkerPose) ProtoReflect() protoreflect.Message {
	mi := &file_visualization_msgs_InteractiveMarkerPose_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractiveMarkerPose.ProtoReflect.Descriptor instead.
func (*InteractiveMarkerPose) Descriptor() ([]byte, []int) {
	return file_visualization_msgs_InteractiveMarkerPose_proto_rawDescGZIP(), []int{0}
}

func (x *InteractiveMarkerPose) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InteractiveMarkerPose) GetPose() *geometry_msgs.Pose {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *InteractiveMarkerPose) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_visualization_msgs_InteractiveMarkerPose_proto protoreflect.FileDescriptor

var file_visualization_msgs_InteractiveMarkerPose_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x76, 0x69, 0x73, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x2f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x76, 0x69, 0x73, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x1a, 0x18, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x2f, 0x50, 0x6f, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15,
	0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x65, 0x52, 0x04, 0x50, 0x6f, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x76, 0x69, 0x73, 0x75, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_visualization_msgs_InteractiveMarkerPose_proto_rawDescOnce sync.Once
	file_visualization_msgs_InteractiveMarkerPose_proto_rawDescData = file_visualization_msgs_InteractiveMarkerPose_proto_rawDesc
)

func file_visualization_msgs_InteractiveMarkerPose_proto_rawDescGZIP() []byte {
	file_visualization_msgs_InteractiveMarkerPose_proto_rawDescOnce.Do(func() {
		file_visualization_msgs_InteractiveMarkerPose_proto_rawDescData = protoimpl.X.CompressGZIP(file_visualization_msgs_InteractiveMarkerPose_proto_rawDescData)
	})
	return file_visualization_msgs_InteractiveMarkerPose_proto_rawDescData
}

var file_visualization_msgs_InteractiveMarkerPose_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_visualization_msgs_InteractiveMarkerPose_proto_goTypes = []any{
	(*InteractiveMarkerPose)(nil), // 0: visualization_msgs.InteractiveMarkerPose
	(*std_msgs.Header)(nil),       // 1: std_msgs.Header
	(*geometry_msgs.Pose)(nil),    // 2: geometry_msgs.Pose
}
var file_visualization_msgs_InteractiveMarkerPose_proto_depIdxs = []int32{
	1, // 0: visualization_msgs.InteractiveMarkerPose.Header:type_name -> std_msgs.Header
	2, // 1: visualization_msgs.InteractiveMarkerPose.Pose:type_name -> geometry_msgs.Pose
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_visualization_msgs_InteractiveMarkerPose_proto_init() }
func file_visualization_msgs_InteractiveMarkerPose_proto_init() {
	if File_visualization_msgs_InteractiveMarkerPose_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_visualization_msgs_InteractiveMarkerPose_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_visualization_msgs_InteractiveMarkerPose_proto_goTypes,
		DependencyIndexes: file_visualization_msgs_InteractiveMarkerPose_proto_depIdxs,
		MessageInfos:      file_visualization_msgs_InteractiveMarkerPose_proto_msgTypes,
	}.Build()
	File_visualization_msgs_InteractiveMarkerPose_proto = out.File
	file_visualization_msgs_InteractiveMarkerPose_proto_rawDesc = nil
	file_visualization_msgs_InteractiveMarkerPose_proto_goTypes = nil
	file_visualization_msgs_InteractiveMarkerPose_proto_depIdxs = nil
}
