//autogenerated:yes
//nolint:revive,lll
package viso2_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type VisoInfo struct {
    msg.Package `ros:"viso2_ros"`
    Header std_msgs.Header
    GotLost bool
    ChangeReferenceFrame bool
    MotionEstimateValid bool
    NumMatches int32
    NumInliers int32
    Runtime float64
}

