//autogenerated:yes
//nolint:revive,lll
package gazebo_video_monitor_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Pose struct {
    msg.Package `ros:"gazebo_video_monitor_msgs"`
    X float64
    Y float64
    Z float64
    Roll float64
    Pitch float64
    Yaw float64
}

