//autogenerated:yes
//nolint:revive,lll
package gazebo_video_monitor_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type StartGmcmRecordingReq struct {
    msg.Package `ros:"gazebo_video_monitor_msgs"`
    Cameras Strings
}



type StartGmcmRecordingRes struct {
    msg.Package `ros:"gazebo_video_monitor_msgs"`
}

type StartGmcmRecording struct {
    msg.Package `ros:"gazebo_video_monitor_msgs"`
    StartGmcmRecordingReq
    StartGmcmRecordingRes
}
