//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type TriangleListPrimitive struct {
    msg.Package `ros:"foxglove_msgs"`
    Pose geometry_msgs.Pose
    Points []geometry_msgs.Point
    Color Color
    Colors []Color
    Indices []uint32
}

