//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SceneEntityUpdate struct {
    msg.Package `ros:"foxglove_msgs"`
    Deletions []SceneEntityDeletion
    Entities []SceneEntity
}

