//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type GeoJSON struct {
    msg.Package `ros:"foxglove_msgs"`
    Geojson string
}

