//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type ConeListMarker struct {
    msg.Package `ros:"foxglove_msgs"`
    Timestamp time.Time
    FrameId string
    Id string
    Lifetime time.Duration
    FrameLocked bool
    Metadata []KeyValuePair
    Attributes []ConeAttributes
}

