//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type ArrowPrimitive struct {
    msg.Package `ros:"foxglove_msgs"`
    Pose geometry_msgs.Pose
    ShaftLength float64
    ShaftDiameter float64
    HeadLength float64
    HeadDiameter float64
    Color Color
}

