//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Point2 struct {
    msg.Package `ros:"foxglove_msgs"`
    X float64
    Y float64
}

