//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


const (
    PrimitiveDeletion_MATCHING_ID uint8 = 0
    PrimitiveDeletion_ALL uint8 = 1
)

type PrimitiveDeletion struct {
    msg.Package `ros:"foxglove_msgs"`
    msg.Definitions `ros:"uint8 MATCHING_ID=0,uint8 ALL=1"`
    Timestamp time.Time
    Type uint8
    Id string
}

