//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "time"
)


type LaserScan struct {
    msg.Package `ros:"foxglove_msgs"`
    Timestamp time.Time
    FrameId string
    Pose geometry_msgs.Pose
    StartAngle float64
    EndAngle float64
    Ranges []float64
    Intensities []float64
}

