//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type RawImage struct {
    msg.Package `ros:"foxglove_msgs"`
    Timestamp time.Time
    FrameId string
    Width uint32
    Height uint32
    Encoding string
    Step uint32
    Data []uint8
}

