//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type ModelMarker struct {
    msg.Package `ros:"foxglove_msgs"`
    Pose geometry_msgs.Pose
    Scale geometry_msgs.Vector3
    Color Color
    UseEmbeddedMaterials bool
    Url string
    MimeType string
    Data []uint8
}

