//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type CompressedImage struct {
    msg.Package `ros:"foxglove_msgs"`
    Timestamp time.Time
    FrameId string
    Data []uint8
    Format string
}

