//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ImageAnnotations struct {
    msg.Package `ros:"foxglove_msgs"`
    Circles []CircleAnnotation
    Points []PointsAnnotation
}

