//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


const (
    PackedElementField_UNKNOWN uint8 = 0
    PackedElementField_UINT8 uint8 = 1
    PackedElementField_INT8 uint8 = 2
    PackedElementField_UINT16 uint8 = 3
    PackedElementField_INT16 uint8 = 4
    PackedElementField_UINT32 uint8 = 5
    PackedElementField_INT32 uint8 = 6
    PackedElementField_FLOAT32 uint8 = 7
    PackedElementField_FLOAT64 uint8 = 8
)

type PackedElementField struct {
    msg.Package `ros:"foxglove_msgs"`
    msg.Definitions `ros:"uint8 UNKNOWN=0,uint8 UINT8=1,uint8 INT8=2,uint8 UINT16=3,uint8 INT16=4,uint8 UINT32=5,uint8 INT32=6,uint8 FLOAT32=7,uint8 FLOAT64=8"`
    Name string
    Offset uint32
    Type uint8
}

