//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


const (
    LocationFix_UNKNOWN uint8 = 0
    LocationFix_APPROXIMATED uint8 = 1
    LocationFix_DIAGONAL_KNOWN uint8 = 2
    LocationFix_KNOWN uint8 = 3
)

type LocationFix struct {
    msg.Package `ros:"foxglove_msgs"`
    msg.Definitions `ros:"uint8 UNKNOWN=0,uint8 APPROXIMATED=1,uint8 DIAGONAL_KNOWN=2,uint8 KNOWN=3"`
    Latitude float64
    Longitude float64
    Altitude float64
    PositionCovariance [9]float64
    PositionCovarianceType uint8
}

