//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "time"
)


type CylinderMarker struct {
    msg.Package `ros:"foxglove_msgs"`
    Timestamp time.Time
    FrameId string
    Id string
    Lifetime time.Duration
    FrameLocked bool
    Metadata []KeyValuePair
    Pose geometry_msgs.Pose
    BottomRadius float64
    TopRadius float64
    Height float64
    Color Color
}

