//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Color struct {
    msg.Package `ros:"foxglove_msgs"`
    R float64
    G float64
    B float64
    A float64
}

