//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Markers struct {
    msg.Package `ros:"foxglove_msgs"`
    Deletions []MarkerDeletion
    Arrows []ArrowMarker
    Cubes []CubeListMarker
    Spheres []SphereListMarker
    Cones []ConeListMarker
    Lines []LineMarker
    Triangles []TriangleListMarker
    Texts []TextMarker
    Models []ModelMarker
}

