//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type SphereMarker struct {
    msg.Package `ros:"foxglove_msgs"`
    Pose geometry_msgs.Pose
    Size geometry_msgs.Vector3
    Color Color
}

