//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type CircleAnnotation struct {
    msg.Package `ros:"foxglove_msgs"`
    Timestamp time.Time
    Position Point2
    Diameter float64
    Thickness float64
    FillColor Color
    OutlineColor Color
}

