//autogenerated:yes
//nolint:revive,lll
package foxglove_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type CameraCalibration struct {
    msg.Package `ros:"foxglove_msgs"`
    Timestamp time.Time
    FrameId string
    Width uint32
    Height uint32
    DistortionModel string
    D []float64`rosname:"D"`
    K [9]float64`rosname:"K"`
    R [9]float64`rosname:"R"`
    P [12]float64`rosname:"P"`
}

