//autogenerated:yes
//nolint:revive,lll
package ar_track_alvar_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type AlvarMarkers struct {
    msg.Package `ros:"ar_track_alvar_msgs"`
    Header std_msgs.Header
    Markers []AlvarMarker
}

