// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: sensor_msgs/Image.proto

package sensor_msgs

import (
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header      *std_msgs.Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Height      uint32           `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	Width       uint32           `protobuf:"varint,3,opt,name=Width,proto3" json:"Width,omitempty"`
	Encoding    string           `protobuf:"bytes,4,opt,name=Encoding,proto3" json:"Encoding,omitempty"`
	IsBigendian uint32           `protobuf:"varint,5,opt,name=IsBigendian,proto3" json:"IsBigendian,omitempty"`
	Step        uint32           `protobuf:"varint,6,opt,name=Step,proto3" json:"Step,omitempty"`
	Data        []uint32         `protobuf:"varint,7,rep,packed,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_msgs_Image_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_msgs_Image_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_sensor_msgs_Image_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Image) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Image) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *Image) GetIsBigendian() uint32 {
	if x != nil {
		return x.IsBigendian
	}
	return 0
}

func (x *Image) GetStep() uint32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Image) GetData() []uint32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_sensor_msgs_Image_proto protoreflect.FileDescriptor

var file_sensor_msgs_Image_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x15, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73,
	0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01,
	0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x49,
	0x73, 0x42, 0x69, 0x67, 0x65, 0x6e, 0x64, 0x69, 0x61, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x49, 0x73, 0x42, 0x69, 0x67, 0x65, 0x6e, 0x64, 0x69, 0x61, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x74, 0x65, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x74, 0x65,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sensor_msgs_Image_proto_rawDescOnce sync.Once
	file_sensor_msgs_Image_proto_rawDescData = file_sensor_msgs_Image_proto_rawDesc
)

func file_sensor_msgs_Image_proto_rawDescGZIP() []byte {
	file_sensor_msgs_Image_proto_rawDescOnce.Do(func() {
		file_sensor_msgs_Image_proto_rawDescData = protoimpl.X.CompressGZIP(file_sensor_msgs_Image_proto_rawDescData)
	})
	return file_sensor_msgs_Image_proto_rawDescData
}

var file_sensor_msgs_Image_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sensor_msgs_Image_proto_goTypes = []any{
	(*Image)(nil),           // 0: sensor_msgs.Image
	(*std_msgs.Header)(nil), // 1: std_msgs.Header
}
var file_sensor_msgs_Image_proto_depIdxs = []int32{
	1, // 0: sensor_msgs.Image.Header:type_name -> std_msgs.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sensor_msgs_Image_proto_init() }
func file_sensor_msgs_Image_proto_init() {
	if File_sensor_msgs_Image_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sensor_msgs_Image_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sensor_msgs_Image_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sensor_msgs_Image_proto_goTypes,
		DependencyIndexes: file_sensor_msgs_Image_proto_depIdxs,
		MessageInfos:      file_sensor_msgs_Image_proto_msgTypes,
	}.Build()
	File_sensor_msgs_Image_proto = out.File
	file_sensor_msgs_Image_proto_rawDesc = nil
	file_sensor_msgs_Image_proto_goTypes = nil
	file_sensor_msgs_Image_proto_depIdxs = nil
}
