// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: sensor_msgs/JoyFeedback.proto

package sensor_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoyFeedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      uint32  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Id        uint32  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Intensity float32 `protobuf:"fixed32,3,opt,name=Intensity,proto3" json:"Intensity,omitempty"`
}

func (x *JoyFeedback) Reset() {
	*x = JoyFeedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sensor_msgs_JoyFeedback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoyFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoyFeedback) ProtoMessage() {}

func (x *JoyFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_msgs_JoyFeedback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoyFeedback.ProtoReflect.Descriptor instead.
func (*JoyFeedback) Descriptor() ([]byte, []int) {
	return file_sensor_msgs_JoyFeedback_proto_rawDescGZIP(), []int{0}
}

func (x *JoyFeedback) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *JoyFeedback) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JoyFeedback) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

var File_sensor_msgs_JoyFeedback_proto protoreflect.FileDescriptor

var file_sensor_msgs_JoyFeedback_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4a, 0x6f,
	0x79, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x4f, 0x0a, 0x0b,
	0x4a, 0x6f, 0x79, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73,
	0x2f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sensor_msgs_JoyFeedback_proto_rawDescOnce sync.Once
	file_sensor_msgs_JoyFeedback_proto_rawDescData = file_sensor_msgs_JoyFeedback_proto_rawDesc
)

func file_sensor_msgs_JoyFeedback_proto_rawDescGZIP() []byte {
	file_sensor_msgs_JoyFeedback_proto_rawDescOnce.Do(func() {
		file_sensor_msgs_JoyFeedback_proto_rawDescData = protoimpl.X.CompressGZIP(file_sensor_msgs_JoyFeedback_proto_rawDescData)
	})
	return file_sensor_msgs_JoyFeedback_proto_rawDescData
}

var file_sensor_msgs_JoyFeedback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sensor_msgs_JoyFeedback_proto_goTypes = []any{
	(*JoyFeedback)(nil), // 0: sensor_msgs.JoyFeedback
}
var file_sensor_msgs_JoyFeedback_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sensor_msgs_JoyFeedback_proto_init() }
func file_sensor_msgs_JoyFeedback_proto_init() {
	if File_sensor_msgs_JoyFeedback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sensor_msgs_JoyFeedback_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*JoyFeedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sensor_msgs_JoyFeedback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sensor_msgs_JoyFeedback_proto_goTypes,
		DependencyIndexes: file_sensor_msgs_JoyFeedback_proto_depIdxs,
		MessageInfos:      file_sensor_msgs_JoyFeedback_proto_msgTypes,
	}.Build()
	File_sensor_msgs_JoyFeedback_proto = out.File
	file_sensor_msgs_JoyFeedback_proto_rawDesc = nil
	file_sensor_msgs_JoyFeedback_proto_goTypes = nil
	file_sensor_msgs_JoyFeedback_proto_depIdxs = nil
}
