//autogenerated:yes
//nolint:revive,lll
package mpc_local_planner_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type StateFeedback struct {
    msg.Package `ros:"mpc_local_planner_msgs"`
    Header std_msgs.Header
    State []float64
}

