//autogenerated:yes
//nolint:revive,lll
package mpc_local_planner_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type OptimalControlResult struct {
    msg.Package `ros:"mpc_local_planner_msgs"`
    Header std_msgs.Header
    DimStates int64
    DimControls int64
    TimeStates []float64
    States []float64
    TimeControls []float64
    Controls []float64
    OptimalSolutionFound bool
    CpuTime float64
}

