// This file is auto-generated by rostoproto, do not edit Manually!!

package turtlebot3result_sub

import (
	"github.com/bluenviron/goroslib/v2"
	"go_agent/telemetry/gengo/ros"
)

var msgStream chan turtlebot3_example.Turtlebot3Result
var initialized bool = false
var msgC turtlebot3_example.Turtlebot3Result

func msgCallback(msg *turtlebot3_example.Turtlebot3Result) {
	if !initialized {
		return
	}

	if msg != nil {
		msgC = *msg
		msgStream <- msgC
	}
}

func Init(topicName string, n *goroslib.Node, msgS chan turtlebot3_example.Turtlebot3Result, done chan int) error {
	msgStream = msgS
	sub, err := goroslib.NewSubscriber(goroslib.SubscriberConf{
		Node:     n,
		Topic:    topicName,
		Callback: msgCallback,
	})

	if err != nil {
		return fmt.Errorf("Failed to create subscriber for topic %q: %v", topicName, err)
	}
	initialized = true
	// wait for done
	<-done
}
