//autogenerated:yes
//nolint:revive,lll
package teb_local_planner

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/costmap_converter"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type FeedbackMsg struct {
    msg.Package `ros:"teb_local_planner"`
    Header std_msgs.Header
    Trajectories []TrajectoryMsg
    SelectedTrajectoryIdx uint16
    ObstaclesMsg costmap_converter.ObstacleArrayMsg
}

