//autogenerated:yes
//nolint:revive,lll
package map_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ProjectedMapInfo struct {
    msg.Package `ros:"map_msgs"`
    FrameId string
    X float64
    Y float64
    Width float64
    Height float64
    MinZ float64
    MaxZ float64
}

