//autogenerated:yes
//nolint:revive,lll
package map_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type OccupancyGridUpdate struct {
    msg.Package `ros:"map_msgs"`
    Header std_msgs.Header
    X int32
    Y int32
    Width uint32
    Height uint32
    Data []int8
}

