//autogenerated:yes
//nolint:revive,lll
package map_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/nav_msgs"
)


type GetMapROIReq struct {
    msg.Package `ros:"map_msgs"`
    X float64
    Y float64
    LX float64
    LY float64
}



type GetMapROIRes struct {
    msg.Package `ros:"map_msgs"`
    SubMap nav_msgs.OccupancyGrid
}

type GetMapROI struct {
    msg.Package `ros:"map_msgs"`
    GetMapROIReq
    GetMapROIRes
}
