//autogenerated:yes
//nolint:revive,lll
package map_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
)


type GetPointMapReq struct {
    msg.Package `ros:"map_msgs"`
}



type GetPointMapRes struct {
    msg.Package `ros:"map_msgs"`
    Map sensor_msgs.PointCloud2
}

type GetPointMap struct {
    msg.Package `ros:"map_msgs"`
    GetPointMapReq
    GetPointMapRes
}
