//autogenerated:yes
//nolint:revive,lll
package map_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type SaveMapReq struct {
    msg.Package `ros:"map_msgs"`
    Filename std_msgs.String
}



type SaveMapRes struct {
    msg.Package `ros:"map_msgs"`
}

type SaveMap struct {
    msg.Package `ros:"map_msgs"`
    SaveMapReq
    SaveMapRes
}
