//autogenerated:yes
//nolint:revive,lll
package smach_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type SmachContainerStatus struct {
    msg.Package `ros:"smach_msgs"`
    Header std_msgs.Header
    Path string
    InitialStates []string
    ActiveStates []string
    LocalData string
    Info string
}

