//autogenerated:yes
//nolint:revive,lll
package pcl_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type PointIndices struct {
    msg.Package `ros:"pcl_msgs"`
    Header std_msgs.Header
    Indices []int32
}

