//autogenerated:yes
//nolint:revive,lll
package pcl_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Vertices struct {
    msg.Package `ros:"pcl_msgs"`
    Vertices []uint32
}

