// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: turtlebot3_msgs/VersionInfo.proto

package turtlebot3_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hardware string `protobuf:"bytes,1,opt,name=Hardware,proto3" json:"Hardware,omitempty"`
	Firmware string `protobuf:"bytes,2,opt,name=Firmware,proto3" json:"Firmware,omitempty"`
	Software string `protobuf:"bytes,3,opt,name=Software,proto3" json:"Software,omitempty"`
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_turtlebot3_msgs_VersionInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_turtlebot3_msgs_VersionInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_turtlebot3_msgs_VersionInfo_proto_rawDescGZIP(), []int{0}
}

func (x *VersionInfo) GetHardware() string {
	if x != nil {
		return x.Hardware
	}
	return ""
}

func (x *VersionInfo) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *VersionInfo) GetSoftware() string {
	if x != nil {
		return x.Software
	}
	return ""
}

var File_turtlebot3_msgs_VersionInfo_proto protoreflect.FileDescriptor

var file_turtlebot3_msgs_VersionInfo_proto_rawDesc = []byte{
	0x0a, 0x21, 0x74, 0x75, 0x72, 0x74, 0x6c, 0x65, 0x62, 0x6f, 0x74, 0x33, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x2f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x74, 0x75, 0x72, 0x74, 0x6c, 0x65, 0x62, 0x6f, 0x74, 0x33, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x22, 0x61, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x46, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x46, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53,
	0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x6f, 0x5f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x74, 0x75, 0x72, 0x74, 0x6c,
	0x65, 0x62, 0x6f, 0x74, 0x33, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_turtlebot3_msgs_VersionInfo_proto_rawDescOnce sync.Once
	file_turtlebot3_msgs_VersionInfo_proto_rawDescData = file_turtlebot3_msgs_VersionInfo_proto_rawDesc
)

func file_turtlebot3_msgs_VersionInfo_proto_rawDescGZIP() []byte {
	file_turtlebot3_msgs_VersionInfo_proto_rawDescOnce.Do(func() {
		file_turtlebot3_msgs_VersionInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_turtlebot3_msgs_VersionInfo_proto_rawDescData)
	})
	return file_turtlebot3_msgs_VersionInfo_proto_rawDescData
}

var file_turtlebot3_msgs_VersionInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turtlebot3_msgs_VersionInfo_proto_goTypes = []any{
	(*VersionInfo)(nil), // 0: turtlebot3_msgs.VersionInfo
}
var file_turtlebot3_msgs_VersionInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_turtlebot3_msgs_VersionInfo_proto_init() }
func file_turtlebot3_msgs_VersionInfo_proto_init() {
	if File_turtlebot3_msgs_VersionInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_turtlebot3_msgs_VersionInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turtlebot3_msgs_VersionInfo_proto_goTypes,
		DependencyIndexes: file_turtlebot3_msgs_VersionInfo_proto_depIdxs,
		MessageInfos:      file_turtlebot3_msgs_VersionInfo_proto_msgTypes,
	}.Build()
	File_turtlebot3_msgs_VersionInfo_proto = out.File
	file_turtlebot3_msgs_VersionInfo_proto_rawDesc = nil
	file_turtlebot3_msgs_VersionInfo_proto_goTypes = nil
	file_turtlebot3_msgs_VersionInfo_proto_depIdxs = nil
}
