//autogenerated:yes
//nolint:revive,lll
package std_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type Time struct {
    msg.Package `ros:"std_msgs"`
    Data time.Time
}

