receivers:
  - name: "joystick"
    enabled: true
    exchange: "client"
    queue: "joystick"
    consumer: "agent-joystick"
    message_type: "geometry_msgs/Twist"
    auto_ack: false
    ros_topic: "/cmd_vel"
    ros_node_name: "joystick_cmd_vel_publisher"
    wait_for_ros_subscriber: "/cmd_vel_node"
