topics:
  - "/odom_with_amcl"
  - "/cmd_vel"
  - "/cmd_vel_filtered"
  - "/move_base_flex_SmacLattice_unsmoothed_plan"
  - "/move_base_flex_TebLocalPlannerROS_global_plan"
  - "/task_feedback"
  - "/uavcanRosBridge/uavcan_ros_bridge/Battery"
