//autogenerated:yes
//nolint:revive,lll
package seven_robot_perception

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/pcl_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type ModelCoefficientsArray struct {
    msg.Package `ros:"seven_robot_perception"`
    Header std_msgs.Header
    Coefficients []pcl_msgs.ModelCoefficients
}

