//autogenerated:yes
//nolint:revive,lll
package seven_robot_perception

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type BoundingBox struct {
    msg.Package `ros:"seven_robot_perception"`
    Header std_msgs.Header
    Dimension geometry_msgs.Vector3
    Pose geometry_msgs.PoseStamped
    Id uint32
}

