//autogenerated:yes
//nolint:revive,lll
package seven_robot_perception

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type SVMFile struct {
    msg.Package `ros:"seven_robot_perception"`
    Name std_msgs.String
}

