//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type TypeDef struct {
    msg.Package `ros:"rosapi"`
    Type string
    Fieldnames []string
    Fieldtypes []string
    Fieldarraylen []int32
    Examples []string
    Constnames []string
    Constvalues []string
}

