//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type NodeDetailsReq struct {
    msg.Package `ros:"rosapi"`
    Node string
}



type NodeDetailsRes struct {
    msg.Package `ros:"rosapi"`
    Subscribing []string
    Publishing []string
    Services []string
}

type NodeDetails struct {
    msg.Package `ros:"rosapi"`
    NodeDetailsReq
    NodeDetailsRes
}
