//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type TopicsAndRawTypesReq struct {
    msg.Package `ros:"rosapi"`
}



type TopicsAndRawTypesRes struct {
    msg.Package `ros:"rosapi"`
    Topics []string
    Types []string
    TypedefsFullText []string
}

type TopicsAndRawTypes struct {
    msg.Package `ros:"rosapi"`
    TopicsAndRawTypesReq
    TopicsAndRawTypesRes
}
