//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ServiceResponseDetailsReq struct {
    msg.Package `ros:"rosapi"`
    Type string
}



type ServiceResponseDetailsRes struct {
    msg.Package `ros:"rosapi"`
    Typedefs []TypeDef
}

type ServiceResponseDetails struct {
    msg.Package `ros:"rosapi"`
    ServiceResponseDetailsReq
    ServiceResponseDetailsRes
}
