//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ServiceHostReq struct {
    msg.Package `ros:"rosapi"`
    Service string
}



type ServiceHostRes struct {
    msg.Package `ros:"rosapi"`
    Host string
}

type ServiceHost struct {
    msg.Package `ros:"rosapi"`
    ServiceHostReq
    ServiceHostRes
}
