//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SubscribersReq struct {
    msg.Package `ros:"rosapi"`
    Topic string
}



type SubscribersRes struct {
    msg.Package `ros:"rosapi"`
    Subscribers []string
}

type Subscribers struct {
    msg.Package `ros:"rosapi"`
    SubscribersReq
    SubscribersRes
}
