//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ServiceRequestDetailsReq struct {
    msg.Package `ros:"rosapi"`
    Type string
}



type ServiceRequestDetailsRes struct {
    msg.Package `ros:"rosapi"`
    Typedefs []TypeDef
}

type ServiceRequestDetails struct {
    msg.Package `ros:"rosapi"`
    ServiceRequestDetailsReq
    ServiceRequestDetailsRes
}
