//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type MessageDetailsReq struct {
    msg.Package `ros:"rosapi"`
    Type string
}



type MessageDetailsRes struct {
    msg.Package `ros:"rosapi"`
    Typedefs []TypeDef
}

type MessageDetails struct {
    msg.Package `ros:"rosapi"`
    MessageDetailsReq
    MessageDetailsRes
}
