//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ServicesForTypeReq struct {
    msg.Package `ros:"rosapi"`
    Type string
}



type ServicesForTypeRes struct {
    msg.Package `ros:"rosapi"`
    Services []string
}

type ServicesForType struct {
    msg.Package `ros:"rosapi"`
    ServicesForTypeReq
    ServicesForTypeRes
}
