//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ServicesReq struct {
    msg.Package `ros:"rosapi"`
}



type ServicesRes struct {
    msg.Package `ros:"rosapi"`
    Services []string
}

type Services struct {
    msg.Package `ros:"rosapi"`
    ServicesReq
    ServicesRes
}
