//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SetParamReq struct {
    msg.Package `ros:"rosapi"`
    Name string
    Value string
}



type SetParamRes struct {
    msg.Package `ros:"rosapi"`
}

type SetParam struct {
    msg.Package `ros:"rosapi"`
    SetParamReq
    SetParamRes
}
