//autogenerated:yes
//nolint:revive,lll
package rosapi

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type GetTimeReq struct {
    msg.Package `ros:"rosapi"`
}



type GetTimeRes struct {
    msg.Package `ros:"rosapi"`
    Time time.Time
}

type GetTime struct {
    msg.Package `ros:"rosapi"`
    GetTimeReq
    GetTimeRes
}
