// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: pcl_msgs/Vertices.proto

package pcl_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vertices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertices []uint32 `protobuf:"varint,1,rep,packed,name=Vertices,proto3" json:"Vertices,omitempty"`
}

func (x *Vertices) Reset() {
	*x = Vertices{}
	mi := &file_pcl_msgs_Vertices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vertices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertices) ProtoMessage() {}

func (x *Vertices) ProtoReflect() protoreflect.Message {
	mi := &file_pcl_msgs_Vertices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertices.ProtoReflect.Descriptor instead.
func (*Vertices) Descriptor() ([]byte, []int) {
	return file_pcl_msgs_Vertices_proto_rawDescGZIP(), []int{0}
}

func (x *Vertices) GetVertices() []uint32 {
	if x != nil {
		return x.Vertices
	}
	return nil
}

var File_pcl_msgs_Vertices_proto protoreflect.FileDescriptor

var file_pcl_msgs_Vertices_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x63, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x56, 0x65, 0x72, 0x74, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x63, 0x6c, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x22, 0x26, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x08, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67,
	0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x70,
	0x63, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pcl_msgs_Vertices_proto_rawDescOnce sync.Once
	file_pcl_msgs_Vertices_proto_rawDescData = file_pcl_msgs_Vertices_proto_rawDesc
)

func file_pcl_msgs_Vertices_proto_rawDescGZIP() []byte {
	file_pcl_msgs_Vertices_proto_rawDescOnce.Do(func() {
		file_pcl_msgs_Vertices_proto_rawDescData = protoimpl.X.CompressGZIP(file_pcl_msgs_Vertices_proto_rawDescData)
	})
	return file_pcl_msgs_Vertices_proto_rawDescData
}

var file_pcl_msgs_Vertices_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pcl_msgs_Vertices_proto_goTypes = []any{
	(*Vertices)(nil), // 0: pcl_msgs.Vertices
}
var file_pcl_msgs_Vertices_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pcl_msgs_Vertices_proto_init() }
func file_pcl_msgs_Vertices_proto_init() {
	if File_pcl_msgs_Vertices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pcl_msgs_Vertices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pcl_msgs_Vertices_proto_goTypes,
		DependencyIndexes: file_pcl_msgs_Vertices_proto_depIdxs,
		MessageInfos:      file_pcl_msgs_Vertices_proto_msgTypes,
	}.Build()
	File_pcl_msgs_Vertices_proto = out.File
	file_pcl_msgs_Vertices_proto_rawDesc = nil
	file_pcl_msgs_Vertices_proto_goTypes = nil
	file_pcl_msgs_Vertices_proto_depIdxs = nil
}
