// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: seven_robotics_msgs/BatteryHealth.proto

package seven_robotics_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatteryHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Health uint32 `protobuf:"varint,1,opt,name=Health,proto3" json:"Health,omitempty"`
}

func (x *BatteryHealth) Reset() {
	*x = BatteryHealth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seven_robotics_msgs_BatteryHealth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatteryHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryHealth) ProtoMessage() {}

func (x *BatteryHealth) ProtoReflect() protoreflect.Message {
	mi := &file_seven_robotics_msgs_BatteryHealth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryHealth.ProtoReflect.Descriptor instead.
func (*BatteryHealth) Descriptor() ([]byte, []int) {
	return file_seven_robotics_msgs_BatteryHealth_proto_rawDescGZIP(), []int{0}
}

func (x *BatteryHealth) GetHealth() uint32 {
	if x != nil {
		return x.Health
	}
	return 0
}

var File_seven_robotics_msgs_BatteryHealth_proto protoreflect.FileDescriptor

var file_seven_robotics_msgs_BatteryHealth_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x65, 0x76, 0x65, 0x6e,
	0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x27,
	0x0a, 0x0d, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x6f, 0x5f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x76, 0x65, 0x6e,
	0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seven_robotics_msgs_BatteryHealth_proto_rawDescOnce sync.Once
	file_seven_robotics_msgs_BatteryHealth_proto_rawDescData = file_seven_robotics_msgs_BatteryHealth_proto_rawDesc
)

func file_seven_robotics_msgs_BatteryHealth_proto_rawDescGZIP() []byte {
	file_seven_robotics_msgs_BatteryHealth_proto_rawDescOnce.Do(func() {
		file_seven_robotics_msgs_BatteryHealth_proto_rawDescData = protoimpl.X.CompressGZIP(file_seven_robotics_msgs_BatteryHealth_proto_rawDescData)
	})
	return file_seven_robotics_msgs_BatteryHealth_proto_rawDescData
}

var file_seven_robotics_msgs_BatteryHealth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seven_robotics_msgs_BatteryHealth_proto_goTypes = []any{
	(*BatteryHealth)(nil), // 0: seven_robotics_msgs.BatteryHealth
}
var file_seven_robotics_msgs_BatteryHealth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seven_robotics_msgs_BatteryHealth_proto_init() }
func file_seven_robotics_msgs_BatteryHealth_proto_init() {
	if File_seven_robotics_msgs_BatteryHealth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seven_robotics_msgs_BatteryHealth_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BatteryHealth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seven_robotics_msgs_BatteryHealth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seven_robotics_msgs_BatteryHealth_proto_goTypes,
		DependencyIndexes: file_seven_robotics_msgs_BatteryHealth_proto_depIdxs,
		MessageInfos:      file_seven_robotics_msgs_BatteryHealth_proto_msgTypes,
	}.Build()
	File_seven_robotics_msgs_BatteryHealth_proto = out.File
	file_seven_robotics_msgs_BatteryHealth_proto_rawDesc = nil
	file_seven_robotics_msgs_BatteryHealth_proto_goTypes = nil
	file_seven_robotics_msgs_BatteryHealth_proto_depIdxs = nil
}
