// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: seven_robotics_msgs/EgoVelocity.proto

package seven_robotics_msgs

import (
	geometry_msgs "go_agent/telemetry/genproto/ros/geometry_msgs"
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EgoVelocity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *std_msgs.Header     `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Velocity *geometry_msgs.Twist `protobuf:"bytes,2,opt,name=Velocity,proto3" json:"Velocity,omitempty"`
}

func (x *EgoVelocity) Reset() {
	*x = EgoVelocity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seven_robotics_msgs_EgoVelocity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EgoVelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgoVelocity) ProtoMessage() {}

func (x *EgoVelocity) ProtoReflect() protoreflect.Message {
	mi := &file_seven_robotics_msgs_EgoVelocity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgoVelocity.ProtoReflect.Descriptor instead.
func (*EgoVelocity) Descriptor() ([]byte, []int) {
	return file_seven_robotics_msgs_EgoVelocity_proto_rawDescGZIP(), []int{0}
}

func (x *EgoVelocity) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EgoVelocity) GetVelocity() *geometry_msgs.Twist {
	if x != nil {
		return x.Velocity
	}
	return nil
}

var File_seven_robotics_msgs_EgoVelocity_proto protoreflect.FileDescriptor

var file_seven_robotics_msgs_EgoVelocity_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x45, 0x67, 0x6f, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x19, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x54, 0x77, 0x69, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69,
	0x0a, 0x0b, 0x45, 0x67, 0x6f, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x28, 0x0a,
	0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x08, 0x56, 0x65, 0x6c, 0x6f, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6f, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x54, 0x77, 0x69, 0x73, 0x74, 0x52,
	0x08, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x6f, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x76,
	0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seven_robotics_msgs_EgoVelocity_proto_rawDescOnce sync.Once
	file_seven_robotics_msgs_EgoVelocity_proto_rawDescData = file_seven_robotics_msgs_EgoVelocity_proto_rawDesc
)

func file_seven_robotics_msgs_EgoVelocity_proto_rawDescGZIP() []byte {
	file_seven_robotics_msgs_EgoVelocity_proto_rawDescOnce.Do(func() {
		file_seven_robotics_msgs_EgoVelocity_proto_rawDescData = protoimpl.X.CompressGZIP(file_seven_robotics_msgs_EgoVelocity_proto_rawDescData)
	})
	return file_seven_robotics_msgs_EgoVelocity_proto_rawDescData
}

var file_seven_robotics_msgs_EgoVelocity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seven_robotics_msgs_EgoVelocity_proto_goTypes = []any{
	(*EgoVelocity)(nil),         // 0: seven_robotics_msgs.EgoVelocity
	(*std_msgs.Header)(nil),     // 1: std_msgs.Header
	(*geometry_msgs.Twist)(nil), // 2: geometry_msgs.Twist
}
var file_seven_robotics_msgs_EgoVelocity_proto_depIdxs = []int32{
	1, // 0: seven_robotics_msgs.EgoVelocity.Header:type_name -> std_msgs.Header
	2, // 1: seven_robotics_msgs.EgoVelocity.Velocity:type_name -> geometry_msgs.Twist
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_seven_robotics_msgs_EgoVelocity_proto_init() }
func file_seven_robotics_msgs_EgoVelocity_proto_init() {
	if File_seven_robotics_msgs_EgoVelocity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seven_robotics_msgs_EgoVelocity_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EgoVelocity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seven_robotics_msgs_EgoVelocity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seven_robotics_msgs_EgoVelocity_proto_goTypes,
		DependencyIndexes: file_seven_robotics_msgs_EgoVelocity_proto_depIdxs,
		MessageInfos:      file_seven_robotics_msgs_EgoVelocity_proto_msgTypes,
	}.Build()
	File_seven_robotics_msgs_EgoVelocity_proto = out.File
	file_seven_robotics_msgs_EgoVelocity_proto_rawDesc = nil
	file_seven_robotics_msgs_EgoVelocity_proto_goTypes = nil
	file_seven_robotics_msgs_EgoVelocity_proto_depIdxs = nil
}
