// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: seven_robotics_msgs/MotorEncoder.proto

package seven_robotics_msgs

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MotorEncoder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp  *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	EncoderID  uint32               `protobuf:"varint,2,opt,name=EncoderID,proto3" json:"EncoderID,omitempty"`
	Ticks      uint32               `protobuf:"varint,3,opt,name=Ticks,proto3" json:"Ticks,omitempty"`
	TotalCount int64                `protobuf:"varint,4,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	TickHz     float32              `protobuf:"fixed32,5,opt,name=TickHz,proto3" json:"TickHz,omitempty"`
}

func (x *MotorEncoder) Reset() {
	*x = MotorEncoder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seven_robotics_msgs_MotorEncoder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MotorEncoder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorEncoder) ProtoMessage() {}

func (x *MotorEncoder) ProtoReflect() protoreflect.Message {
	mi := &file_seven_robotics_msgs_MotorEncoder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorEncoder.ProtoReflect.Descriptor instead.
func (*MotorEncoder) Descriptor() ([]byte, []int) {
	return file_seven_robotics_msgs_MotorEncoder_proto_rawDescGZIP(), []int{0}
}

func (x *MotorEncoder) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MotorEncoder) GetEncoderID() uint32 {
	if x != nil {
		return x.EncoderID
	}
	return 0
}

func (x *MotorEncoder) GetTicks() uint32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

func (x *MotorEncoder) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *MotorEncoder) GetTickHz() float32 {
	if x != nil {
		return x.TickHz
	}
	return 0
}

var File_seven_robotics_msgs_MotorEncoder_proto protoreflect.FileDescriptor

var file_seven_robotics_msgs_MotorEncoder_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4,
	0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x12,
	0x38, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x63, 0x6b, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x54, 0x69, 0x63, 0x6b, 0x48, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x54,
	0x69, 0x63, 0x6b, 0x48, 0x7a, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seven_robotics_msgs_MotorEncoder_proto_rawDescOnce sync.Once
	file_seven_robotics_msgs_MotorEncoder_proto_rawDescData = file_seven_robotics_msgs_MotorEncoder_proto_rawDesc
)

func file_seven_robotics_msgs_MotorEncoder_proto_rawDescGZIP() []byte {
	file_seven_robotics_msgs_MotorEncoder_proto_rawDescOnce.Do(func() {
		file_seven_robotics_msgs_MotorEncoder_proto_rawDescData = protoimpl.X.CompressGZIP(file_seven_robotics_msgs_MotorEncoder_proto_rawDescData)
	})
	return file_seven_robotics_msgs_MotorEncoder_proto_rawDescData
}

var file_seven_robotics_msgs_MotorEncoder_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seven_robotics_msgs_MotorEncoder_proto_goTypes = []any{
	(*MotorEncoder)(nil),        // 0: seven_robotics_msgs.MotorEncoder
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_seven_robotics_msgs_MotorEncoder_proto_depIdxs = []int32{
	1, // 0: seven_robotics_msgs.MotorEncoder.Timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_seven_robotics_msgs_MotorEncoder_proto_init() }
func file_seven_robotics_msgs_MotorEncoder_proto_init() {
	if File_seven_robotics_msgs_MotorEncoder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seven_robotics_msgs_MotorEncoder_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MotorEncoder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seven_robotics_msgs_MotorEncoder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seven_robotics_msgs_MotorEncoder_proto_goTypes,
		DependencyIndexes: file_seven_robotics_msgs_MotorEncoder_proto_depIdxs,
		MessageInfos:      file_seven_robotics_msgs_MotorEncoder_proto_msgTypes,
	}.Build()
	File_seven_robotics_msgs_MotorEncoder_proto = out.File
	file_seven_robotics_msgs_MotorEncoder_proto_rawDesc = nil
	file_seven_robotics_msgs_MotorEncoder_proto_goTypes = nil
	file_seven_robotics_msgs_MotorEncoder_proto_depIdxs = nil
}
