// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: seven_robotics_msgs/SlidingWindowPoses.proto

package seven_robotics_msgs

import (
	geometry_msgs "go_agent/telemetry/genproto/ros/geometry_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlidingWindowPoses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetPoses []*geometry_msgs.PoseStamped `protobuf:"bytes,1,rep,name=TargetPoses,proto3" json:"TargetPoses,omitempty"`
}

func (x *SlidingWindowPoses) Reset() {
	*x = SlidingWindowPoses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seven_robotics_msgs_SlidingWindowPoses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlidingWindowPoses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlidingWindowPoses) ProtoMessage() {}

func (x *SlidingWindowPoses) ProtoReflect() protoreflect.Message {
	mi := &file_seven_robotics_msgs_SlidingWindowPoses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlidingWindowPoses.ProtoReflect.Descriptor instead.
func (*SlidingWindowPoses) Descriptor() ([]byte, []int) {
	return file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDescGZIP(), []int{0}
}

func (x *SlidingWindowPoses) GetTargetPoses() []*geometry_msgs.PoseStamped {
	if x != nil {
		return x.TargetPoses
	}
	return nil
}

var File_seven_robotics_msgs_SlidingWindowPoses_proto protoreflect.FileDescriptor

var file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x53, 0x6c, 0x69, 0x64, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x50, 0x6f, 0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x1a, 0x1f, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2f, 0x50, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x12, 0x53, 0x6c, 0x69, 0x64, 0x69, 0x6e, 0x67, 0x57,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x50, 0x6f, 0x73, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e,
	0x50, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x65, 0x64, 0x52, 0x0b, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x65, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x6f, 0x5f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x76, 0x65,
	0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDescOnce sync.Once
	file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDescData = file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDesc
)

func file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDescGZIP() []byte {
	file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDescOnce.Do(func() {
		file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDescData = protoimpl.X.CompressGZIP(file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDescData)
	})
	return file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDescData
}

var file_seven_robotics_msgs_SlidingWindowPoses_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seven_robotics_msgs_SlidingWindowPoses_proto_goTypes = []any{
	(*SlidingWindowPoses)(nil),        // 0: seven_robotics_msgs.SlidingWindowPoses
	(*geometry_msgs.PoseStamped)(nil), // 1: geometry_msgs.PoseStamped
}
var file_seven_robotics_msgs_SlidingWindowPoses_proto_depIdxs = []int32{
	1, // 0: seven_robotics_msgs.SlidingWindowPoses.TargetPoses:type_name -> geometry_msgs.PoseStamped
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_seven_robotics_msgs_SlidingWindowPoses_proto_init() }
func file_seven_robotics_msgs_SlidingWindowPoses_proto_init() {
	if File_seven_robotics_msgs_SlidingWindowPoses_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seven_robotics_msgs_SlidingWindowPoses_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SlidingWindowPoses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seven_robotics_msgs_SlidingWindowPoses_proto_goTypes,
		DependencyIndexes: file_seven_robotics_msgs_SlidingWindowPoses_proto_depIdxs,
		MessageInfos:      file_seven_robotics_msgs_SlidingWindowPoses_proto_msgTypes,
	}.Build()
	File_seven_robotics_msgs_SlidingWindowPoses_proto = out.File
	file_seven_robotics_msgs_SlidingWindowPoses_proto_rawDesc = nil
	file_seven_robotics_msgs_SlidingWindowPoses_proto_goTypes = nil
	file_seven_robotics_msgs_SlidingWindowPoses_proto_depIdxs = nil
}
