//autogenerated:yes
//nolint:revive,lll
package find_object_2d

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type DetectionInfo struct {
    msg.Package `ros:"find_object_2d"`
    Header std_msgs.Header
    Ids []std_msgs.Int32
    Widths []std_msgs.Int32
    Heights []std_msgs.Int32
    FilePaths []std_msgs.String
    Inliers []std_msgs.Int32
    Outliers []std_msgs.Int32
    Homographies []std_msgs.Float32MultiArray
}

