// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: teleop_tools_msgs/IncrementGoal.proto

package teleop_tools_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncrementGoal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncrementBy []float32 `protobuf:"fixed32,1,rep,packed,name=IncrementBy,proto3" json:"IncrementBy,omitempty"`
}

func (x *IncrementGoal) Reset() {
	*x = IncrementGoal{}
	mi := &file_teleop_tools_msgs_IncrementGoal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementGoal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementGoal) ProtoMessage() {}

func (x *IncrementGoal) ProtoReflect() protoreflect.Message {
	mi := &file_teleop_tools_msgs_IncrementGoal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementGoal.ProtoReflect.Descriptor instead.
func (*IncrementGoal) Descriptor() ([]byte, []int) {
	return file_teleop_tools_msgs_IncrementGoal_proto_rawDescGZIP(), []int{0}
}

func (x *IncrementGoal) GetIncrementBy() []float32 {
	if x != nil {
		return x.IncrementBy
	}
	return nil
}

var File_teleop_tools_msgs_IncrementGoal_proto protoreflect.FileDescriptor

var file_teleop_tools_msgs_IncrementGoal_proto_rawDesc = []byte{
	0x0a, 0x25, 0x74, 0x65, 0x6c, 0x65, 0x6f, 0x70, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x2f, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x6f, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x74, 0x65, 0x6c, 0x65, 0x6f, 0x70, 0x5f,
	0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x31, 0x0a, 0x0d, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x49,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02,
	0x52, 0x0b, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73,
	0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6f, 0x70, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teleop_tools_msgs_IncrementGoal_proto_rawDescOnce sync.Once
	file_teleop_tools_msgs_IncrementGoal_proto_rawDescData = file_teleop_tools_msgs_IncrementGoal_proto_rawDesc
)

func file_teleop_tools_msgs_IncrementGoal_proto_rawDescGZIP() []byte {
	file_teleop_tools_msgs_IncrementGoal_proto_rawDescOnce.Do(func() {
		file_teleop_tools_msgs_IncrementGoal_proto_rawDescData = protoimpl.X.CompressGZIP(file_teleop_tools_msgs_IncrementGoal_proto_rawDescData)
	})
	return file_teleop_tools_msgs_IncrementGoal_proto_rawDescData
}

var file_teleop_tools_msgs_IncrementGoal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_teleop_tools_msgs_IncrementGoal_proto_goTypes = []any{
	(*IncrementGoal)(nil), // 0: teleop_tools_msgs.IncrementGoal
}
var file_teleop_tools_msgs_IncrementGoal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teleop_tools_msgs_IncrementGoal_proto_init() }
func file_teleop_tools_msgs_IncrementGoal_proto_init() {
	if File_teleop_tools_msgs_IncrementGoal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teleop_tools_msgs_IncrementGoal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teleop_tools_msgs_IncrementGoal_proto_goTypes,
		DependencyIndexes: file_teleop_tools_msgs_IncrementGoal_proto_depIdxs,
		MessageInfos:      file_teleop_tools_msgs_IncrementGoal_proto_msgTypes,
	}.Build()
	File_teleop_tools_msgs_IncrementGoal_proto = out.File
	file_teleop_tools_msgs_IncrementGoal_proto_rawDesc = nil
	file_teleop_tools_msgs_IncrementGoal_proto_goTypes = nil
	file_teleop_tools_msgs_IncrementGoal_proto_depIdxs = nil
}
