// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: plotjuggler_msgs/DataPoint.proto

package plotjuggler_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameIndex uint32  `protobuf:"varint,1,opt,name=NameIndex,proto3" json:"NameIndex,omitempty"`
	Stamp     float64 `protobuf:"fixed64,2,opt,name=Stamp,proto3" json:"Stamp,omitempty"`
	Value     float64 `protobuf:"fixed64,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plotjuggler_msgs_DataPoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_plotjuggler_msgs_DataPoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_plotjuggler_msgs_DataPoint_proto_rawDescGZIP(), []int{0}
}

func (x *DataPoint) GetNameIndex() uint32 {
	if x != nil {
		return x.NameIndex
	}
	return 0
}

func (x *DataPoint) GetStamp() float64 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_plotjuggler_msgs_DataPoint_proto protoreflect.FileDescriptor

var file_plotjuggler_msgs_DataPoint_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6c, 0x6f, 0x74, 0x6a, 0x75, 0x67, 0x67, 0x6c, 0x65, 0x72, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2f, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x70, 0x6c, 0x6f, 0x74, 0x6a, 0x75, 0x67, 0x67, 0x6c, 0x65, 0x72, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x22, 0x55, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x70,
	0x6c, 0x6f, 0x74, 0x6a, 0x75, 0x67, 0x67, 0x6c, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plotjuggler_msgs_DataPoint_proto_rawDescOnce sync.Once
	file_plotjuggler_msgs_DataPoint_proto_rawDescData = file_plotjuggler_msgs_DataPoint_proto_rawDesc
)

func file_plotjuggler_msgs_DataPoint_proto_rawDescGZIP() []byte {
	file_plotjuggler_msgs_DataPoint_proto_rawDescOnce.Do(func() {
		file_plotjuggler_msgs_DataPoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_plotjuggler_msgs_DataPoint_proto_rawDescData)
	})
	return file_plotjuggler_msgs_DataPoint_proto_rawDescData
}

var file_plotjuggler_msgs_DataPoint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plotjuggler_msgs_DataPoint_proto_goTypes = []any{
	(*DataPoint)(nil), // 0: plotjuggler_msgs.DataPoint
}
var file_plotjuggler_msgs_DataPoint_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plotjuggler_msgs_DataPoint_proto_init() }
func file_plotjuggler_msgs_DataPoint_proto_init() {
	if File_plotjuggler_msgs_DataPoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plotjuggler_msgs_DataPoint_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DataPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plotjuggler_msgs_DataPoint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plotjuggler_msgs_DataPoint_proto_goTypes,
		DependencyIndexes: file_plotjuggler_msgs_DataPoint_proto_depIdxs,
		MessageInfos:      file_plotjuggler_msgs_DataPoint_proto_msgTypes,
	}.Build()
	File_plotjuggler_msgs_DataPoint_proto = out.File
	file_plotjuggler_msgs_DataPoint_proto_rawDesc = nil
	file_plotjuggler_msgs_DataPoint_proto_goTypes = nil
	file_plotjuggler_msgs_DataPoint_proto_depIdxs = nil
}
