// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: plotjuggler_msgs/StatisticsValues.proto

package plotjuggler_msgs

import (
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticsValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header       *std_msgs.Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Values       []float64        `protobuf:"fixed64,2,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	NamesVersion uint32           `protobuf:"varint,3,opt,name=NamesVersion,proto3" json:"NamesVersion,omitempty"`
}

func (x *StatisticsValues) Reset() {
	*x = StatisticsValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plotjuggler_msgs_StatisticsValues_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsValues) ProtoMessage() {}

func (x *StatisticsValues) ProtoReflect() protoreflect.Message {
	mi := &file_plotjuggler_msgs_StatisticsValues_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsValues.ProtoReflect.Descriptor instead.
func (*StatisticsValues) Descriptor() ([]byte, []int) {
	return file_plotjuggler_msgs_StatisticsValues_proto_rawDescGZIP(), []int{0}
}

func (x *StatisticsValues) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StatisticsValues) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *StatisticsValues) GetNamesVersion() uint32 {
	if x != nil {
		return x.NamesVersion
	}
	return 0
}

var File_plotjuggler_msgs_StatisticsValues_proto protoreflect.FileDescriptor

var file_plotjuggler_msgs_StatisticsValues_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6c, 0x6f, 0x74, 0x6a, 0x75, 0x67, 0x67, 0x6c, 0x65, 0x72, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2f, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x6c, 0x6f, 0x74, 0x6a,
	0x75, 0x67, 0x67, 0x6c, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x15, 0x73, 0x74, 0x64,
	0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x78, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01,
	0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f,
	0x70, 0x6c, 0x6f, 0x74, 0x6a, 0x75, 0x67, 0x67, 0x6c, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plotjuggler_msgs_StatisticsValues_proto_rawDescOnce sync.Once
	file_plotjuggler_msgs_StatisticsValues_proto_rawDescData = file_plotjuggler_msgs_StatisticsValues_proto_rawDesc
)

func file_plotjuggler_msgs_StatisticsValues_proto_rawDescGZIP() []byte {
	file_plotjuggler_msgs_StatisticsValues_proto_rawDescOnce.Do(func() {
		file_plotjuggler_msgs_StatisticsValues_proto_rawDescData = protoimpl.X.CompressGZIP(file_plotjuggler_msgs_StatisticsValues_proto_rawDescData)
	})
	return file_plotjuggler_msgs_StatisticsValues_proto_rawDescData
}

var file_plotjuggler_msgs_StatisticsValues_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plotjuggler_msgs_StatisticsValues_proto_goTypes = []any{
	(*StatisticsValues)(nil), // 0: plotjuggler_msgs.StatisticsValues
	(*std_msgs.Header)(nil),  // 1: std_msgs.Header
}
var file_plotjuggler_msgs_StatisticsValues_proto_depIdxs = []int32{
	1, // 0: plotjuggler_msgs.StatisticsValues.Header:type_name -> std_msgs.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plotjuggler_msgs_StatisticsValues_proto_init() }
func file_plotjuggler_msgs_StatisticsValues_proto_init() {
	if File_plotjuggler_msgs_StatisticsValues_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plotjuggler_msgs_StatisticsValues_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StatisticsValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plotjuggler_msgs_StatisticsValues_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plotjuggler_msgs_StatisticsValues_proto_goTypes,
		DependencyIndexes: file_plotjuggler_msgs_StatisticsValues_proto_depIdxs,
		MessageInfos:      file_plotjuggler_msgs_StatisticsValues_proto_msgTypes,
	}.Build()
	File_plotjuggler_msgs_StatisticsValues_proto = out.File
	file_plotjuggler_msgs_StatisticsValues_proto_rawDesc = nil
	file_plotjuggler_msgs_StatisticsValues_proto_goTypes = nil
	file_plotjuggler_msgs_StatisticsValues_proto_depIdxs = nil
}
