package rostoproto

import (
	"fmt"
	"path/filepath"
)

type ProtobufPackage struct {
	SimpleTarget

	// If true, generate protobuf serializations for all public types.
	// If false, only generate protobuf serializations for structs that
	// request serialization.
	GenerateAll bool

	// A list of names that this package exports
	LocalNames map[string]struct{}

	// A list of type names in this package that will need marshaller rewriting
	// to remove synthetic protobuf fields.
	OptionalTypeNames map[string]struct{}

	// A list of struct tags to generate onto named struct fields
	StructTags map[string]map[string]string

	// An import tracker for this package
	Imports *ImportTracker
}

func newProtobufPackage(packagePath, packageDir, packageName string, generateAll bool) *ProtobufPackage {
	pkg := &ProtobufPackage{
		SimpleTarget: SimpleTarget{
			PkgName:       packageName,
			PkgPath:       packagePath,
			PkgDir:        packageDir,
			HeaderComment: []byte("// This file is auto-generated by rostoproto, do not edit Manually!!\n\n\n"),
		},
		GenerateAll: generateAll,
	}
	pkg.GeneratorsFunc = pkg.generatorsFunc
	return pkg
}

func (p *ProtobufPackage) ProtoTypeName() Name {
	return Name{
		Name:    p.Path(), // the ros msg path std_msgs/header
		Package: p.Name(), // the protobuf package std_msgs.header
		Path:    p.ImportPath(),
	}
}

func (p *ProtobufPackage) ImportPath() string {
	return filepath.Join(p.Path(), fmt.Sprintf("%s.proto", p.Name()))
}

func (p *ProtobufPackage) OutputPath() string {
	return filepath.Join(p.Path(), fmt.Sprintf("%s.pb.go", p.Name()))
}

func (p *ProtobufPackage) generatorsFunc(c *Context) []Generator {
	generators := []Generator{}

	generators = append(generators, &genProtoIDL{
		RosMsgGenerator: RosMsgGenerator{
			OutputFilename: p.Name(),
		},
		localPackage:    Name{Package: p.Name(), Path: p.Path()},
		localRosPackage: Name{Package: p.Path(), Name: p.RosPackageName()},
		generateAll:     p.GenerateAll,
		// imports:         *p.Imports,
	})
	// log.Printf("Returning generator for package %v with path %v and ros package name %v\n",
	// 	p.Name(), p.Path(), p.RosPackageName())
	return generators
}

func (p *ProtobufPackage) RosPackageName() string {
	return filepath.Base(p.Path())
}

var (
	_ = Target(&ProtobufPackage{})
)
