//autogenerated:yes
//nolint:revive,lll
package graph_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type GeometryGraph struct {
    msg.Package `ros:"graph_msgs"`
    Header std_msgs.Header
    Nodes []geometry_msgs.Point
    Edges []Edges
}

