//autogenerated:yes
//nolint:revive,lll
package graph_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Edges struct {
    msg.Package `ros:"graph_msgs"`
    NodeIds []uint32
    Weights []float64
}

