package rostogo

import (
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/bluenviron/goroslib/v2/pkg/conversion"
)

func ImportPackage(pkgDir string, outputDir string) error {
	pkgName := filepath.Base(pkgDir)
	err := os.MkdirAll(outputDir, 0755)
	if err != nil {
		log.Fatalf("Failed to create output directory %s: %v", outputDir, err)
	}
	if pkgName == "seven_robotics_msgs" {
		return importPackageWithoutActions(pkgName, pkgDir, outputDir)
	}
	return conversion.ImportPackage(pkgName, pkgDir, outputDir)
}

func importPackageWithoutActions(pkgName string, pkgDir string, outputDir string) error {
	if err := writePackageFile(pkgName, outputDir); err != nil {
		return err
	}

	return filepath.WalkDir(pkgDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && d.Name() == "action" {
			return filepath.SkipDir
		}
		if d.IsDir() {
			return nil
		}

		switch filepath.Ext(d.Name()) {
		case ".msg":
			outpath := filepath.Join(outputDir, "msg_"+strings.TrimSuffix(strings.ToLower(d.Name()), ".msg")+".go")
			f, err := os.Create(outpath)
			if err != nil {
				return err
			}
			defer f.Close()
			if err := conversion.ImportMessage(path, pkgName, pkgName, f); err != nil {
				os.Remove(outpath)
				return err
			}
		case ".srv":
			outpath := filepath.Join(outputDir, "srv_"+strings.TrimSuffix(strings.ToLower(d.Name()), ".srv")+".go")
			f, err := os.Create(outpath)
			if err != nil {
				return err
			}
			defer f.Close()
			if err := conversion.ImportService(path, pkgName, pkgName, f); err != nil {
				os.Remove(outpath)
				return err
			}
		}

		return nil
	})
}

func writePackageFile(pkgName string, outputDir string) error {
	content := []byte("// Package " + pkgName + " contains message definitions.\n" +
		"//\n" +
		"//autogenerated:yes\n" +
		"//nolint:revive\n" +
		"package " + pkgName + "\n")
	return os.WriteFile(filepath.Join(outputDir, "package.go"), content, 0644)
}
