//autogenerated:yes
//nolint:revive,lll
package nav_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type GetMapResult struct {
    msg.Package `ros:"nav_msgs"`
    Map OccupancyGrid
}

