//autogenerated:yes
//nolint:revive,lll
package nav_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type GridCells struct {
    msg.Package `ros:"nav_msgs"`
    Header std_msgs.Header
    CellWidth float32
    CellHeight float32
    Cells []geometry_msgs.Point
}

