//autogenerated:yes
//nolint:revive,lll
package nav_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type SetMapReq struct {
    msg.Package `ros:"nav_msgs"`
    Map OccupancyGrid
    InitialPose geometry_msgs.PoseWithCovarianceStamped
}



type SetMapRes struct {
    msg.Package `ros:"nav_msgs"`
    Success bool
}

type SetMap struct {
    msg.Package `ros:"nav_msgs"`
    SetMapReq
    SetMapRes
}
