//autogenerated:yes
//nolint:revive,lll
package tf2_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/actionlib_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type LookupTransformActionFeedback struct {
    msg.Package `ros:"tf2_msgs"`
    Header std_msgs.Header
    Status actionlib_msgs.GoalStatus
    Feedback LookupTransformFeedback
}

