//autogenerated:yes
//nolint:revive,lll
package tf2_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type LookupTransformGoal struct {
    msg.Package `ros:"tf2_msgs"`
    TargetFrame string
    SourceFrame string
    SourceTime time.Time
    Timeout time.Duration
    TargetTime time.Time
    FixedFrame string
    Advanced bool
}

