//autogenerated:yes
//nolint:revive,lll
package tf2_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type LookupTransformResult struct {
    msg.Package `ros:"tf2_msgs"`
    Transform geometry_msgs.TransformStamped
    Error TF2Error
}

