//autogenerated:yes
//nolint:revive,lll
package tf2_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type TFMessage struct {
    msg.Package `ros:"tf2_msgs"`
    Transforms []geometry_msgs.TransformStamped
}

