//autogenerated:yes
//nolint:revive,lll
package teleop_tools_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/actionlib_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type IncrementActionFeedback struct {
    msg.Package `ros:"teleop_tools_msgs"`
    Header std_msgs.Header
    Status actionlib_msgs.GoalStatus
    Feedback IncrementFeedback
}

