//autogenerated:yes
//nolint:revive,lll
package teleop_tools_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type IncrementAction struct {
    msg.Package `ros:"teleop_tools_msgs"`
    ActionGoal IncrementActionGoal
    ActionResult IncrementActionResult
    ActionFeedback IncrementActionFeedback
}

