//autogenerated:yes
//nolint:revive,lll
package teleop_tools_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type IncrementGoal struct {
    msg.Package `ros:"teleop_tools_msgs"`
    IncrementBy []float32
}

