//autogenerated:yes
//nolint:revive,lll
package move_base_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type MoveBaseAction struct {
    msg.Package `ros:"move_base_msgs"`
    ActionGoal MoveBaseActionGoal
    ActionResult MoveBaseActionResult
    ActionFeedback MoveBaseActionFeedback
}

