//autogenerated:yes
//nolint:revive,lll
package move_base_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type MoveBaseGoal struct {
    msg.Package `ros:"move_base_msgs"`
    TargetPose geometry_msgs.PoseStamped
}

