// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: seven_robot_perception/ModelCoefficientsArray.proto

package seven_robot_perception

import (
	pcl_msgs "go_agent/telemetry/genproto/ros/pcl_msgs"
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelCoefficientsArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header       *std_msgs.Header              `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Coefficients []*pcl_msgs.ModelCoefficients `protobuf:"bytes,2,rep,name=Coefficients,proto3" json:"Coefficients,omitempty"`
}

func (x *ModelCoefficientsArray) Reset() {
	*x = ModelCoefficientsArray{}
	mi := &file_seven_robot_perception_ModelCoefficientsArray_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCoefficientsArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCoefficientsArray) ProtoMessage() {}

func (x *ModelCoefficientsArray) ProtoReflect() protoreflect.Message {
	mi := &file_seven_robot_perception_ModelCoefficientsArray_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCoefficientsArray.ProtoReflect.Descriptor instead.
func (*ModelCoefficientsArray) Descriptor() ([]byte, []int) {
	return file_seven_robot_perception_ModelCoefficientsArray_proto_rawDescGZIP(), []int{0}
}

func (x *ModelCoefficientsArray) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ModelCoefficientsArray) GetCoefficients() []*pcl_msgs.ModelCoefficients {
	if x != nil {
		return x.Coefficients
	}
	return nil
}

var File_seven_robot_perception_ModelCoefficientsArray_proto protoreflect.FileDescriptor

var file_seven_robot_perception_ModelCoefficientsArray_proto_rawDesc = []byte{
	0x0a, 0x33, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x70, 0x65,
	0x72, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f,
	0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x20, 0x70,
	0x63, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x65,
	0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x15, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x16, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0c, 0x43,
	0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x63, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0c,
	0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x38, 0x5a, 0x36,
	0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f,
	0x73, 0x65, 0x76, 0x65, 0x6e, 0x5f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x63,
	0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seven_robot_perception_ModelCoefficientsArray_proto_rawDescOnce sync.Once
	file_seven_robot_perception_ModelCoefficientsArray_proto_rawDescData = file_seven_robot_perception_ModelCoefficientsArray_proto_rawDesc
)

func file_seven_robot_perception_ModelCoefficientsArray_proto_rawDescGZIP() []byte {
	file_seven_robot_perception_ModelCoefficientsArray_proto_rawDescOnce.Do(func() {
		file_seven_robot_perception_ModelCoefficientsArray_proto_rawDescData = protoimpl.X.CompressGZIP(file_seven_robot_perception_ModelCoefficientsArray_proto_rawDescData)
	})
	return file_seven_robot_perception_ModelCoefficientsArray_proto_rawDescData
}

var file_seven_robot_perception_ModelCoefficientsArray_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seven_robot_perception_ModelCoefficientsArray_proto_goTypes = []any{
	(*ModelCoefficientsArray)(nil),     // 0: seven_robot_perception.ModelCoefficientsArray
	(*std_msgs.Header)(nil),            // 1: std_msgs.Header
	(*pcl_msgs.ModelCoefficients)(nil), // 2: pcl_msgs.ModelCoefficients
}
var file_seven_robot_perception_ModelCoefficientsArray_proto_depIdxs = []int32{
	1, // 0: seven_robot_perception.ModelCoefficientsArray.Header:type_name -> std_msgs.Header
	2, // 1: seven_robot_perception.ModelCoefficientsArray.Coefficients:type_name -> pcl_msgs.ModelCoefficients
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_seven_robot_perception_ModelCoefficientsArray_proto_init() }
func file_seven_robot_perception_ModelCoefficientsArray_proto_init() {
	if File_seven_robot_perception_ModelCoefficientsArray_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seven_robot_perception_ModelCoefficientsArray_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seven_robot_perception_ModelCoefficientsArray_proto_goTypes,
		DependencyIndexes: file_seven_robot_perception_ModelCoefficientsArray_proto_depIdxs,
		MessageInfos:      file_seven_robot_perception_ModelCoefficientsArray_proto_msgTypes,
	}.Build()
	File_seven_robot_perception_ModelCoefficientsArray_proto = out.File
	file_seven_robot_perception_ModelCoefficientsArray_proto_rawDesc = nil
	file_seven_robot_perception_ModelCoefficientsArray_proto_goTypes = nil
	file_seven_robot_perception_ModelCoefficientsArray_proto_depIdxs = nil
}
