package rostoproto

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

var tplMessage = template.Must(template.New("Message").Parse(
	`// This file is autogenerated by ros-to-proto. Do Not Edit
   proto = "syntax3";

   {{- range $v := .Imports}}
   import {{"$v"}};
   {{- end}}
   {{.Message}}
  `,
))

func ImportMessage(path string, protoPkgName string, rosPkgName string, w io.Writer) error {
	name := strings.TrimSuffix(filepath.Base(path), ".msg")

	buf, err := os.ReadFile(path)

	if err != nil {
		return err
	}

	content := string(buf)

	msgDef, err := ParseMessageDefinition(rosPkgName, name, content)
	if err != nil {
		return err
	}
	fmt.Printf("Message PackageName: %v\n", msgDef.RosPkgName)
	fmt.Printf("Message Name: %v\n", msgDef.Name)
	for i, field := range msgDef.Fields {
		fmt.Printf("Field Definition %v : %v\n", i, field)
	}

	for i, def := range msgDef.Definitions {
		fmt.Printf("Message Definition %v: %v\n", i, def)
	}

	fmt.Printf("Message DefinitionStr: %v\n", msgDef.DefinitionsStr)

	return nil
	// message, err := msgDef.write()
	//
	// if err != nil {
	// 	return err
	// }
	//
	// return tplMessage.Execute(w, map[string]interface{}{
	// 	"ProtoPkgName": protoPkgName,
	// 	"RosPkgName":   rosPkgName,
	// 	"Imports":      msgDef.Imports,
	// 	"Message":      message,
	// })
}
