package rostoproto

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

var tpl_package = template.Must(template.New("").Parse(
	`// This file is autogenerated by ros-to-proto.
//  Do Not Edit
package {{ .PkgName }}`))

func WritePackage(fpath string, tpl *template.Template, args map[string]interface{}) error {
	f, err := os.Create(fpath)

	if err != nil {
		return fmt.Errorf("Failed to create file %s: %v", fpath, err)
	}

	defer f.Close()

	return tpl.Execute(f, args)
}

func GenPackageFile(name, dir string) error {
	os.MkdirAll(dir, 0755)

	err := WritePackage(filepath.Join(dir, "package.go"), tpl_package, map[string]interface{}{"PkgName": name})
	if err != nil {
		return err
	}
	return nil
}
