//autogenerated:yes
//nolint:revive,lll
package apriltag_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type AprilTagDetectionArray struct {
    msg.Package `ros:"apriltag_ros"`
    Header std_msgs.Header
    Detections []AprilTagDetection
}

