//autogenerated:yes
//nolint:revive,lll
package apriltag_ros

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/sensor_msgs"
)


type AnalyzeSingleImageReq struct {
    msg.Package `ros:"apriltag_ros"`
    FullPathWhereToGetImage string
    FullPathWhereToSaveImage string
    CameraInfo sensor_msgs.CameraInfo
}



type AnalyzeSingleImageRes struct {
    msg.Package `ros:"apriltag_ros"`
    TagDetections AprilTagDetectionArray
}

type AnalyzeSingleImage struct {
    msg.Package `ros:"apriltag_ros"`
    AnalyzeSingleImageReq
    AnalyzeSingleImageRes
}
