//autogenerated:yes
//nolint:revive,lll
package sound_play

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SoundRequestAction struct {
    msg.Package `ros:"sound_play"`
    ActionGoal SoundRequestActionGoal
    ActionResult SoundRequestActionResult
    ActionFeedback SoundRequestActionFeedback
}

