//autogenerated:yes
//nolint:revive,lll
package geometry_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type AccelStamped struct {
    msg.Package `ros:"geometry_msgs"`
    Header std_msgs.Header
    Accel Accel
}

