//autogenerated:yes
//nolint:revive,lll
package rosbridge_library

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type TestUInt8 struct {
    msg.Package `ros:"rosbridge_library"`
    Data []uint8
}

