//autogenerated:yes
//nolint:revive,lll
package rosbridge_library

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Num struct {
    msg.Package `ros:"rosbridge_library"`
    Num int64
}

