//autogenerated:yes
//nolint:revive,lll
package rosbridge_library

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type TestArrayRequestReq struct {
    msg.Package `ros:"rosbridge_library"`
    Int []int32
}



type TestArrayRequestRes struct {
    msg.Package `ros:"rosbridge_library"`
}

type TestArrayRequest struct {
    msg.Package `ros:"rosbridge_library"`
    TestArrayRequestReq
    TestArrayRequestRes
}
