//autogenerated:yes
//nolint:revive,lll
package rosbridge_library

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SendBytesReq struct {
    msg.Package `ros:"rosbridge_library"`
    Count int64
}



type SendBytesRes struct {
    msg.Package `ros:"rosbridge_library"`
    Data string
}

type SendBytes struct {
    msg.Package `ros:"rosbridge_library"`
    SendBytesReq
    SendBytesRes
}
