//autogenerated:yes
//nolint:revive,lll
package rosbridge_library

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type TestMultipleRequestFieldsReq struct {
    msg.Package `ros:"rosbridge_library"`
    Int int32
    Float float32
    String string
    Bool bool
}



type TestMultipleRequestFieldsRes struct {
    msg.Package `ros:"rosbridge_library"`
}

type TestMultipleRequestFields struct {
    msg.Package `ros:"rosbridge_library"`
    TestMultipleRequestFieldsReq
    TestMultipleRequestFieldsRes
}
