// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: rosgraph_msgs/Log.proto

package rosgraph_msgs

import (
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *std_msgs.Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Level    uint32           `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	Name     string           `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Msg      string           `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	File     string           `protobuf:"bytes,5,opt,name=File,proto3" json:"File,omitempty"`
	Function string           `protobuf:"bytes,6,opt,name=Function,proto3" json:"Function,omitempty"`
	Line     uint32           `protobuf:"varint,7,opt,name=Line,proto3" json:"Line,omitempty"`
	Topics   []string         `protobuf:"bytes,8,rep,name=Topics,proto3" json:"Topics,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosgraph_msgs_Log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_rosgraph_msgs_Log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_rosgraph_msgs_Log_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Log) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Log) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Log) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Log) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Log) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *Log) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Log) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_rosgraph_msgs_Log_proto protoreflect.FileDescriptor

var file_rosgraph_msgs_Log_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x6f, 0x73, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x4c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x6f, 0x73, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x15, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc7, 0x01, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x4c, 0x69, 0x6e,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x6f, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x72, 0x6f, 0x73,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rosgraph_msgs_Log_proto_rawDescOnce sync.Once
	file_rosgraph_msgs_Log_proto_rawDescData = file_rosgraph_msgs_Log_proto_rawDesc
)

func file_rosgraph_msgs_Log_proto_rawDescGZIP() []byte {
	file_rosgraph_msgs_Log_proto_rawDescOnce.Do(func() {
		file_rosgraph_msgs_Log_proto_rawDescData = protoimpl.X.CompressGZIP(file_rosgraph_msgs_Log_proto_rawDescData)
	})
	return file_rosgraph_msgs_Log_proto_rawDescData
}

var file_rosgraph_msgs_Log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rosgraph_msgs_Log_proto_goTypes = []any{
	(*Log)(nil),             // 0: rosgraph_msgs.Log
	(*std_msgs.Header)(nil), // 1: std_msgs.Header
}
var file_rosgraph_msgs_Log_proto_depIdxs = []int32{
	1, // 0: rosgraph_msgs.Log.Header:type_name -> std_msgs.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rosgraph_msgs_Log_proto_init() }
func file_rosgraph_msgs_Log_proto_init() {
	if File_rosgraph_msgs_Log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rosgraph_msgs_Log_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rosgraph_msgs_Log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rosgraph_msgs_Log_proto_goTypes,
		DependencyIndexes: file_rosgraph_msgs_Log_proto_depIdxs,
		MessageInfos:      file_rosgraph_msgs_Log_proto_msgTypes,
	}.Build()
	File_rosgraph_msgs_Log_proto = out.File
	file_rosgraph_msgs_Log_proto_rawDesc = nil
	file_rosgraph_msgs_Log_proto_goTypes = nil
	file_rosgraph_msgs_Log_proto_depIdxs = nil
}
