//autogenerated:yes
//nolint:revive,lll
package people_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type PositionMeasurement struct {
    msg.Package `ros:"people_msgs"`
    Header std_msgs.Header
    Name string
    ObjectId string
    Pos geometry_msgs.Point
    Reliability float64
    Covariance [9]float64
    Initialization int8 `rostype:"byte"`
}

