//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type SingleJointPositionFeedback struct {
    msg.Package `ros:"control_msgs"`
    Header std_msgs.Header
    Position float64
    Velocity float64
    Error float64
}

