//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
    "go_agent/telemetry/gengo/ros/trajectory_msgs"
)


type FollowJointTrajectoryFeedback struct {
    msg.Package `ros:"control_msgs"`
    Header std_msgs.Header
    JointNames []string
    Desired trajectory_msgs.JointTrajectoryPoint
    Actual trajectory_msgs.JointTrajectoryPoint
    Error trajectory_msgs.JointTrajectoryPoint
}

