//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


const (
    FollowJointTrajectoryResult_SUCCESSFUL int32 = 0
    FollowJointTrajectoryResult_INVALID_GOAL int32 = -1
    FollowJointTrajectoryResult_INVALID_JOINTS int32 = -2
    FollowJointTrajectoryResult_OLD_HEADER_TIMESTAMP int32 = -3
    FollowJointTrajectoryResult_PATH_TOLERANCE_VIOLATED int32 = -4
    FollowJointTrajectoryResult_GOAL_TOLERANCE_VIOLATED int32 = -5
)

type FollowJointTrajectoryResult struct {
    msg.Package `ros:"control_msgs"`
    msg.Definitions `ros:"int32 SUCCESSFUL=0,int32 INVALID_GOAL=-1,int32 INVALID_JOINTS=-2,int32 OLD_HEADER_TIMESTAMP=-3,int32 PATH_TOLERANCE_VIOLATED=-4,int32 GOAL_TOLERANCE_VIOLATED=-5"`
    ErrorCode int32
    ErrorString string
}

