//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
    "time"
)


type PidState struct {
    msg.Package `ros:"control_msgs"`
    Header std_msgs.Header
    Timestep time.Duration
    Error float64
    ErrorDot float64
    PError float64
    IError float64
    DError float64
    PTerm float64
    ITerm float64
    DTerm float64
    IMax float64
    IMin float64
    Output float64
}

