//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type GripperCommandFeedback struct {
    msg.Package `ros:"control_msgs"`
    Position float64
    Effort float64
    Stalled bool
    ReachedGoal bool
}

