//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/actionlib_msgs"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type FollowJointTrajectoryActionGoal struct {
    msg.Package `ros:"control_msgs"`
    Header std_msgs.Header
    GoalId actionlib_msgs.GoalID
    Goal FollowJointTrajectoryGoal
}

