//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type SingleJointPositionGoal struct {
    msg.Package `ros:"control_msgs"`
    Position float64
    MinDuration time.Duration
    MaxVelocity float64
}

