//autogenerated:yes
//nolint:revive,lll
package roscpp

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Logger struct {
    msg.Package `ros:"roscpp"`
    Name string
    Level string
}

