//autogenerated:yes
//nolint:revive,lll
package roscpp

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type GetLoggersReq struct {
    msg.Package `ros:"roscpp"`
}



type GetLoggersRes struct {
    msg.Package `ros:"roscpp"`
    Loggers []Logger
}

type GetLoggers struct {
    msg.Package `ros:"roscpp"`
    GetLoggersReq
    GetLoggersRes
}
