//autogenerated:yes
//nolint:revive,lll
package roscpp

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SetLoggerLevelReq struct {
    msg.Package `ros:"roscpp"`
    Logger string
    Level string
}



type SetLoggerLevelRes struct {
    msg.Package `ros:"roscpp"`
}

type SetLoggerLevel struct {
    msg.Package `ros:"roscpp"`
    SetLoggerLevelReq
    SetLoggerLevelRes
}
