//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type LinkState struct {
    msg.Package `ros:"gazebo_msgs"`
    LinkName string
    Pose geometry_msgs.Pose
    Twist geometry_msgs.Twist
    ReferenceFrame string
}

