//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type SetLightPropertiesReq struct {
    msg.Package `ros:"gazebo_msgs"`
    LightName string
    Diffuse std_msgs.ColorRGBA
    AttenuationConstant float64
    AttenuationLinear float64
    AttenuationQuadratic float64
}



type SetLightPropertiesRes struct {
    msg.Package `ros:"gazebo_msgs"`
    Success bool
    StatusMessage string
}

type SetLightProperties struct {
    msg.Package `ros:"gazebo_msgs"`
    SetLightPropertiesReq
    SetLightPropertiesRes
}
