//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type ApplyJointEffortReq struct {
    msg.Package `ros:"gazebo_msgs"`
    JointName string
    Effort float64
    StartTime time.Time
    Duration time.Duration
}



type ApplyJointEffortRes struct {
    msg.Package `ros:"gazebo_msgs"`
    Success bool
    StatusMessage string
}

type ApplyJointEffort struct {
    msg.Package `ros:"gazebo_msgs"`
    ApplyJointEffortReq
    ApplyJointEffortRes
}
