//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type GetPhysicsPropertiesReq struct {
    msg.Package `ros:"gazebo_msgs"`
}



type GetPhysicsPropertiesRes struct {
    msg.Package `ros:"gazebo_msgs"`
    TimeStep float64
    Pause bool
    MaxUpdateRate float64
    Gravity geometry_msgs.Vector3
    OdeConfig ODEPhysics
    Success bool
    StatusMessage string
}

type GetPhysicsProperties struct {
    msg.Package `ros:"gazebo_msgs"`
    GetPhysicsPropertiesReq
    GetPhysicsPropertiesRes
}
