//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type SetPhysicsPropertiesReq struct {
    msg.Package `ros:"gazebo_msgs"`
    TimeStep float64
    MaxUpdateRate float64
    Gravity geometry_msgs.Vector3
    OdeConfig ODEPhysics
}



type SetPhysicsPropertiesRes struct {
    msg.Package `ros:"gazebo_msgs"`
    Success bool
    StatusMessage string
}

type SetPhysicsProperties struct {
    msg.Package `ros:"gazebo_msgs"`
    SetPhysicsPropertiesReq
    SetPhysicsPropertiesRes
}
