//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type BodyRequestReq struct {
    msg.Package `ros:"gazebo_msgs"`
    BodyName string
}



type BodyRequestRes struct {
    msg.Package `ros:"gazebo_msgs"`
}

type BodyRequest struct {
    msg.Package `ros:"gazebo_msgs"`
    BodyRequestReq
    BodyRequestRes
}
