//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type DeleteLightReq struct {
    msg.Package `ros:"gazebo_msgs"`
    LightName string
}



type DeleteLightRes struct {
    msg.Package `ros:"gazebo_msgs"`
    Success bool
    StatusMessage string
}

type DeleteLight struct {
    msg.Package `ros:"gazebo_msgs"`
    DeleteLightReq
    DeleteLightRes
}
