//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type GetLinkStateReq struct {
    msg.Package `ros:"gazebo_msgs"`
    LinkName string
    ReferenceFrame string
}



type GetLinkStateRes struct {
    msg.Package `ros:"gazebo_msgs"`
    LinkState LinkState
    Success bool
    StatusMessage string
}

type GetLinkState struct {
    msg.Package `ros:"gazebo_msgs"`
    GetLinkStateReq
    GetLinkStateRes
}
