//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type JointRequestReq struct {
    msg.Package `ros:"gazebo_msgs"`
    JointName string
}



type JointRequestRes struct {
    msg.Package `ros:"gazebo_msgs"`
}

type JointRequest struct {
    msg.Package `ros:"gazebo_msgs"`
    JointRequestReq
    JointRequestRes
}
