//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SetJointPropertiesReq struct {
    msg.Package `ros:"gazebo_msgs"`
    JointName string
    OdeJointConfig ODEJointProperties
}



type SetJointPropertiesRes struct {
    msg.Package `ros:"gazebo_msgs"`
    Success bool
    StatusMessage string
}

type SetJointProperties struct {
    msg.Package `ros:"gazebo_msgs"`
    SetJointPropertiesReq
    SetJointPropertiesRes
}
