//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/geometry_msgs"
)


type SpawnModelReq struct {
    msg.Package `ros:"gazebo_msgs"`
    ModelName string
    ModelXml string
    RobotNamespace string
    InitialPose geometry_msgs.Pose
    ReferenceFrame string
}



type SpawnModelRes struct {
    msg.Package `ros:"gazebo_msgs"`
    Success bool
    StatusMessage string
}

type SpawnModel struct {
    msg.Package `ros:"gazebo_msgs"`
    SpawnModelReq
    SpawnModelRes
}
