//autogenerated:yes
//nolint:revive,lll
package gazebo_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type SetModelStateReq struct {
    msg.Package `ros:"gazebo_msgs"`
    ModelState ModelState
}



type SetModelStateRes struct {
    msg.Package `ros:"gazebo_msgs"`
    Success bool
    StatusMessage string
}

type SetModelState struct {
    msg.Package `ros:"gazebo_msgs"`
    SetModelStateReq
    SetModelStateRes
}
