// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: rosserial_msgs/TopicInfo.proto

package rosserial_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicId     uint32 `protobuf:"varint,1,opt,name=TopicId,proto3" json:"TopicId,omitempty"`
	TopicName   string `protobuf:"bytes,2,opt,name=TopicName,proto3" json:"TopicName,omitempty"`
	MessageType string `protobuf:"bytes,3,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Md5Sum      string `protobuf:"bytes,4,opt,name=Md5sum,proto3" json:"Md5sum,omitempty"`
	BufferSize  int32  `protobuf:"varint,5,opt,name=BufferSize,proto3" json:"BufferSize,omitempty"`
}

func (x *TopicInfo) Reset() {
	*x = TopicInfo{}
	mi := &file_rosserial_msgs_TopicInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicInfo) ProtoMessage() {}

func (x *TopicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rosserial_msgs_TopicInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicInfo.ProtoReflect.Descriptor instead.
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return file_rosserial_msgs_TopicInfo_proto_rawDescGZIP(), []int{0}
}

func (x *TopicInfo) GetTopicId() uint32 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *TopicInfo) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *TopicInfo) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *TopicInfo) GetMd5Sum() string {
	if x != nil {
		return x.Md5Sum
	}
	return ""
}

func (x *TopicInfo) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

var File_rosserial_msgs_TopicInfo_proto protoreflect.FileDescriptor

var file_rosserial_msgs_TopicInfo_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x73,
	0x2f, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x72, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x73,
	0x22, 0x9d, 0x01, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x64, 0x35, 0x73,
	0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x64, 0x35, 0x73, 0x75, 0x6d,
	0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x53, 0x69, 0x7a, 0x65,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x6f, 0x73, 0x2f, 0x72, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rosserial_msgs_TopicInfo_proto_rawDescOnce sync.Once
	file_rosserial_msgs_TopicInfo_proto_rawDescData = file_rosserial_msgs_TopicInfo_proto_rawDesc
)

func file_rosserial_msgs_TopicInfo_proto_rawDescGZIP() []byte {
	file_rosserial_msgs_TopicInfo_proto_rawDescOnce.Do(func() {
		file_rosserial_msgs_TopicInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_rosserial_msgs_TopicInfo_proto_rawDescData)
	})
	return file_rosserial_msgs_TopicInfo_proto_rawDescData
}

var file_rosserial_msgs_TopicInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rosserial_msgs_TopicInfo_proto_goTypes = []any{
	(*TopicInfo)(nil), // 0: rosserial_msgs.TopicInfo
}
var file_rosserial_msgs_TopicInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rosserial_msgs_TopicInfo_proto_init() }
func file_rosserial_msgs_TopicInfo_proto_init() {
	if File_rosserial_msgs_TopicInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rosserial_msgs_TopicInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rosserial_msgs_TopicInfo_proto_goTypes,
		DependencyIndexes: file_rosserial_msgs_TopicInfo_proto_depIdxs,
		MessageInfos:      file_rosserial_msgs_TopicInfo_proto_msgTypes,
	}.Build()
	File_rosserial_msgs_TopicInfo_proto = out.File
	file_rosserial_msgs_TopicInfo_proto_rawDesc = nil
	file_rosserial_msgs_TopicInfo_proto_goTypes = nil
	file_rosserial_msgs_TopicInfo_proto_depIdxs = nil
}
