// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: gazebo_msgs/ODEJointProperties.proto

package gazebo_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ODEJointProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Damping     []float64 `protobuf:"fixed64,1,rep,packed,name=Damping,proto3" json:"Damping,omitempty"`
	HiStop      []float64 `protobuf:"fixed64,2,rep,packed,name=HiStop,proto3" json:"HiStop,omitempty"`
	LoStop      []float64 `protobuf:"fixed64,3,rep,packed,name=LoStop,proto3" json:"LoStop,omitempty"`
	Erp         []float64 `protobuf:"fixed64,4,rep,packed,name=Erp,proto3" json:"Erp,omitempty"`
	Cfm         []float64 `protobuf:"fixed64,5,rep,packed,name=Cfm,proto3" json:"Cfm,omitempty"`
	StopErp     []float64 `protobuf:"fixed64,6,rep,packed,name=StopErp,proto3" json:"StopErp,omitempty"`
	StopCfm     []float64 `protobuf:"fixed64,7,rep,packed,name=StopCfm,proto3" json:"StopCfm,omitempty"`
	FudgeFactor []float64 `protobuf:"fixed64,8,rep,packed,name=FudgeFactor,proto3" json:"FudgeFactor,omitempty"`
	Fmax        []float64 `protobuf:"fixed64,9,rep,packed,name=Fmax,proto3" json:"Fmax,omitempty"`
	Vel         []float64 `protobuf:"fixed64,10,rep,packed,name=Vel,proto3" json:"Vel,omitempty"`
}

func (x *ODEJointProperties) Reset() {
	*x = ODEJointProperties{}
	mi := &file_gazebo_msgs_ODEJointProperties_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ODEJointProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ODEJointProperties) ProtoMessage() {}

func (x *ODEJointProperties) ProtoReflect() protoreflect.Message {
	mi := &file_gazebo_msgs_ODEJointProperties_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ODEJointProperties.ProtoReflect.Descriptor instead.
func (*ODEJointProperties) Descriptor() ([]byte, []int) {
	return file_gazebo_msgs_ODEJointProperties_proto_rawDescGZIP(), []int{0}
}

func (x *ODEJointProperties) GetDamping() []float64 {
	if x != nil {
		return x.Damping
	}
	return nil
}

func (x *ODEJointProperties) GetHiStop() []float64 {
	if x != nil {
		return x.HiStop
	}
	return nil
}

func (x *ODEJointProperties) GetLoStop() []float64 {
	if x != nil {
		return x.LoStop
	}
	return nil
}

func (x *ODEJointProperties) GetErp() []float64 {
	if x != nil {
		return x.Erp
	}
	return nil
}

func (x *ODEJointProperties) GetCfm() []float64 {
	if x != nil {
		return x.Cfm
	}
	return nil
}

func (x *ODEJointProperties) GetStopErp() []float64 {
	if x != nil {
		return x.StopErp
	}
	return nil
}

func (x *ODEJointProperties) GetStopCfm() []float64 {
	if x != nil {
		return x.StopCfm
	}
	return nil
}

func (x *ODEJointProperties) GetFudgeFactor() []float64 {
	if x != nil {
		return x.FudgeFactor
	}
	return nil
}

func (x *ODEJointProperties) GetFmax() []float64 {
	if x != nil {
		return x.Fmax
	}
	return nil
}

func (x *ODEJointProperties) GetVel() []float64 {
	if x != nil {
		return x.Vel
	}
	return nil
}

var File_gazebo_msgs_ODEJointProperties_proto protoreflect.FileDescriptor

var file_gazebo_msgs_ODEJointProperties_proto_rawDesc = []byte{
	0x0a, 0x24, 0x67, 0x61, 0x7a, 0x65, 0x62, 0x6f, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4f, 0x44,
	0x45, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x61, 0x7a, 0x65, 0x62, 0x6f, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x22, 0xfe, 0x01, 0x0a, 0x12, 0x4f, 0x44, 0x45, 0x4a, 0x6f, 0x69, 0x6e, 0x74,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x61,
	0x6d, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x44, 0x61, 0x6d,
	0x70, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x69, 0x53, 0x74, 0x6f, 0x70, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x48, 0x69, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x4c, 0x6f, 0x53, 0x74, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x4c, 0x6f,
	0x53, 0x74, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x70, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x03, 0x45, 0x72, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x66, 0x6d, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x03, 0x43, 0x66, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70,
	0x45, 0x72, 0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x45,
	0x72, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x43, 0x66, 0x6d, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x43, 0x66, 0x6d, 0x12, 0x20, 0x0a, 0x0b,
	0x46, 0x75, 0x64, 0x67, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x0b, 0x46, 0x75, 0x64, 0x67, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x46, 0x6d, 0x61, 0x78, 0x18, 0x09, 0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x46, 0x6d,
	0x61, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x03, 0x56, 0x65, 0x6c, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x67, 0x61, 0x7a, 0x65, 0x62, 0x6f, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gazebo_msgs_ODEJointProperties_proto_rawDescOnce sync.Once
	file_gazebo_msgs_ODEJointProperties_proto_rawDescData = file_gazebo_msgs_ODEJointProperties_proto_rawDesc
)

func file_gazebo_msgs_ODEJointProperties_proto_rawDescGZIP() []byte {
	file_gazebo_msgs_ODEJointProperties_proto_rawDescOnce.Do(func() {
		file_gazebo_msgs_ODEJointProperties_proto_rawDescData = protoimpl.X.CompressGZIP(file_gazebo_msgs_ODEJointProperties_proto_rawDescData)
	})
	return file_gazebo_msgs_ODEJointProperties_proto_rawDescData
}

var file_gazebo_msgs_ODEJointProperties_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gazebo_msgs_ODEJointProperties_proto_goTypes = []any{
	(*ODEJointProperties)(nil), // 0: gazebo_msgs.ODEJointProperties
}
var file_gazebo_msgs_ODEJointProperties_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gazebo_msgs_ODEJointProperties_proto_init() }
func file_gazebo_msgs_ODEJointProperties_proto_init() {
	if File_gazebo_msgs_ODEJointProperties_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gazebo_msgs_ODEJointProperties_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gazebo_msgs_ODEJointProperties_proto_goTypes,
		DependencyIndexes: file_gazebo_msgs_ODEJointProperties_proto_depIdxs,
		MessageInfos:      file_gazebo_msgs_ODEJointProperties_proto_msgTypes,
	}.Build()
	File_gazebo_msgs_ODEJointProperties_proto = out.File
	file_gazebo_msgs_ODEJointProperties_proto_rawDesc = nil
	file_gazebo_msgs_ODEJointProperties_proto_goTypes = nil
	file_gazebo_msgs_ODEJointProperties_proto_depIdxs = nil
}
