// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: std_msgs/Int8.proto

package std_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Int8 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int32 `protobuf:"varint,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Int8) Reset() {
	*x = Int8{}
	if protoimpl.UnsafeEnabled {
		mi := &file_std_msgs_Int8_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int8) ProtoMessage() {}

func (x *Int8) ProtoReflect() protoreflect.Message {
	mi := &file_std_msgs_Int8_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int8.ProtoReflect.Descriptor instead.
func (*Int8) Descriptor() ([]byte, []int) {
	return file_std_msgs_Int8_proto_rawDescGZIP(), []int{0}
}

func (x *Int8) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_std_msgs_Int8_proto protoreflect.FileDescriptor

var file_std_msgs_Int8_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x49, 0x6e, 0x74, 0x38, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x22,
	0x1a, 0x0a, 0x04, 0x49, 0x6e, 0x74, 0x38, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x2a, 0x5a, 0x28, 0x67,
	0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x73,
	0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_std_msgs_Int8_proto_rawDescOnce sync.Once
	file_std_msgs_Int8_proto_rawDescData = file_std_msgs_Int8_proto_rawDesc
)

func file_std_msgs_Int8_proto_rawDescGZIP() []byte {
	file_std_msgs_Int8_proto_rawDescOnce.Do(func() {
		file_std_msgs_Int8_proto_rawDescData = protoimpl.X.CompressGZIP(file_std_msgs_Int8_proto_rawDescData)
	})
	return file_std_msgs_Int8_proto_rawDescData
}

var file_std_msgs_Int8_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_std_msgs_Int8_proto_goTypes = []any{
	(*Int8)(nil), // 0: std_msgs.Int8
}
var file_std_msgs_Int8_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_std_msgs_Int8_proto_init() }
func file_std_msgs_Int8_proto_init() {
	if File_std_msgs_Int8_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_std_msgs_Int8_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Int8); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_std_msgs_Int8_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_std_msgs_Int8_proto_goTypes,
		DependencyIndexes: file_std_msgs_Int8_proto_depIdxs,
		MessageInfos:      file_std_msgs_Int8_proto_msgTypes,
	}.Build()
	File_std_msgs_Int8_proto = out.File
	file_std_msgs_Int8_proto_rawDesc = nil
	file_std_msgs_Int8_proto_goTypes = nil
	file_std_msgs_Int8_proto_depIdxs = nil
}
