// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.6.1
// source: control_msgs/JointTolerance.proto

package control_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JointTolerance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Position     float64 `protobuf:"fixed64,2,opt,name=Position,proto3" json:"Position,omitempty"`
	Velocity     float64 `protobuf:"fixed64,3,opt,name=Velocity,proto3" json:"Velocity,omitempty"`
	Acceleration float64 `protobuf:"fixed64,4,opt,name=Acceleration,proto3" json:"Acceleration,omitempty"`
}

func (x *JointTolerance) Reset() {
	*x = JointTolerance{}
	mi := &file_control_msgs_JointTolerance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JointTolerance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointTolerance) ProtoMessage() {}

func (x *JointTolerance) ProtoReflect() protoreflect.Message {
	mi := &file_control_msgs_JointTolerance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointTolerance.ProtoReflect.Descriptor instead.
func (*JointTolerance) Descriptor() ([]byte, []int) {
	return file_control_msgs_JointTolerance_proto_rawDescGZIP(), []int{0}
}

func (x *JointTolerance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JointTolerance) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *JointTolerance) GetVelocity() float64 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *JointTolerance) GetAcceleration() float64 {
	if x != nil {
		return x.Acceleration
	}
	return 0
}

var File_control_msgs_JointTolerance_proto protoreflect.FileDescriptor

var file_control_msgs_JointTolerance_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4a,
	0x6f, 0x69, 0x6e, 0x74, 0x54, 0x6f, 0x6c, 0x65, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6d, 0x73, 0x67,
	0x73, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x6f, 0x6c, 0x65, 0x72,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x22, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x6c, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_control_msgs_JointTolerance_proto_rawDescOnce sync.Once
	file_control_msgs_JointTolerance_proto_rawDescData = file_control_msgs_JointTolerance_proto_rawDesc
)

func file_control_msgs_JointTolerance_proto_rawDescGZIP() []byte {
	file_control_msgs_JointTolerance_proto_rawDescOnce.Do(func() {
		file_control_msgs_JointTolerance_proto_rawDescData = protoimpl.X.CompressGZIP(file_control_msgs_JointTolerance_proto_rawDescData)
	})
	return file_control_msgs_JointTolerance_proto_rawDescData
}

var file_control_msgs_JointTolerance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_control_msgs_JointTolerance_proto_goTypes = []any{
	(*JointTolerance)(nil), // 0: control_msgs.JointTolerance
}
var file_control_msgs_JointTolerance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_msgs_JointTolerance_proto_init() }
func file_control_msgs_JointTolerance_proto_init() {
	if File_control_msgs_JointTolerance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_control_msgs_JointTolerance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_msgs_JointTolerance_proto_goTypes,
		DependencyIndexes: file_control_msgs_JointTolerance_proto_depIdxs,
		MessageInfos:      file_control_msgs_JointTolerance_proto_msgTypes,
	}.Build()
	File_control_msgs_JointTolerance_proto = out.File
	file_control_msgs_JointTolerance_proto_rawDesc = nil
	file_control_msgs_JointTolerance_proto_goTypes = nil
	file_control_msgs_JointTolerance_proto_depIdxs = nil
}
