// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: sound_play/SoundRequest.proto

package sound_play

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sound   int32   `protobuf:"varint,1,opt,name=Sound,proto3" json:"Sound,omitempty"`
	Command int32   `protobuf:"varint,2,opt,name=Command,proto3" json:"Command,omitempty"`
	Volume  float32 `protobuf:"fixed32,3,opt,name=Volume,proto3" json:"Volume,omitempty"`
	Arg     string  `protobuf:"bytes,4,opt,name=Arg,proto3" json:"Arg,omitempty"`
	Arg2    string  `protobuf:"bytes,5,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
}

func (x *SoundRequest) Reset() {
	*x = SoundRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sound_play_SoundRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundRequest) ProtoMessage() {}

func (x *SoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sound_play_SoundRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundRequest.ProtoReflect.Descriptor instead.
func (*SoundRequest) Descriptor() ([]byte, []int) {
	return file_sound_play_SoundRequest_proto_rawDescGZIP(), []int{0}
}

func (x *SoundRequest) GetSound() int32 {
	if x != nil {
		return x.Sound
	}
	return 0
}

func (x *SoundRequest) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *SoundRequest) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *SoundRequest) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *SoundRequest) GetArg2() string {
	if x != nil {
		return x.Arg2
	}
	return ""
}

var File_sound_play_SoundRequest_proto protoreflect.FileDescriptor

var file_sound_play_SoundRequest_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x53, 0x6f, 0x75,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x7c, 0x0a, 0x0c, 0x53,
	0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x6f, 0x75, 0x6e,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x72, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x41, 0x72, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x72, 0x67, 0x32, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x72, 0x67, 0x32, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x6f, 0x5f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x6f, 0x75,
	0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sound_play_SoundRequest_proto_rawDescOnce sync.Once
	file_sound_play_SoundRequest_proto_rawDescData = file_sound_play_SoundRequest_proto_rawDesc
)

func file_sound_play_SoundRequest_proto_rawDescGZIP() []byte {
	file_sound_play_SoundRequest_proto_rawDescOnce.Do(func() {
		file_sound_play_SoundRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_sound_play_SoundRequest_proto_rawDescData)
	})
	return file_sound_play_SoundRequest_proto_rawDescData
}

var file_sound_play_SoundRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sound_play_SoundRequest_proto_goTypes = []any{
	(*SoundRequest)(nil), // 0: sound_play.SoundRequest
}
var file_sound_play_SoundRequest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sound_play_SoundRequest_proto_init() }
func file_sound_play_SoundRequest_proto_init() {
	if File_sound_play_SoundRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sound_play_SoundRequest_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sound_play_SoundRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sound_play_SoundRequest_proto_goTypes,
		DependencyIndexes: file_sound_play_SoundRequest_proto_depIdxs,
		MessageInfos:      file_sound_play_SoundRequest_proto_msgTypes,
	}.Build()
	File_sound_play_SoundRequest_proto = out.File
	file_sound_play_SoundRequest_proto_rawDesc = nil
	file_sound_play_SoundRequest_proto_goTypes = nil
	file_sound_play_SoundRequest_proto_depIdxs = nil
}
