// This file is auto-generated by rostoproto, do not edit Manually!!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: sound_play/SoundRequestActionFeedback.proto

package sound_play

import (
	actionlib_msgs "go_agent/telemetry/genproto/ros/actionlib_msgs"
	std_msgs "go_agent/telemetry/genproto/ros/std_msgs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoundRequestActionFeedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *std_msgs.Header           `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Status   *actionlib_msgs.GoalStatus `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Feedback *SoundRequestFeedback      `protobuf:"bytes,3,opt,name=Feedback,proto3" json:"Feedback,omitempty"`
}

func (x *SoundRequestActionFeedback) Reset() {
	*x = SoundRequestActionFeedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sound_play_SoundRequestActionFeedback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoundRequestActionFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundRequestActionFeedback) ProtoMessage() {}

func (x *SoundRequestActionFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_sound_play_SoundRequestActionFeedback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundRequestActionFeedback.ProtoReflect.Descriptor instead.
func (*SoundRequestActionFeedback) Descriptor() ([]byte, []int) {
	return file_sound_play_SoundRequestActionFeedback_proto_rawDescGZIP(), []int{0}
}

func (x *SoundRequestActionFeedback) GetHeader() *std_msgs.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SoundRequestActionFeedback) GetStatus() *actionlib_msgs.GoalStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SoundRequestActionFeedback) GetFeedback() *SoundRequestFeedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

var File_sound_play_SoundRequestActionFeedback_proto protoreflect.FileDescriptor

var file_sound_play_SoundRequestActionFeedback_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x53, 0x6f, 0x75,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73,
	0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x1a, 0x1f, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x6c, 0x69, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x47, 0x6f, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x73, 0x6f, 0x75, 0x6e,
	0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x15, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x1a, 0x53, 0x6f, 0x75,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x28, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x32, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x6c, 0x69, 0x62, 0x5f, 0x6d, 0x73,
	0x67, 0x73, 0x2e, 0x47, 0x6f, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x08, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x2e, 0x53, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x08, 0x46, 0x65, 0x65, 0x64, 0x62,
	0x61, 0x63, 0x6b, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f,
	0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x73, 0x2f, 0x73, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x70, 0x6c, 0x61,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sound_play_SoundRequestActionFeedback_proto_rawDescOnce sync.Once
	file_sound_play_SoundRequestActionFeedback_proto_rawDescData = file_sound_play_SoundRequestActionFeedback_proto_rawDesc
)

func file_sound_play_SoundRequestActionFeedback_proto_rawDescGZIP() []byte {
	file_sound_play_SoundRequestActionFeedback_proto_rawDescOnce.Do(func() {
		file_sound_play_SoundRequestActionFeedback_proto_rawDescData = protoimpl.X.CompressGZIP(file_sound_play_SoundRequestActionFeedback_proto_rawDescData)
	})
	return file_sound_play_SoundRequestActionFeedback_proto_rawDescData
}

var file_sound_play_SoundRequestActionFeedback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sound_play_SoundRequestActionFeedback_proto_goTypes = []any{
	(*SoundRequestActionFeedback)(nil), // 0: sound_play.SoundRequestActionFeedback
	(*std_msgs.Header)(nil),            // 1: std_msgs.Header
	(*actionlib_msgs.GoalStatus)(nil),  // 2: actionlib_msgs.GoalStatus
	(*SoundRequestFeedback)(nil),       // 3: sound_play.SoundRequestFeedback
}
var file_sound_play_SoundRequestActionFeedback_proto_depIdxs = []int32{
	1, // 0: sound_play.SoundRequestActionFeedback.Header:type_name -> std_msgs.Header
	2, // 1: sound_play.SoundRequestActionFeedback.Status:type_name -> actionlib_msgs.GoalStatus
	3, // 2: sound_play.SoundRequestActionFeedback.Feedback:type_name -> sound_play.SoundRequestFeedback
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sound_play_SoundRequestActionFeedback_proto_init() }
func file_sound_play_SoundRequestActionFeedback_proto_init() {
	if File_sound_play_SoundRequestActionFeedback_proto != nil {
		return
	}
	file_sound_play_SoundRequestFeedback_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sound_play_SoundRequestActionFeedback_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SoundRequestActionFeedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sound_play_SoundRequestActionFeedback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sound_play_SoundRequestActionFeedback_proto_goTypes,
		DependencyIndexes: file_sound_play_SoundRequestActionFeedback_proto_depIdxs,
		MessageInfos:      file_sound_play_SoundRequestActionFeedback_proto_msgTypes,
	}.Build()
	File_sound_play_SoundRequestActionFeedback_proto = out.File
	file_sound_play_SoundRequestActionFeedback_proto_rawDesc = nil
	file_sound_play_SoundRequestActionFeedback_proto_goTypes = nil
	file_sound_play_SoundRequestActionFeedback_proto_depIdxs = nil
}
