//autogenerated:yes
//nolint:revive,lll
package base_local_planner

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type Position2DInt struct {
    msg.Package `ros:"base_local_planner"`
    X int64
    Y int64
}

