//autogenerated:yes
//nolint:revive,lll
package controller_manager_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ControllerState struct {
    msg.Package `ros:"controller_manager_msgs"`
    Name string
    State string
    Type string
    ClaimedResources []HardwareInterfaceResources
}

