//autogenerated:yes
//nolint:revive,lll
package controller_manager_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type ControllerStatistics struct {
    msg.Package `ros:"controller_manager_msgs"`
    Name string
    Type string
    Timestamp time.Time
    Running bool
    MaxTime time.Duration
    MeanTime time.Duration
    VarianceTime time.Duration
    NumControlLoopOverruns int32
    TimeLastControlLoopOverrun time.Time
}

