//autogenerated:yes
//nolint:revive,lll
package controller_manager_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ListControllersReq struct {
    msg.Package `ros:"controller_manager_msgs"`
}



type ListControllersRes struct {
    msg.Package `ros:"controller_manager_msgs"`
    Controller []ControllerState
}

type ListControllers struct {
    msg.Package `ros:"controller_manager_msgs"`
    ListControllersReq
    ListControllersRes
}
