//autogenerated:yes
//nolint:revive,lll
package controller_manager_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ListControllerTypesReq struct {
    msg.Package `ros:"controller_manager_msgs"`
}



type ListControllerTypesRes struct {
    msg.Package `ros:"controller_manager_msgs"`
    Types []string
    BaseClasses []string
}

type ListControllerTypes struct {
    msg.Package `ros:"controller_manager_msgs"`
    ListControllerTypesReq
    ListControllerTypesRes
}
