//autogenerated:yes
//nolint:revive,lll
package controller_manager_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type LoadControllerReq struct {
    msg.Package `ros:"controller_manager_msgs"`
    Name string
}



type LoadControllerRes struct {
    msg.Package `ros:"controller_manager_msgs"`
    Ok bool
}

type LoadController struct {
    msg.Package `ros:"controller_manager_msgs"`
    LoadControllerReq
    LoadControllerRes
}
