//autogenerated:yes
//nolint:revive,lll
package controller_manager_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type UnloadControllerReq struct {
    msg.Package `ros:"controller_manager_msgs"`
    Name string
}



type UnloadControllerRes struct {
    msg.Package `ros:"controller_manager_msgs"`
    Ok bool
}

type UnloadController struct {
    msg.Package `ros:"controller_manager_msgs"`
    UnloadControllerReq
    UnloadControllerRes
}
