//autogenerated:yes
//nolint:revive,lll
package controller_manager_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ReloadControllerLibrariesReq struct {
    msg.Package `ros:"controller_manager_msgs"`
    ForceKill bool
}



type ReloadControllerLibrariesRes struct {
    msg.Package `ros:"controller_manager_msgs"`
    Ok bool
}

type ReloadControllerLibraries struct {
    msg.Package `ros:"controller_manager_msgs"`
    ReloadControllerLibrariesReq
    ReloadControllerLibrariesRes
}
