//autogenerated:yes
//nolint:revive,lll
package realsense2_camera

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type IMUInfo struct {
    msg.Package `ros:"realsense2_camera"`
    FrameId string
    Data [12]float64
    NoiseVariances [3]float64
    BiasVariances [3]float64
}

