//autogenerated:yes
//nolint:revive,lll
package realsense2_camera

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "go_agent/telemetry/gengo/ros/std_msgs"
)


type Metadata struct {
    msg.Package `ros:"realsense2_camera"`
    Header std_msgs.Header
    JsonData string
}

