//autogenerated:yes
//nolint:revive,lll
package realsense2_camera

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type DeviceInfoReq struct {
    msg.Package `ros:"realsense2_camera"`
}



type DeviceInfoRes struct {
    msg.Package `ros:"realsense2_camera"`
    DeviceName string
    SerialNumber string
    FirmwareVersion string
    UsbTypeDescriptor string
    FirmwareUpdateId string
    Sensors string
}

type DeviceInfo struct {
    msg.Package `ros:"realsense2_camera"`
    DeviceInfoReq
    DeviceInfoRes
}
